startmesaj =  "**🎉 ᴍᴇʀʜᴀʙᴀ\n\n🗨️ ʙᴇɴɪ ɢʀᴜʙᴜɴᴀ ᴇᴋʟᴇᴍᴇʏᴇ ɴᴇ ᴅᴇʀsɪɴ, ᴇʟɪᴍᴅᴇɴ ɢᴇʟᴇɴ ʜᴇʀşᴇʏɪ ʏᴀᴘᴍᴀʏᴀ ʜᴀᴢɪʀɪᴍ ...\n\n💕 sɪᴢᴇ ʏᴀʀᴅɪᴍᴄɪ ᴏʟᴀʙɪʟᴍᴇᴍ ɪᴄ̧ɪɴ ᴀşşᴀɢ̆ɪᴅᴀᴋɪ ʙᴜᴛᴏɴʟᴀʀɪ ᴋᴜʟʟᴀɴɪɴ ...**"
startbutton = "**🗯️ ʏᴀᴘᴀʏ ᴢᴇᴋᴀ ᴍᴏᴅᴜ :\n✓ ᴏ̈ʀɴᴇᴋ ᴋᴜʟʟᴀɴɪᴍɪ :\n\n buket Einstein kimdir ?\n\n ✓ ᴋɪsᴀᴄᴀ buket ʏᴀᴢᴅɪᴋᴛᴀɴ sᴏɴʀᴀ sᴏʀᴜɴᴜᴢᴜ ʏᴀᴢɪɴ . **"
noadmin = "**✓  sᴀᴅᴇᴄᴇ ᴀᴅᴍɪɴʟᴇʀ ᴋᴜʟʟᴀɴᴀʙɪʟɪʀ ...**"
nogroup = "**✓  sᴀᴅᴇᴄᴇ ɢʀᴜᴘʟᴀʀᴅᴀ ᴋᴜʟʟᴀɴɪʟᴀʙɪʟɪʀ .**"
noowner = "**➻ ᴏʟᴀᴍᴀᴢ, sᴀʜɪʙɪᴍ ᴅᴇɢɪʟsɪɴ 😳\n» ɴᴏᴛ : sᴀᴅᴇᴄᴇ sᴀʜɪʙɪᴍ ᴋᴜʟʟᴀɴᴀʙɪʟɪʀ .**"
etikett = "**🔺 ᴇᴛɪᴋᴇᴛ ᴋᴏᴍᴜᴛ 🔺\n\n» /utag\n   - ᴜ̈ʏᴇʟᴇʀɪ ᴛᴏᴘʟᴜ ᴇᴛɪᴋᴇᴛʟᴇʀɪᴍ .\n\n» /tag\n   - ᴜ̈ʏᴇʟᴇʀɪ ᴛᴇᴋ ᴛᴇᴋ ᴇᴛɪᴋᴇᴛʟᴇʀɪᴍ . \n\n» /atag\n   - ʏᴏ̈ɴᴇᴛɪᴄɪʟᴇʀɪ ᴛᴇᴋ ᴛᴇᴋ ᴇᴛɪᴋᴇᴛʟᴇʀɪᴍ .\n\n» /etag\n   - ᴜ̈ʏᴇʟᴇʀɪ ᴇᴍᴏᴊɪʟᴇʀʟᴇ ᴇᴛɪᴋᴇᴛʟᴇʀɪᴍ .\n\n» /stag\n   - ᴜ̈ʏᴇʟᴇʀɪ sᴏ̈ᴢʟᴇʀʟᴇ ᴇᴛɪᴋᴇᴛʟᴇʀɪᴍ .\n\n» /vtag\n   - ᴜ̈ʏᴇʟᴇʀɪ sᴏʀᴜʟᴀʀʟᴀ ᴇᴛɪᴋᴇᴛʟᴇʀɪᴍ .\n\n» /otag\n   - ᴜ̈ʏᴇʟᴇʀɪ ʀᴜ̈ᴛʙᴇʟᴇʀʟᴇ ᴇᴛɪᴋᴇᴛʟᴇʀɪᴍ .\n\n» /cancel\n   - ᴇᴛɪᴋᴇᴛʟᴇᴍᴇʏɪ ᴅᴜʀᴅᴜʀᴜʀᴜᴍ .**"
extraa = "**🔺 ᴇxᴛʀᴀ ᴋᴏᴍᴜᴛ 🔺\n\n» /bul\n   - ᴀɴɪɴᴅᴀ şᴀʀᴋɪ ɪɴᴅɪʀɪʀɪᴍ .\n\n» /vbul\n   - ᴀɴɪɴᴅᴀ ᴠɪᴅᴇᴏ ɪɴᴅɪʀɪʀɪᴍ .\n\n» /ara\n   - ʟɪɴᴋ ʜᴀʟɪɴᴅᴇ ɪɴᴅɪʀɪʀɪᴍ .\n\n» /reload\n   - ᴀᴅᴍɪɴ ʟɪsᴛᴇsɪɴɪ ɢᴜ̈ɴᴄᴇʟʟᴇʀɪᴍ .\n\n» /dels\n   - ᴛᴏᴘʟᴜ ᴍᴇsᴀᴊ sɪʟᴇʀɪᴍ .\n\n» /id\n   - ɢʀᴜᴘ & ᴋᴜʟʟᴀɴɪᴄɪ ɪᴅ'sɪɴɪ ᴏ̈ɢ̆ʀᴇɴɪɴ .\n\n» /iletisim\n   - ʙɪᴢɪᴍʟᴇ ɪʟᴇᴛɪşɪᴍᴇ ɢᴇᴄ̧ɪɴ .\n\n» /grup\n   - ɢʀᴜᴘ ʜᴀᴋᴋɪɴᴅᴀ ʙɪʟɢɪ ᴠᴇʀɪʀɪᴍ .\n\n» /kurt\n   - ᴋᴜʀᴛ ᴏʏᴜɴᴜ ʀᴏʟʟᴇʀɪ ...\n\n» /sohbetmod\n   - sᴏʜʙᴇᴛ ᴍᴏᴅᴜ ɪᴄ‌ɪɴ ᴋᴜʟʟᴀɴɪɴ  ...\n\n» /yas\n   - ᴅᴏɢ̆ᴜᴍ ɢᴜ̈ɴᴜ̈ɴᴜ̈ᴢᴜ̈ ɢᴏ̈sᴛᴇʀɪʀɪᴍ.\n\n/burc\n   ʙᴜʀᴄᴜɴᴜᴢᴜ ɢᴏ̈sᴛᴇʀɪʀɪᴍ.**"
sahipp = "**🔺 sᴀʜɪᴘ ᴋᴏᴍᴜᴛ 🔺\n\n» /istatistik\n   - ɪsᴛᴀᴛɪsᴛɪᴋʟᴇʀɪᴍɪ ɢᴏ̈sᴛᴇʀɪʀɪᴍ .\n\n» /reklam\n   - ɢʀᴜᴘʟᴀʀᴀ ʀᴇᴋʟᴀᴍ ᴀᴛᴀʀɪᴍ .**"
oyunn = "**🔺  ᴏʏᴜɴ ᴋᴏᴍᴜᴛ  🔺\n\n» /d\n   - ᴅᴏɢ̆ʀᴜʟᴜᴋ sᴏʀᴜsᴜ sᴏʀᴀʀɪᴍ .\n\n» /c\n   - ᴄᴇsᴀʀᴇᴛ sᴏʀᴜsᴜ sᴏʀᴀʀɪᴍ .\n\n» /soz\n   - ᴄ̧ᴇşɪᴛʟɪ sᴏ̈ᴢʟᴇʀ ᴀᴛᴀʀɪᴍ .\n\n» /eros\n   -  ɢʀᴜᴘᴛᴀᴋɪ ᴜ̈ʏᴇʟᴇʀɪ sʜɪᴘʟᴇʀɪᴍ .\n\n» /slap\n   - ᴇɢ̆ʟᴇɴᴍᴇᴋ ɪᴄ̧ɪɴ ᴋᴜʟʟᴀɴɪɴ .\n\n» /turet\n   - ᴋᴇʟɪᴍᴇ ᴛᴜ̈ʀᴇᴛ ᴏʏᴜɴᴜ ᴀᴄ̧ᴀʀɪᴍ .\n\n» /kapat\n   - ᴋᴇʟɪᴍᴇ ᴛᴜ̈ʀᴇᴛ ᴏʏᴜɴᴜ ᴋᴀᴘᴀᴛɪʀɪᴍ .\n\n» /pass\n   - ᴋᴇʟɪᴍᴇʏɪ ᴘᴀss ɢᴇᴄ̧ᴇʀɪᴍ .**"
ibaslama = "**🗨️ ᴇᴛɪᴋᴇᴛʟᴇᴍᴇʏᴇ ʙᴀşʟɪʏᴏʀᴜᴍ ...**"

emj = " ❤️ 🧡 💛 💚 💙 💜 🖤 🤍 🤎 🙂 🙃 😉 😌 😍 🥰 😘 😗 😙 😚 😋 😛 😝 😜 🤪 🤨 🧐 🤓 😎 🤩 🥳 😏 😒 " \
        "😞 😔 😟 😕 🙁 😣 😖 😫 😩 🥺 😢 😭 😤 😠 😡 🤯 😳 🥵 🥶 😱 😨 😰 😥 😓 🤗 🤔 🤭 🤫 🤥 😶 😐 😑 😬 🙄 " \
        "😯 😦 😧 😮 😲 🥱 😴 🤤 😪 😵 🤐 🥴 🤢 🤮 🤧 😷 🤒 🤕 🤑 🤠 😈 👿 👹 👺 🤡  👻 💀 👽 👾 🤖 🎃 😺 😸 😹 " \
        "😻 😼 😽 🙀 😿 😾 ❄️ 🌺 🌨 🌩 ⛈ 🌧 ☁️ ☀️ 🌈 🌪 ✨ 🌟 ☃️ 🪐 🌏 🌙 🌔 🌚 🌝 🕊 🦩 🦦 🌱 🌿 ☘ 🍂 🌹 🥀 🌾 " \
        "🌦 🍃 🎋".split(" ")

rutbe = (
"ᴇᴍɴɪʏᴇᴛ ᴍᴜ̈ᴅᴜ̈ʀᴜ̈", "ᴇᴍɴɪʏᴇᴛ ᴀᴍɪʀɪ", "ʙᴀşᴋᴏᴍɪsᴇʀ", "ᴋᴏᴍɪsᴇʀ", "ᴏʀɢᴇɴᴇʀᴀʟ", "ᴋᴜʀᴍᴀʏ", "ᴘɪʏᴀᴅᴇ", "sᴜ̈ᴠᴀʀɪ", "ᴛᴀɴᴋᴄ̧ɪ", "ᴛᴏᴘᴄ̧ᴜ", "ᴋᴏʀɢᴇɴᴇʀᴀʟ", "ᴛᴜ̈ᴍɢᴇɴᴇʀᴀʟ", "ᴛᴜɢ̆ɢᴇɴᴇʀᴀʟ",
"ᴀʟʙᴀʏ", "ʏᴀʀʙᴀʏ", "ʙɪɴʙᴀşɪ", "ʏᴜ̈ᴢʙᴀşɪ", "ᴜ̈sᴛᴇɢ̆ᴍᴇɴ", "ᴛᴇɢ̆ᴍᴇɴ", "ᴀsᴛᴇɢ̆ᴍᴇɴ", "ᴀsᴛsᴜʙᴀʏ", "ᴀsᴛsᴜʙᴀʏ ᴜ̈sᴛᴄ̧ᴀᴠᴜş", "ᴀsᴛsᴜʙᴀʏ ᴄ̧ᴀᴠᴜş", "ᴜᴢᴍᴀɴ ᴄ̧ᴀᴠᴜş", "ᴜᴢᴍᴀɴ ᴏɴʙᴀşɪ", "ᴄ̧ᴀᴠᴜş", "ᴏɴʙᴀşɪ",
)

romantiksoz = (
"Uçurumdan ne farkın var sevgili? Bu yüzden sana YAR demek yakışır.","Ellerimi açıp gökyüzüne ettiğim duaların karşılığı sensin.","Olur da ayrı düşersek sevgilim, bir gün benimle karşılaş ve benimle yeniden tanış.","Hayatıma gel. Seninle yaşamak da ölmek de kutlu günüm olur sevgilim.","Seni tanımadan önce sevilmeden nasıl yaşamışım bilmiyorum. Bana verdiğin tüm sevgi için minnettarım sevgilim.","Yan yana ayrı yazılır, sımsıkı birleşik. Biz yan yana olsak bile sımsıkı kalalım.","Bir yanda sayfalarca aşk sözleri sıralasam sana diyorum. Sonra bir anda gözlerini görüyorum, seni seviyorum cümlesine saklıyorum aşk sözlerimizi.",
"Her sabah gözlerimi sana açmak istiyorum. Kalbime girdiğin ilk günden beri sana uyanmalarım hiç değişmedi.","Farz et ki bu aşk adını kalbime mühürledi, adını dilimde sakladı.","Sevgilim, seninle bir hayat geçirmek değil sensiz bir hayat geçirmemek istiyorum.","Bir ömrüm daha olsa seni daha erken bulurum. Geçirdiğimiz tüm yıllar saatlere, günlere saniyelere dönüşüyor. Seni sevmeye doyamıyorum.","Ne kadar ömrümüz kaldı sevgilim? Seni ne kadar sevdiğimi anlatmaya yetecek mi?","Bir zaman diliminde seni yaşayıp bitirmek değil aşk, her sabah doğan güneş gibi yeniden başlamak.","Sorma bana kaç yaşındasın diye, seni tanıdığım gün doğduğumu anladım.",
"Aşk zaten bakınca gözlerine iki lafı bir araya getirememek değil midir? Seviyorum dedikten sonra tükenir nefesim.","Tüm günahlarıma tövbe ettikten sonra çıktın karşıma. Sen benim dualarımın kabul olduğuna inanışımsın.","Sağanak gibi sev beni, senden kaçmam mümkün olmasın.","O kadar güzel gülüyordun ki, seni sevmesem sevgim ziyan olacaktı .","Ah bu hayat! Sensiz geçen günlerin telafisi nasıl olacak?","Aynı duada amin demek lazım bize. Benim yaramın şifasına sen iyi gelirsin.","Güneş batmış, gece gelmiş, ben gülüşünde kalmışım.","Aşk, tüm dünyaya kafa tutacak kadar güçlüyken bir gülüşe esir düşmektir.","Kimseye boyun eğmezken sana eğildim, beni sensiz koyma.",
"Ne önemi var hangi şehirde olduğumuzun, benim memleketim senin ellerin.","Allah’ım beni öyle bir sonbahar ayazı öldür ki, sevdiğim mezarıma koyacak tek bir gül bile bulamazsın.","İçin ağlasa da kim duyar seni? Kim anlar dışarıdan olup biteni? Leyla’nın yüzünü görenler bilir: Mecnun’un kalbine batan dikeni.","Sana romantik sözler yazıp kalbini boyamak istemem, sana gözlerimle gözlerine sözler yazıp yaşamak isterim aşkım.","Ve sevda darağacında, elimi çeksem senden olacağım, çekmesem kendimden.","Uyuma! Sabaha kadar kahve içelim camdan dışarıyı izleyelim. Yağmur sokaklarda yağsın sen içime yağ.","Bir hasret kadar uzak olsan da bir nefes kadar yakınsın yüreğime. Ömrüme ömür katan yarim.",
"Kavuşmak belki bir gün ama unutma prenses suya aşık ateşler aşığına kavuşunca ölür.","Ağır yürüyorum diye kızıyorlar. Yüküm ağır, yüreğimde seni taşıyorum anlamıyorlar.","Kaçmak istedikçe sana yakalanıyorum. Söndürmek istedikçe sana yanıyorum. Yenildim işte! Yine de seviyorum.","Gözlerinden göğsüme sayısız yıldız akar. Bir gülüşün içimde binlerce lamba yakar.","Gözlerinin ‘kahve’sinden koy ömrüme, kırk yılın hatırına ‘sen’de kalayım.","Güneşin buz tuttuğu yerde bir alev görürsen, Bil ki o yalnız senin için yanan kalbimdir.","Sonra sen geldin, güldün. Gönlümdeki en kurak topraklar papatya bahçesi oldu.","Ah be sevgili! Slow müzik tadındaydı beraberliğimiz, gidişin remix’li oldu; kop’tun gidiyorsun.",
"Seni sevdim diye kızdıysan, sende beni sev de intikam al.","Manşet: Aşk kalemiyle yazanların değil, yüreğiyle yananların işidir.","Sen uçsuz bucaksız hayallerimin tek sahibisin.","Gerçek aşkta ne vefa vardır ne cefa.","Vazgeçilmez olan sen değildin. Vazgeçmek istemeyen bendim.","Eğer bir gün bana dönecek olursan, eski günlerimi getir !","Sana çay yapsam, benimle ömrüm soğuyana kadar kalır mısın .","Dünyanın en kötü çöpçüsüydüm. Gülüşünden arta kalanları topluyordum.","O kadar çok bu kadar çok diyemem sevgin için aşığım sana gözlerimin ışığısın.","Benden seni seviyorum dememi bekleme sevgili. Bizde zikir sessiz çekilir.","Aşk kalemiyle yazanların değil, yüreğiyle yananların işidir.","Sana da kırgınım papatya! Bir seviyorumu sığdıramadın onca yaprağına.",
"Okyanusta ölmez de insan, gider bir kaşık sevdada boğulur.","Aşk, iki insan bir münasebet değil, bir nefeslik ömürde binlerce mana demek.","Seni seviyorum demek, dünyanın en güzel cümlesi.","Seninle geçirdiğim her an, hayatın en değerli hediyesi.","Gözlerin benim için yıldızlar gibi, kalbim seninle aydınlanıyor.","Kalbimde sadece senin için bir yer var, sen benim için özelsin.","Seninle hayatım, renklerle dolu bir resim gibi, birlikte bir sanat eseri yaratıyoruz.","Sana olan aşkım, sonsuz okyanusların bile büyüklüğünü sığdıramaz.","Gözlerin dünyamı aydınlatıyor, sesin ruhumu okşuyor, seni seviyorum.","Seni sevmek, kalbimde hiç solmayacak bir çiçek gibi.","Hayatın en güzel yanı, seninle anlam kazanıyor.","Kalbimdeki en güzel melodiyi senin için çalıyorum, seni seviyorum.",
"Gözlerine baktığımda, aşkın en güzel resmini görüyorum.","Seninle birlikte olduğum her an, zaman duruyor ve sonsuzluğa dönüşüyor.","Sonsuzluğu birlikte keşfetmek istiyorum, çünkü seninle hayat bir masal gibi.","Seni düşündüğüm her an, kalbim coşkuyla doluyor ve aşkınla yanıyor.","Seni sevmek, nefes almak gibi, vazgeçilmez bir ihtiyaç.","Gözlerin benim için yıldızlar gibi, kalbim seninle aydınlanıyor.","Hangi ara seni bu kadar sevdim bilemedim. Gecemi aydınlatan, gündüzümü ışıtan yar.","Çok solcu gördüm ben bu hayatta ama kimse senin gibi kalıcı devrim yapmadı “SOL” yanımda.","Sonunda aşk acısı olsa da sev, çok sev. Usul usul gir yüreğime, kalbim bağrım çatlasın!","İyi geceler canım derdin. Gecenin iyiliğinden çok, canın olma düşüncesi yeşerir dururdu içimde.",
"Sen güldün ben bir yudum daha içtim çaydan. Yoksa nasıl açıklardım, içimdeki sıcaklığı.","Sana en muhtaç olduğum şu anda gel. Yaşamak olsan da gel, ölüm olsan da gel.","Bana yüzünü dönme gece oluyor sanıyorum.","Yalansan yalanı severim elimde değil.","Kendime gelemiyorum, sana gelsem olur mu?","Sevmek bir renkse, gel gökkuşağım ol.","Yanlış olduğunu bile bile yürüdüğüm yolsun sen.","Yanağında açan güle âşık oldu bu can.","Aklım mı? O yüzsüz bir misafir. Hep sende kalıyor.","Bir umutla beklediğim en güzel yarınsın.","Sen bile bilemezsin gülüşün ben de kaç bahar eder.","Denize ilk kez giren çocuk masumiyetiyle seviyorum seni. Boğulacakmışım gibi.","Ey canımın sahibi Yar! Sen benimle olduktan sonra kaybettiklerimin ne önemi var.",
"Aşk ve yangın birini daima bitirir. Netice olarak ikisi de düştüğü yeri yakar.","Aşk tenini nefsetmek değil, ruhunu resmetmektir. Bedenini bedene değil, kalbi kalbe hapsetmektir.","Sen benim yıldız kayarken tuttuğum dilek değil ezan okunurken ettiğim duamsın.","Dışarıya yağmur, yüreğime hasret, fikrime sen. Nasıl yağıyorsunuz üçünüz birden bir bilsen.","Ya tam açacaksın yüreğini, ya da hiç yeltenmeyeceksin! Grisi yoktur aşkın; ya siyahi, ya beyazı seçeceksin.","Git diyorsun da, olmuyor işte git demekle. Ben de sana sev diyorum mesela. Sevebiliyor musun?","Kaybetmekten asla korkmadığım son sınavıma yüreğinin dersliğinde giriyorum. Öğrenci benim, öğretmen sensin.","Yüreğini yasla bana sevgili, bir ömür birbirimize yük olalım.",
"Fizikte bir teoriye göre bazı sesler kalp atışınızın hızlanmasına neden olabilir. Benim için bu ses senin sesin.","Okyanusla, gökyüzü gibiydik biz seninle. İkimizde maviydik, birlikte gibiydik. Aslında hiç birleşmemiştik…","Senin gülüşün ilkbaharda daha renkliydi.","Geleydin bir çay içimi, sen çay dökerdin, ben içimi.","Uçurum uçurum gözlerine baktığım sensin.","Kalbim ki kendisine kefilim. Adınla uyandı bu sabah.","Yanıma gelmediğinde rüyalarıma beklerim.","Gittin… Ve solumda kaldın ve soluğumda ve sonumda.","Yeter ki diline dolanayım; istersen bir küfür, istersen bir şarkı olayım.","Bütün şairler sana mı aşıktı ki her okuduğum şiirde, dinlediğim ezgide sen vardın.","O senin neyin olur dediler. Uzaktan dedim uzaktan yandığım olur kendisi.",
"Ben utangaç bir kalbi taşırım geceden. Ben sana aşık olduğumu, ölsem söyleyemem .","Bazen aşk iki lafı bir araya getirememektir. Seni dersin… Tükenir nefesin.","Bana kimse sen gibi baktı mı bilmem, ama ben kimseye sana baktığım gibi bakmadım.","Sensiz bir gün daha akşam oldu. İçim el vermiyor. Biz buna “gün” demeyelim.","Sen aklım ve kalbim arasında kalan en güzel çaresizliğimsin.","Sen benim gökyüzüne gönderdiğim duamın yeryüzündeki cevabısın.","Şurama batan, şurama batana özlem demeselerdi bıçak derdim.","Ad koyunca büyüsü bozulur diye, isimsiz, izinsiz, içimden seviyorum seni.","O kadar güzel gülüyor ki tamam diyorum bu kadar yaşadığım yeter.","Bir gün bir yerde tekrar karşılaşırsak eğer, benimle yine tanış yine seveyim.","Tahir gibi sev mesela, özür dilerim daha önce gelemediğim için de.",
"Aklımda işin yok! Durup durup aklıma gelme… Yanıma gel, mevzu kalbimde!","Sen benim görmek için, bakmaya gerek bile duymadığım ezberimsin.","Ölümü boş ver, kefenim sen kokacak mı onu söyle ?","En modern alışkanlıktır ölmek ben seni doğasıya seviyorum.","Derdimin dermanı sensin. Bana bir duanın amini gerek.","Sevdim, Çünkü bir tek ona sarılınca yuva gibi kokuyordu içim.","Sen bana Allah’ın emanetisin.","Seni sevmek aşktır bana.","Sensin, kalbim değildir. Böyle göğsüme vuran…","Yar, bütün şiirlerime sebep ettim seni, hakkını helal et!","Sen olmayınca buralar buz gibi.","Sensizlik bir iklim adı şimdilerde…","Canımın içi sen hangi şiirden kaçıp geldin yüreğimin orta yerine.","Sensiz geçen günlerimin kazası yok sevgilim.","Seni düşünürken içim geçmiş, severken de ömrüm.",
"Yemin ederim intiharsın sen seve seve edilen.","Konu ne zaman senden açılsa kapatmaya kıyamıyorum.","Sen en güzel şiirlerin bile kuramadığı kafiyesin.","Sen benim ilk şiirim, ilk kavgam, sen benim 17 yaşımsın.","Aşkın her hali güzeldi, ben SEN halini sevdim.","İnsanın en büyük zenginliği onu anlayan birine sahip olması derler. Demek ki ben yeryüzünde cenneti yaşamışım seninle…","Seni uzaktan sevmeyi öğrendim, bakmadan görmeyi, sana kavuşmak için sabretmeyi öğrendim. Her şeyden biraz öğretti sevgin bana, sensiz yaşamak dışında.","O kadar güzel bakıyor ki gözlerin, tüm dünya kör olsun istiyorum.","Bir kurulu düzenimiz olsun seninle, mesela dizlerine yatmadan uyumuş saymayayım kendimi .",
)

kapaksoz = (
"Senin gibi bozukları kumbarada biriktirir, geleceğe yatırım yaparım. Ha, çok mu sıkıştım, hiç düşünmem hemen harcarım.","Konuştuğun kadar şerefli olsaydı hislerin, şerefini iki paralık etmezdi seçimlerin.","Demişsin ya, onun gibilerini cebimden çıkarırım diye. Dinle! Ben senin gibilerini tespihime dizerim, tövbe tövbe diye çekerim.","Canım, karakterin yere düşmüş. Onu bir alıver oradan.","Çakalların özgürlüğü Aslan yerden kalkana kadardır.",
"Zoruna gittiğini duydum. Güzel yer, ben de gitmiştim!","Sen hala kabullenmedin mi sevap sandığın günahlarını!","Seni unuttum sanma, sadece değerin kadar hatırlıyorum.","Bugün laf koymayacağım. Çay koydum; gel, iç, insanlık gör.","Eksik olmayın, dedik. Fazla olmaya başladınız. Hayırdır?","Ben insanları harcamayı iyi bilirim. Yeter ki bozuk olsun.","Kimi insan girdiğinde odayı aydınlatır, kimide çıktığında…","Oturur sana şerefi anlatırdım ama, kaybettiği bir şeyi dinlemek ağır gelir insana.",
"Bugün laf koymıcam. Çay koydum; gel, iç, insanlık gör.","Biz kimsenin varlığıyla var olmadık. Yokluluğuyla da yok olmayız.","Bana akıl verirken kalanı sana yetmeyecekse, benim için risk almanı istemem.","Dost dediğin kara günde belli olurmuş. Söndürün ışıkları, dostlarımı sayacağım!","Yanımda olması gerekenler zaten yanımda, defolup gidenler kimin umurunda?","Büyük bir hayal kırıklığı yaşayıp, ben artık kimseyi sevemem deme.","Unutma ki, en güzel çiçekler mezarlıklarda yetişir.",
"Yüz kere yere düşmüş olayım; başkalarına çelme takan biri olmayacağım. Ben kazanan değil, insan olmak istiyorum.","Hani ben kötüyüm ya senin gözünde! Hiç düşünüyor musun acaba; Sen kaç kuruşluk adamsın benim gözümde.","İnsanlar önce kendini, sonra haddini daha sonra da ne istediğini bilse hiç problem yaşanmayacak.","Yüzüme karşı melek olanlar, arkamdan kuyu kazarak çakallık yaptıklarını düşünüyorlar. Asla unutmasınlar, ben onların içindeki şeytanla boğuşuyorum.","Benim kimseyle uğraşacak vaktim yok. İnsansa notunu, hayvansa otunu verir geçerim.",
"Karakteri menfaatlerine göre şekillenen insanlar var. Allah bizi onlardan korusun.","Kimi insan girdiğinde odayı aydınlatır, kimide çıktığında…","Oturur sana şerefi anlatırdım ama, kaybettiği bir şeyi dinlemek ağır gelir insana.","Bugün laf koymıcam. Çay koydum; gel, iç, insanlık gör.","Biz kimsenin varlığıyla var olmadık. Yokluluğuyla da yok olmayız.","Bana akıl verirken kalanı sana yetmeyecekse, benim için risk almanı istemem.","Dost dediğin kara günde belli olurmuş. Söndürün ışıkları, dostlarımı sayacağım!",
"Yanımda olması gerekenler zaten yanımda, defolup gidenler kimin umurunda?","İki arada bir derede kalmadı hiç gönlüm, ya sevdim, ya sildim.","İyi insanlar daima kaybederler, çünkü adil dövüşürler","İnsan bazen büyük hayallerini küçük insanlarla ziyan eder.","Ben ağlarken yanımda yoksan ben gülerken gölge yapma.","Gitsen de artık beni bağlamaz; hani bir laf vardır ya, kendi düşen ağlamaz.","Erkek özlediğini söylemez! Oturur bir sigara daha yakar.","Karakterim ve tavrımı birbirine karıştırmayınız. Karakterim kim olduğumla ilgilidir, tavrımsa sizin kim olduğunuzla.",
"Kimi insan girdiğinde odayı aydınlatır, kimi de çıktığında.","Tamam hiçbir şey bildiğin yok ama bari arada bir de olsa haddini bilsen diyorum.","Biz popüler değiliz adamız, bizim durumlarımız değil adamlığımız beğenilir.","Hayatına giren herkese bir tanem diyorsan sen çokluk ile yokluk arasında ki farkı bilmiyorsun demektir.","Seni adam ederdim ama çoktan köpeğim olmuşsun, ne lüzumu var .","Ömrü bitene kadar sevmeli insan. Menfaatleri bitene kadar değil.","Serseriler ağlamaz ağlarsa kimse susturamaz sunu bil ki sosyete kızı herkes serseri olamaz.",
"Senin kaprislerini çekeceğime zikir çekerim en azından çektikçe sevap haneme işlerim.","Ayaklarımda pranga var diye yanımda şaklabanlık yapıyorsun ya istediğimde prangaları çıkarabileceğimi unutuyorsun.","Siz sokakların efendisi sandığınız semtlerin çocuklarısınız, bizler sizlere bağışladık o sokakları.","Sonunu düşünen kahraman olamaz","Bazı insanlar çamaşır suyu gibidir. İnsan yıpratmaktan başka bir işe yaramazlar.","Hiçbir zaman lüks bir yaşam istemedik. Yanımızda sevdiklerimiz olsun, Sokaklarda yaşamaya bile razıydık.",
"Boşuna kimseyi suçlamayın dostlarım. Kullanıcı hatası değil, bazılarının doğuştan defoludur yüreği.","Kara kalem resim yapmayı seviyorum. Çünkü kimin ne renk olduğunu hala çözemedim.","Senin açtığın yarayı bir başkasıyla kapatmasına kapatırım da,  yüreğime adilik yapmamın alemi yok.","Aldırma gidenlere, sevip terk edenlere. Hayat dediğin iki kelime; hoş geldin, güle güle.","Ben güçsüzüm düşerim ağlarım canım acır yaralarım ve kusurlarım var, sırf bu yüzden insanım. Sıradanım.","Sen bu kalp yükünü kaldıramadıysan ben el atarım.","Senin çivin çıkmış ama bilirsin ben çok iyi çakarım.",
"Ben kendi çapımda yazıyorum. Ucu sana dokunuyorsa, etrafımda dönüyorsun demektir boşa uğraşma. Bakmam sana.","Hayatı boyunca oyuncak ayıya sarılıp uyumuş bir kızı, büyüdüğünde sevgili seçimi yüzünden eleştiremezsin.","Demiş ki: ”kaybettiklerini görsün de ağlasın”. Dedim ki: ”kazandıklarımı görsen, değerinin olmadığını anlarsın.","Seni hiç unutmadım inanır mısın? Yediğim salatada bile arar oldum. Bir hıyarın eksikliği bu kadar mı belli olur.","Büyük balonların eceli, küçük iğnelerdir.",
"Gitmeyi tercih edenlerin ardından, el sallayın ki; artık sadece bir EL olduklarını daha iyi görsünler.","Ne yarım kaldım senden sonra, ne de yaralı, beni ne sen yıkabilirsin, ne de en kralı.","Kusura bakmayın, kusurlarınıza bakın!","Hani sen bana mecbursun havasında olanlar var ya. Onlar o havada takılsınlar; ben bana yeter de artarım, artanımla da onlara hava katarım.","Anladım ki; insanlar; susanı korkak, görmezden geleni aptal, affetmeyi bileni çantada keklik sanıyorlar. Oysaki ben istediğim kadar hayatlımdalar. Göz yumduğum kadar dürüstler ve sustuğum kadar insanlar.",
"Adam sorar kaçınız çıplaklığınıza güvenmek yerine karakterinize güvenecek kadar kadınsınız? Kadın cevap verir kaçınız çıplak bedene sahiplenmek yerine, üstünü örtecek kadar adamsınız?","Balonlar, içi boş şeylerin de bazen yükselebileceğini hatırlatır.","Gidişine illa bir isim konulacaksa, mal kaybı diyelim.","Canım, karakterin yere düşmüş. Onu bir alıver oradan.","Çakalların özgürlüğü Aslan yerden kalkana kadardır.","Zoruna gittiğini duydum. Güzel yer, ben de gitmiştim!","Sen hala kabullenmedin mi sevap sandığın günahlarını!","Seni unuttum sanma, sadece değerin kadar hatırlıyorum.",
"Bugün laf koymayacağım. Çay koydum; gel, iç, insanlık gör.","Eksik olmayın, dedik. Fazla olmaya başladınız. Hayırdır?","Ben insanları harcamayı iyi bilirim. Yeter ki bozuk olsun.","Ben “geri zekâlılıkla mücadele vakfı” mıyım, ya?","Kar yağınca mikroplar ölür diyorlar. İyi misin?","Adını şifrem yapsam, yetersiz karakter diyecek hala konuşuyor.","Hesabını veremeyeceğin işlere kalkışma! Öbür tarafta bulaşık yıkatmıyorlar.","Canım, bak! Bir derdin sıkıntın olursa, biliyorsun, hiç umurumda değil.",
"Her gece resmine bakmadan yatamıyorum, illa tüküreceğim.","Canımı sıktığın zaman sana tekme tokat dalıp, “Pardon! Dalmışım.” diyesim var.","Hani senin varlığın “fifi”, yokluğun da “tın” ya! Benim varlığım “olay”, yokluğum “koyar”..!","Egonu öyle beslemişsin ki karakterin aç kalmış.","Gölgene de yazıklar olsun! Seni adam sanmış ki peşinden gidiyor.","Kendi bindiğim gemiyi yakacak kadar deliyken, beni kibritle korkutmaya çalışma!","Sana benden nasihat: Başkasıyla gelen mutluluk, başkasıyla gidecektir .",
"Bir zamda şu insanlara gelse kendilerini bu kadar ucuza satmasalar.","Senin gibiler su ihtiyacını ancak tükürdüğünü yalayarak karşılıyor. Ne yaparsın işte…","Kara kalem resim yapmayı seviyorum. Çünkü kimin ne renk olduğunu hala çözemedim.","Eşeğe semer alınırken ne düşündüğü sorulmaz ölçüsü alınır. Ölçünü aldırtma bana!","Kendini beğenmiş insanları severim. Hiç kimsenin beğenmediği bir şeyi beğenmek, Ayrıcalık ’tır.","Tecrübeli satış elemanı arayanlara eski dostlarımın ismini veriyorum.","Biz karada yürüttüğümüz geminin kaptanıyız, siz hangi teknenin küreğisiniz.",
"İnsanlar önce kendini, sonra haddini daha sonra da ne istediğini bilse hiç problem yaşanmayacak.","Yüzüme karşı melek olanlar, arkamdan kuyu kazarak çakallık yaptıklarını düşünüyorlar. Asla unutmasınlar, ben onların içindeki şeytanla boğuşuyorum.","Biz saymayı fasulyeden öğrenmiş bir nesiliz. Kimleri fasulyeden sayacağımızı iyi biliriz.","Bu dünya senden önce de dönüyor, senden sonrada dönecek. Yani seninle bir şey değişmediği gibi, sensiz de bir şey değişmeyecek.","Attığınız ya da atacaklarınız kazıkları saklıyorum, saklıyorum ki gün gelip bana döndüğünüzde sizi ağırlayacak yerim olsun.",
"Bazı insanlar söze gelince edebiyatın turşusunu bile kuruyorlar da icraata gelince turşunun içindeki hıyar kadar olamıyorlar.","Einstein amca bak öyle atomu parçalamakla filan olmaz bu işler, sen gel de o’nun gidişinden sonra beni topla, toplayabilirsen.","Benden sana ne beddua gelir ne de dua bundan sonra, tek bir dileğim var sadece ne yaşattıysan bana, sende aynısını yaşa.","Ezan sesini seviyorum. Çalan müzik susuyor, küfür edilmiyor, içki içen bırakıyor. Yani 3 dakika herkes insan oluyor.","Senin gibi bozukları kumbarada biriktirir, geleceğe yatırım yaparım. Ha çok mu sıkıştım; hiç düşünmem hemen harcarım.",
"Büyük bir hayal kırıklığı yaşayıp, ben artık kimseyi sevemem deme. Unutma ki, en güzel çiçekler mezarlıklarda yetişir.","Seni gözümde bu kadar büyütmeme aptallık diyorsan, bu senin karakterinin küçüklüğü, benim hayal dünyamın büyüklüğüdür.","Demişsin ya onun gibilerini cebimden çıkarırım diye. Dinle. Ben senin gibilerini tespihime dizerim tövbe tövbe diye çekerim.","Biraz insan ol diyeceğim ama seni de zor durumda bırakmak istemiyorum.","Bir zam” da şu insanlara gelse kendilerini bu kadar ucuza” satmasalar…","Yanımda olması gerekenler zaten yanımda def olup gidenler kimin umurunda.",
"Ey sevgili nedir yüzündeki acı yoksa kırılan hayallerim mi battı eline?","Çok fazla konuşmaya gerek yok aslında. Sen, benden daha kötülerine layıksın.","Bana kalbimdesin deme sevgili, kalabalık yerlerde sıkıntı basıyor beni.","Akıllı telefonmuş. Karşı taraf aptal olunca, telefon akıllı olsa bile işe yaramıyor.","Erkek arkadaşının parası yok diye tokum” diyen de vardır, yokum” diyen de.","Benim bütünlemem yok sevgilim. Bir kere kaldın mı benden bir daha geçemezsin.","Sana değer verip aşkı bulacağıma x’e değer veririm y’yi bulurum daha iyi.",
"İyi günde yanımda durmaya değil, dar günde arkamda olacaksan gel. Hayal ettiklerini görmeye değil, içimde acıyı göreceksen gel.","İnsanı acıtan yarası değil, vefasız dostunun hakikatidir. Ağaçları deviren fırtına değil, toprağın yetersiz sadakatidir.","Kime kıymet versem hayatımı ‘kıyamete’ çevirmesini iyi biliyor.","Gidişine illa bir isim konulacaksa MAL KAYBI diyelim.","‎50 kuruşluk çikolatanın verdiği mutluluğu veremeyen insanlar var.","Bazı insanları hayata baktığı pencereden, atmalı.","Bazı insanlar ayakkabı mağazası gibi, her numara var Allah için.",
"Kendime yakışanı severim. Herkese yapışanı değil.","Seni adam ederdim ama çoktan köpeğim olmuşsun, ne luzmu var.","Şimdi söyle; hayatını düzene mi sokayım, seni üzene mi?","Varlığım parmağına ‘yüzük’ olmadı ya. Yokluğum kulağına ‘küpe’ olsun.","İki dakika insan ol desem zaman tutacak insanlar tanıyorum.","Sokak lambası gibi olma ey yar kime yandığın belli olsun.","İyileştirir diye medet umduklarımız tekrar tekrar yaralıyor bizi.","En güzel ironisidir dünyanın, seni üzmek istemiyorum diyen herkesin hayatımızın içine sıçması.","Kıyamam dediklerimiz bizi ince ince kıyıp pembeleşinceye kadar kısık ateşte kavurdular.",
"Yüz kere yere düşmüş olayım; başkalarına çelme takan biri olmayacağım. Ben kazanan değil, insan olmak istiyorum.","Bir kadının gözyaşının akmasına sadece soğan değil, bir ‘hıyar’ da neden olabilir.","Sen hayata at gözlükleriyle bakmaya devam edersen, birilerinin çüşşş demesi zoruna gitmesin.","Bilirsin ben belâ okuyamam, Allah salânı versin.","Bir zamanlar toz konduramadıklarım, şimdi kirden görünmez olmuş.","Her şeyi bilmene gerek yok haddini bil yeter.","İnsanlar da fotoğraf gibi; ne kadar büyütürsen, o kadar düşüyor kalitesi.",
)

guzelsoz = (
'ᴜsʟᴜᴘ ᴋᴀʀᴀᴋᴛᴇʀɪᴅɪʀ ʙɪʀ ɪɴsᴀɴɪɴ ...','ɪʏɪʏɪᴍ ᴅᴇsᴇᴍ ɪɴᴀɴᴀᴄᴀᴋ , ᴏ ᴋᴀᴅᴀʀ ʜᴀʙᴇʀsɪᴢ ʙᴇɴᴅᴇɴ ...','ᴍᴇsᴀғᴇʟᴇʀ ᴜᴍʀᴜᴍᴅᴀ ᴅᴇɢɪʟ , ɪᴄɪᴍᴅᴇ ᴇɴ ɢᴜᴢᴇʟ ʏᴇʀᴅᴇsɪɴ ...','ʙɪʀ ᴍᴜᴄɪᴢᴇʏᴇ ɪʜᴛɪʏᴀᴄɪᴍ ᴠᴀʀᴅɪ , ʜᴀʏᴀᴛ sᴇɴɪ ᴋᴀʀsɪᴍᴀ ᴄɪᴋᴀʀᴅɪ ...', 'ᴏʏʟᴇ ɢᴜᴢᴇʟ ʙᴀᴋᴛɪɴ ᴋɪ , ᴋᴀʟʙɪɴ ᴅᴇ ɢᴜʟᴜsᴜɴ ᴋᴀᴅᴀʀ ɢᴜᴢᴇʟ sᴀɴᴍɪsᴛɪᴍ ...','ʜᴀʏᴀᴛ ɴᴇ ɢɪᴅᴇɴɪ ɢᴇʀɪ ɢᴇᴛɪʀɪʀ , ɴᴇ ᴅᴇ ᴋᴀʏʙᴇᴛᴛɪɢɪɴ ᴢᴀᴍᴀɴɪ ɢᴇʀɪ ɢᴇᴛɪʀɪʀ ...','sᴇᴠᴍᴇᴋ ɪᴄɪɴ sᴇʙᴇᴘ ᴀʀᴀᴍᴀᴅɪᴍ , ʙɪʀ ᴛᴇᴋ sᴇsɪ ʏᴇᴛᴛɪ ᴋᴀʟʙɪᴍᴇ ...', 
'ᴍᴜᴛʟᴜʏᴜɴ ᴀᴍᴀ sᴀᴅᴇᴄᴇ sᴇɴɪɴʟᴇ ...','ʙᴇɴ ʜᴇᴘ sᴇᴠɪʟᴍᴇᴋ ɪsᴛᴇᴅɪɢɪᴍ ɢɪʙɪ sᴇᴠɪɴᴅɪᴍ ...', 'ʙɪʀɪ ᴠᴀʀ ɴᴇ ᴏᴢʟᴇᴍᴇᴋᴛᴇɴ ʏᴏʀᴜʟᴅᴜᴍ ɴᴇ sᴇᴠᴍᴇᴋᴛᴇɴ ...', 'ᴄᴏᴋ ᴢᴏʀ ʙᴇ sᴇɴɪ sᴇᴠᴍᴇʏᴇɴ ʙɪʀɪɴᴇ ᴀsɪᴋ ᴏʟᴍᴀᴋ ...','ɴᴇ ᴋᴀᴅᴀʀ ʏᴀŞᴀᴅɪĞɪᴍɪᴢ ᴅᴇĞɪʟ, ɴᴀꜱɪʟ ʏᴀŞᴀᴅɪĞɪᴍɪᴢ Öɴᴇᴍʟɪᴅɪʀ ...',
'ᴄᴏᴋ ᴏɴᴇᴍsɪᴢʟɪᴋ ɪsᴇ ʏᴀʀᴀᴍᴀᴅɪ ᴀʀᴛɪᴋ ʙᴏs ᴠᴇʀɪʏᴏʀᴜᴢ ...', 'ʜᴇʀᴋᴇsɪɴ ʙɪʀ ɢᴇᴄᴍɪsɪ ᴠᴀʀ , ʙɪʀ ᴅᴇ ᴠᴀᴢɢᴇᴄᴍɪsɪ ...', 'ᴀsɪᴋ ᴏʟᴍᴀᴋ ɢᴜᴢᴇʟ ʙɪʀ sᴇʏ ᴀᴍᴀ sᴀᴅᴇᴄᴇ sᴀɴᴀ ...', 'ᴀɴʟᴀʏᴀɴ ʏᴏᴋᴛᴜ , sᴜsᴍᴀʏɪ ᴛᴇʀᴄɪʜ ᴇᴛᴛɪᴍ ...', 'sᴇɴ ᴄᴏᴋ sᴇᴠ ᴅᴇ ʙɪʀᴀᴋɪᴘ ɢɪᴅᴇɴ ʏᴀʀ ᴜᴛᴀɴsɪɴ ...', 'ᴏ ɢɪᴛᴛɪᴋᴛᴇɴ sᴏɴʀᴀ ɢᴇᴄᴇᴍ ɢᴜɴᴅᴜᴢᴇ ʜᴀsʀᴇᴛ ᴋᴀʟᴅɪ ...','ɢᴜᴠᴇɴᴍᴇᴋ  sᴇᴠᴍᴇᴋᴛᴇɴ ᴅᴀʜᴀ ᴅᴇɢᴇʀʟɪ , ᴢᴀᴍᴀɴʟᴀ ᴀɴʟᴀʀsɪɴ ...', 
'ɪɴsᴀɴ ʙᴀᴢᴇɴ ʙᴜʏᴜᴋ ʜᴀʏᴀʟʟᴇʀɪɴɪ ᴋᴜᴄᴜᴋ ɪɴsᴀɴʟᴀʀʟᴀ ᴢɪʏᴀɴ ᴇᴅᴇʀ ...', 'ᴋɪᴍsᴇ ᴋɪᴍsᴇʏɪ ᴋᴀʏʙᴇᴛᴍᴇᴢ  ɢɪᴅᴇɴ ʙᴀsᴋᴀsɪɴɪ ʙᴜʟᴜʀ , ᴋᴀʟᴀɴ ᴋᴇɴᴅɪɴɪ ...', 'ɢᴜᴄʟᴜ ɢᴏʀᴜɴᴇʙɪʟɪʀɪᴍ ᴀᴍᴀ ɪɴᴀɴ ʙᴀɴᴀ ʏᴏʀɢᴜɴᴜᴍ ...', 'ᴏᴍʀᴜɴᴜᴢᴜ sᴜsᴛᴜᴋʟᴀʀɪɴɪᴢɪ ᴅᴜʏᴀɴ  ʙɪʀɪʏʟᴇ ɢᴇᴄɪʀɪɴ ...', 'ʜᴀʏᴀᴛ ɪʟᴇʀɪʏᴇ ʙᴀᴋɪʟᴀʀᴀᴋ ʏᴀsᴀɴɪʀ ɢᴇʀɪʏᴇ ʙᴀᴋᴀʀᴀᴋ ᴀɴʟᴀsɪʟɪʀ ...', 'ᴀʀᴛɪᴋ ʜɪᴄʙɪʀ sᴇʏ ᴇsᴋɪsɪ ɢɪʙɪ ᴅᴇɢɪʟ ʙᴜɴᴀ ʙᴇɴᴅᴇ ᴅᴀʜɪʟɪᴍ ...', 'ᴋɪʏᴍᴇᴛ ʙɪʟᴇɴᴇ ɢᴏɴᴜʟᴅᴇ ᴠᴇʀɪʟɪʀ ᴏᴍᴜʀᴅᴇ ...', 
'ʙɪʀ ᴄɪᴄᴇᴋʟᴇ ɢᴜʟᴇʀ ᴋᴀᴅɪɴ , ʙɪʀ ʟᴀғʟᴀ ʜᴜᴢᴜɴ ...', 'ᴋᴀʟʙɪ ɢᴜᴢᴇʟ ᴏʟᴀɴ ɪɴsᴀɴɪɴ ɢᴏᴢᴜɴᴅᴇɴ ʏᴀs ᴇᴋsɪᴋ ᴏʟᴍᴀᴢᴍɪs ...', 'ʜᴇʀ sᴇʏɪ ʙɪʟᴇɴ ᴅᴇɢɪʟ ᴋɪʏᴍᴇᴛ ʙɪʟᴇɴ ɪɴsᴀɴʟᴀʀ ᴏʟsᴜɴ ʜᴀʏᴀᴛɪɴɪᴢᴅᴀ ...', 'ᴍᴇsᴀғᴇ ɪʏɪᴅɪʀ ɴᴇ ʜᴀᴅᴅɪɴɪ ᴀsᴀɴ ᴏʟᴜʀ , ɴᴇ ᴅᴇ ᴄᴀɴɪɴɪ sɪᴋᴀɴ ...', 'ʏᴜʀᴇɢɪᴍɪɴ ᴛᴀᴍ ᴏʀᴛᴀsɪɴᴅᴀ ʙᴜʏᴜᴋ ʙɪʀ ʏᴏʀɢᴜɴʟᴜᴋ ᴠᴀʀ ...', 'ᴠᴇʀɪʟᴇɴ ᴅᴇɢᴇʀɪɴ ɴᴀɴᴋᴏʀᴜ ᴏʟᴍᴀʏɪɴ ɢᴇʀɪsɪ ʜᴀʟʟ ᴏʟᴜʀ ...', 
'ʜᴇᴍ ɢᴜᴄʟᴜ ᴏʟᴜᴘ ʜᴇᴍ ʜᴀssᴀs ᴋᴀʟᴘʟɪ ʙɪʀɪ ᴏʟᴍᴀᴋ ᴄᴏᴋ ᴢᴏʀ ...', 'ᴍᴜʜᴛᴀᴄ ᴋᴀʟɪɴ ʏᴜʀᴇɢɪ ɢᴜᴢᴇʟ  ɪɴsᴀɴʟᴀʀᴀ ...', 'ɪɴsᴀɴ ᴀɴʟᴀᴅɪɢɪ ᴠᴇ ᴀɴʟᴀsɪʟᴅɪɢɪ ɪɴsᴀɴᴅᴀ ᴄɪᴄᴇᴋ ᴀᴄᴀʀ ...', 'ɪsᴛᴇʏᴇɴ ᴅᴀɢʟᴀʀɪ ᴀsᴀʀ ɪsᴛᴇᴍᴇʏᴇɴ ᴛᴜᴍsᴇɢɪ ʙɪʟᴇ ɢᴇᴄᴇᴍᴇᴢ ...', 'ɪɴsᴀʟʟᴀʜ sᴀʙɪʀʟᴀ ʙᴇᴋʟᴇᴅɪɢɪɴ sᴇʏ ɪᴄɪɴ ʜᴀʏɪʀʟɪ ʙɪʀ ʜᴀʙᴇʀ ᴀʟɪʀsɪɴ ...', 'ɪʏɪ ᴏʟᴀɴ ᴋᴀʏʙᴇᴛsᴇ ᴅᴇ ᴋᴀᴢᴀɴɪʀ ...', 'ɢᴏɴʟᴜɴᴜᴢᴇ ᴀʟᴅɪɢɪɴɪᴢ , ɢᴏɴʟᴜɴᴜᴢᴜ ᴀʟᴍᴀʏɪ ʙɪʟsɪɴ ...', 
'ʏɪɴᴇ ʏɪʀᴛɪᴋ ᴄᴇʙɪᴍᴇ ᴋᴏʏᴍᴜsᴜᴍ ᴜᴍᴜᴅᴜᴍᴜ ...', 'ᴏʟᴍᴇᴋ ʙɪʀ sᴇʏ ᴅᴇɢɪʟ ʏᴀsᴀᴍᴀᴋ ᴋᴏʀᴋᴜɴᴄ ...', 'ɴᴇ ɪᴄɪᴍᴅᴇᴋɪ sᴏᴋᴀᴋʟᴀʀᴀ sɪɢᴀʙɪʟᴅɪᴍ ɴᴇ ᴅᴇ ᴅɪsᴀʀɪᴅᴀᴋɪ ᴅᴜɴʏᴀʏᴀ ...', 'ɪɴsᴀɴ sᴇᴠɪʟᴍᴇᴋᴛᴇɴ ᴄᴏᴋ ᴀɴʟᴀsɪʟᴍᴀʏɪ ɪsᴛɪʏᴏʀᴅᴜ ʙᴇʟᴋɪ ᴅᴇ ...', 'ᴇᴋᴍᴇᴋ ᴘᴀʜᴀʟɪ , ᴇᴍᴇᴋ ᴜᴄᴜᴢᴅᴜʀ ...', 'sᴀᴠᴀsᴍᴀʏɪ ʙɪʀᴀᴋɪʏᴏʀᴜᴍ ʙᴜɴᴜ ᴠᴇᴅᴀ sᴀʏ ...','ᴋÜÇÜᴋ ɪŞʟᴇʀᴇ ɢᴇʀᴇĞɪɴᴅᴇɴ Çᴏᴋ Öɴᴇᴍ ᴠᴇʀᴇɴʟᴇʀ, ᴇʟɪɴᴅᴇɴ ʙÜʏÜᴋ ɪŞ ɢᴇʟᴍᴇʏᴇɴʟᴇʀᴅɪʀ ...',
'ᴀŞᴋ ʙɪʀ ᴋᴀᴅɪɴɪɴ ʏᴀŞᴀᴍɪɴɪɴ ᴛÜᴍ ÖʏᴋÜꜱÜ, ᴇʀᴋᴇĞɪɴ ɪꜱᴇ ʏᴀʟɴɪᴢᴄᴀ ʙɪʀ ꜱᴇʀÜᴠᴇɴɪᴅɪʀ ...','ʜᴇʀŞᴇʏɪ ᴅᴇɴᴇʀɪᴍ; ᴀᴍᴀ ʏᴀᴘᴀʙɪʟᴅɪᴋʟᴇʀɪᴍɪ ʏᴀᴘᴀʀɪᴍ ...','ʏᴀɴʟɪŞ ʙɪʟᴅɪĞɪɴ ʏᴏʟᴅᴀ; ʜЕʀᴋЕꜱʟЕ ʏÜʀÜʏЕᴄЕĞɪɴЕ, ᴅᴏĞʀᴜ ʙɪʟᴅɪĞɪɴ ʏᴏʟᴅᴀ; ᴛЕᴋ ʙᴀŞɪɴᴀ ʏÜʀÜ ...','ᴏ ᴅᴀ ɢᴀᴢɪ ᴏʟᴍᴀᴋ ɪꜱᴛᴇᴅɪ, ꜰᴀᴋᴀᴛ ᴏɴᴀ ᴀɴʟᴀᴛᴍᴀᴋ ɢᴇʀᴇᴋᴛɪ ᴋɪ, Şᴇʜɪᴅ ᴏʟᴍᴀʏɪ ɢÖᴢᴇ ᴀʟᴀᴍᴀʏᴀɴ ɢᴀᴢɪ ᴏʟᴀᴍᴀᴢᴅɪ ...','ɴᴇ ᴋᴀᴅᴀʀ ʏÜᴋꜱᴇʟɪʀꜱᴇɴ, ᴜÇᴍᴀʏɪ ʙɪʟᴍᴇʏᴇɴʟᴇʀᴇ ᴏ ᴋᴀᴅᴀʀ ᴋÜÇÜᴋ ɢÖʀÜɴÜʀꜱÜɴ ...',
'ɴᴇ ᴋᴀᴅᴀʀ ʜᴀᴢɪɴ ʙɪʀ ÇᴀĞᴅᴀ ʏᴀŞɪʏᴏʀᴜᴢ, ʙɪʀ Öɴʏᴀʀɢɪʏɪ ᴏʀᴛᴀᴅᴀɴ ᴋᴀʟᴅɪʀᴍᴀᴋ ᴀᴛᴏᴍᴜ ᴘᴀʀÇᴀʟᴀᴍᴀᴋᴛᴀɴ ᴅᴀʜᴀ ɢÜÇ ...','ᴍᴜᴛʟᴜʟᴜᴋ ʜᴇʀ Şᴇʏᴅᴇɴ Öɴᴄᴇ ᴠÜᴄᴜᴛ ꜱᴀĞʟɪĞɪɴᴅᴀᴅɪʀ ...','ʙᴀᴢᴇɴ ʙɪʀ Şᴇʏᴇ ꜱᴏɴ ᴠᴇʀᴍᴇᴋ ɪÇɪɴ ɪꜱᴛᴇᴍᴇᴅɪĞɪɴ ʙɪʀ Şᴇʏ ʏᴀᴘᴍᴀɴ ɢᴇʀᴇᴋɪʀ ...','ᴋɪᴍ ᴋᴀᴢᴀɴᴍᴀᴢꜱᴀ ʙᴜ ᴅÜɴʏᴀᴅᴀ ʙɪʀ ᴇᴋᴍᴇᴋ ᴘᴀʀᴀꜱɪ ʏᴀ ᴅᴏꜱᴛᴜɴᴜɴ ʏÜᴢ ᴋᴀʀᴀꜱɪ ʏᴀ ᴅᴀ ᴅÜŞᴍᴀɴɪɴɪɴ ᴍᴀꜱᴋᴀʀᴀꜱɪ ...','ᴀᴠᴜᴄᴜ ᴋᴀᴅᴀʀ ʏÜʀᴇĞɪ ᴏʟᴍᴀʏᴀɴ ɪɴꜱᴀɴʟᴀʀɪ ᴋÜʀᴇᴋ ɢɪʙɪ ᴅɪʟɪ ᴠᴀʀ ...','ᴍᴜᴛʟᴜʟᴜᴋ ʜᴇʀ Şᴇʏᴅᴇɴ Öɴᴄᴇ ᴠÜᴄᴜᴛ ꜱᴀĞʟɪĞɪɴᴅᴀᴅɪʀ ...',
'ᴏᴋʏᴀɴᴜꜱᴛᴀ Öʟᴍᴇᴢ ᴅᴇ ɪɴꜱᴀɴ, ɢɪᴅᴇʀ ʙɪʀ ᴋᴀŞɪᴋ ꜱᴇᴠᴅᴀᴅᴀ ʙᴏĞᴜʟᴜʀ ...','ᴍᴜᴛʟᴜʟᴜᴋ ʜᴇʀ Şᴇʏᴅᴇɴ Öɴᴄᴇ ᴠÜᴄᴜᴛ ꜱᴀĞʟɪĞɪɴᴅᴀᴅɪʀ ...','ɴᴇʀᴇʏᴇ ɢɪᴛᴛɪĞɪɴɪ ʙɪʟᴍɪʏᴏʀꜱᴀɴ, ʜᴀɴɢɪ ʏᴏʟᴅᴀɴ ɢɪᴛᴛɪĞɪɴɪɴ ʜɪÇʙɪʀ Öɴᴇᴍɪ ʏᴏᴋᴛᴜʀ ...','ʙᴀᴢᴇɴ ɪʟᴋ ɢÖʀÜŞᴛᴇ ʙɪʟɪʀꜱɪɴ, ᴏ ɪɴꜱᴀɴ ꜱᴇɴɪɴ ᴋᴀᴅᴇʀɪɴᴅɪʀ. ʙᴀᴢᴇɴ ʙɪʀ ÖᴍÜʀ ᴀʀᴀʀꜱɪɴ, ʙᴜʟᴜɴᴍᴀᴢ ...','ʟᴀɴᴇᴛ ᴏʟꜱᴜɴ. ɴᴇ ᴍᴜᴀᴢᴢᴀᴍ Şᴇʏ ꜱᴇɴɪ ꜱᴇᴠᴍᴇᴋ ...','ʏᴀʀɪᴍ ɴᴇꜰᴇꜱʟɪᴋ ʙᴜ ʜᴀʏᴀᴛᴛᴀ. ꜱᴇᴠɢɪᴅᴇɴ ʙᴀŞᴋᴀ ʜɪÇʙɪʀ Şᴇʏ ᴘʟᴀɴʟᴀᴍᴀ ...',
'İʟɪᴍ ᴀŞᴀĞɪᴅᴀᴋɪʟᴇʀɪ ʏÜᴋꜱᴇʟᴛɪʀ, ᴄᴀʜɪʟʟɪᴋ ɪꜱᴇ ʏÜᴋꜱᴇᴋᴛᴇᴋɪʟᴇʀɪ ᴀʟÇᴀʟᴛɪʀ ...','ᴋɪᴍ ɪʟɪᴍ ᴀʀᴀᴍᴀ ʏᴏʟᴜɴᴅᴀ ᴏʟᴜʀꜱᴀ, ᴄᴇɴɴᴇᴛ ᴅᴇ ᴏɴᴜ ᴀʀᴀᴍᴀ ʏᴏʟᴜɴᴅᴀ ᴏʟᴜʀ ...','ʏᴀɴɪʟᴛᴍᴀꜱɪɴ ꜱᴇɴɪ ᴍᴀꜱᴜᴍ ʙᴀᴋɪŞʟᴀʀ, ʙᴀᴢɪʟᴀʀɪɴɪ Şᴇʏᴛᴀɴ ᴀʏᴀᴋᴛᴀ ᴀʟᴋɪŞʟᴀʀ ...','İɴꜱᴀɴʟᴀʀɪ ᴛᴀɴɪŞɪʀᴋᴇɴ ᴅᴇĞɪʟ, ᴛᴀʀᴛɪŞɪʀᴋᴇɴ ᴛᴀɴɪʀꜱɪɴ. ÇÜɴᴋÜ Öꜰᴋᴇ, ꜱᴀʟʟᴀɴᴀɴ ᴋɪŞɪʟɪĞɪ ᴏʀᴛᴀʏᴀ Çɪᴋᴀʀɪʀ ...','ɢᴇʀÇᴇᴋ ᴀŞᴋ ɪÇɪɴ ᴀꜱʟᴀ ʙɪʀ ᴢᴀᴍᴀɴ ʏᴀ ᴅᴀ ʏᴇʀ ʏᴏᴋᴛᴜʀ ...','ᴇĞᴇʀ ᴅᴏĞʀᴜʏᴜ ꜱÖʏʟᴇʀꜱᴇɴ ʜɪÇʙɪʀ Şᴇʏɪ ʜᴀᴛɪʀʟᴀᴍᴀᴋ ᴢᴏʀᴜɴᴅᴀ ᴅᴇĞɪʟꜱɪɴ ...',
'ʜᴇʀ ᴇʟɪɴɪ ꜱɪᴋᴀɴʟᴀ ᴅᴏꜱᴛ, ʜᴇʀ ᴄᴀɴɪɴɪ ꜱɪᴋᴀɴʟᴀ ᴅÜŞᴍᴀɴ ᴏʟᴍᴀ ...','ᴇᴅᴇᴘ ᴀᴋʟɪɴ ᴛᴇʀᴄÜᴍᴀɴɪᴅɪʀ. ʜᴇʀᴋᴇꜱ ᴇᴅᴇʙɪ ᴋᴀᴅᴀʀ ᴀᴋɪʟʟɪ, ᴀᴋʟɪ ᴋᴀᴅᴀʀ Şᴇʀᴇꜰʟɪ, Şᴇʀᴇꜰɪ ᴋᴀᴅᴀʀ ᴅᴇĞᴇʀʟɪᴅɪʀ ...','ʏᴀŞɪɴ ᴅᴇĞɪʟ ʏᴀŞᴀᴅɪᴋʟᴀʀɪɴ ÖĞʀᴇᴛɪʀ ꜱᴀɴᴀ ʜᴀʏᴀᴛɪ ...','Şᴜɴᴜ ᴀꜱʟᴀ ᴜɴᴜᴛᴍᴀ; ɢÜʟᴇʀᴋᴇɴ ᴋᴀʏʙᴇᴛᴛɪᴋʟᴇʀɪɴɪ, ᴀĞʟᴀʏᴀʀᴀᴋ ᴋᴀᴢᴀɴᴀᴍᴀᴢꜱɪɴ ...','ꜰᴀᴢʟᴀ ʙÜʏÜᴛᴍᴇ ᴋᴇɴᴅɪɴɪ, ᴇɴ ꜰᴀᴢʟᴀ ꜱᴇᴠᴇʙɪʟᴅɪĞɪᴍ ᴋᴀᴅᴀʀꜱɪɴ; ᴅᴀʜᴀꜱɪ ʏᴏᴋ ...','ᴀŞᴋ Çᴏᴋ ᴋɪꜱᴀ ᴀᴍᴀ ᴜɴᴜᴛᴍᴀꜱɪ Çᴏᴋ ᴢᴏʀ ...',
'İʏɪʏɪ ᴀʀᴀ, ᴅᴏĞʀᴜʏᴜ ᴀʀᴀ, ɢÜᴢᴇʟɪ ᴀʀᴀ ꜰᴀᴋᴀᴛ ᴋᴜꜱᴜʀᴜ ᴀʀᴀᴍᴀ ...','ʜᴀʏᴀᴛɪ ɢÖᴢʏᴀŞʟᴀʀɪɴʟᴀ ÖᴅÜʟʟᴇɴᴅɪʀᴇᴄᴇĞɪɴᴇ; ɢÜʟÜᴄÜᴋʟᴇʀɪɴʟᴇ ᴄᴇᴢᴀʟᴀɴᴅɪʀ ...','ᴜᴢᴀᴋᴋᴇɴ ʙɪʟᴇ ʙɪʀ ɴᴇꜰᴇꜱ ᴋᴀᴅᴀʀ ʏᴀᴋɪɴɪᴍᴅᴀꜱɪɴ ...','ʜᴇʀ ᴍÜɴᴀᴋᴀŞᴀɴɪɴ ᴛᴇᴍᴇʟɪɴᴅᴇ ʙɪʀɪꜱɪɴɪɴ ᴄᴀʜɪʟʟɪĞɪ ʏᴀᴛᴀʀ ...','ʙɪʟɢᴇʟɪᴋ ᴋᴀʟᴘᴛᴇɴ ɢᴇʟɪʀ. ᴀᴋɪʟʟᴀ ɪʟɢɪꜱɪ ʏᴏᴋᴛᴜʀ. ʙɪʟɢᴇʟɪᴋ, ᴠᴀʀʟɪĞɪɴɪɴ ᴇɴ ᴅᴇʀɪɴ ɴᴏᴋᴛᴀꜱɪɴᴅᴀɴ Çɪᴋᴀʀ. ᴋᴀꜰᴀʏᴀ ᴀɪᴛ ᴅᴇĞɪʟᴅɪʀ ...',
'ʏᴀŞᴀᴅɪĞɪɴ ʏᴇʀɪ ᴄᴇɴɴᴇᴛ ʏᴀᴘᴀᴍᴀᴅɪĞɪɴ ꜱÜʀᴇᴄᴇ ᴋᴀÇᴛɪĞɪɴ ʜᴇʀ ʏᴇʀ ᴄᴇʜᴇɴɴᴇᴍᴅɪʀ ...','ᴋɪʀɪʟᴍɪŞ ʙɪʀɪ Çᴏᴋ ɢÜᴢᴇʟ ꜱᴜꜱᴀʀ. ʜᴇʀ Şᴇʏɪɴᴇ ʜᴀꜱʀᴇᴛ ᴋᴀʟɪʀꜱɪɴ ...','İɴᴀɴÇ, ᴘᴀʀÇᴀʟᴀɴᴍɪŞ ʙɪʀ ᴅÜɴʏᴀɴɪɴ ɪŞɪĞᴀ ÇɪᴋᴀᴄᴀĞɪ ɢÜÇᴛÜʀ ...','ʙᴇʟᴋɪ ᴅᴇ ɪɴꜱᴀɴ ʜᴇʀ Şᴇʏɪ ɪÇɪɴᴇ ᴀᴛᴍᴀᴋᴛᴀɴ ʙᴏĞᴜʟᴜʏᴏʀ ᴢᴀᴍᴀɴʟᴀ ...','ᴀŞᴋ ʙɪʀ ᴋᴀᴅɪɴɪɴ ʏᴀŞᴀᴍɪɴɪɴ ᴛÜᴍ ÖʏᴋÜꜱÜ, ᴇʀᴋᴇĞɪɴ ɪꜱᴇ ʏᴀʟɴɪᴢᴄᴀ ʙɪʀ ꜱᴇʀÜᴠᴇɴɪᴅɪʀ ...','ᴀŞᴋ ʀÜᴢɢᴀʀ ɢɪʙɪᴅɪʀ, ɢÖʀᴇᴍᴇᴢꜱɪɴ ᴀᴍᴀ ʜɪꜱꜱᴇᴅᴇʙɪʟɪʀꜱɪɴ ...',
'ᴅᴇĞɪŞɪᴍ ᴇʙᴇᴅɪ, ÖʟÜᴍꜱÜᴢʟÜᴋ ᴋᴀʟɪᴄɪᴅɪʀ ...','ᴋÖʀʟᴇʀɪɴ Üʟᴋᴇꜱɪɴᴅᴇ, ᴛᴇᴋ ɢÖᴢʟÜ ɪɴꜱᴀɴ ᴋʀᴀʟ ᴏʟᴜʀ ...''ᴏʏꜱᴀ ʏÜʀᴇĞɪ ᴛᴇᴍɪᴢ ᴏʟᴍᴀʏᴀɴɪɴ, ᴀɴʟᴀʏɪŞɪ ᴅᴀ ᴋɪᴛᴛɪʀ ...','ʜɪÇ ʙᴜ ᴋᴀᴅᴀʀ ꜱᴜꜱᴍᴀᴋ ɪꜱᴛᴇᴍᴇᴍɪŞᴛɪᴍ ...','ŞÜᴋʀᴇᴛᴍᴇʏɪ ÖĞʀᴇɴᴍᴇʏᴇɴ ɴᴀɴᴋÖʀ ᴇʟʙᴇᴛᴛᴇ ŞɪᴋÂʏᴇᴛ ᴇᴅᴇʀ ...','Öʏʟᴇ ʙɪʀ ɢᴇʟ ᴅᴇᴍᴇʟɪꜱɪɴ ᴋɪ, ᴍᴇꜱᴀꜰᴇʟᴇʀ ᴀɴʟᴀᴍɪɴɪ ʏɪᴛɪʀᴍᴇʟɪ ...',
'ꜱᴀʙɪʀ ᴠᴀᴢɢᴇÇᴍᴇᴋ ᴅᴇĞɪʟ, ᴜᴍᴜᴅᴜ ʏᴀʀɪɴᴀ ᴇʀᴛᴇʟᴇᴍᴇᴋᴛɪʀ ...','ꜱᴇᴠᴅɪᴋʟᴇʀɪɴɪᴢᴇ ᴢᴀᴍᴀɴ ᴀʏɪʀɪɴ ʏᴏᴋꜱᴀ ᴢᴀᴍᴀɴ ꜱɪᴢɪ ꜱᴇᴠᴅɪᴋʟᴇʀɪɴɪᴢᴅᴇɴ ᴀʏɪʀɪʀ ...','ʙᴀŞᴋᴀꜱɪɴɪɴ ÖɴÜɴÜ ᴀʏᴅɪɴʟᴀᴛɪʀᴋᴇɴ ᴋᴇɴᴅɪ ʏᴏʟᴜᴍᴜᴢᴀ ᴅᴀ ɪŞɪᴋ ᴛᴜᴛᴀʀɪᴢ ...','ʜᴇʀᴋᴇꜱ ᴀʏɴɪ Şᴇʏɪ ᴅÜŞÜɴÜʏᴏʀꜱᴀ, ʜɪÇ ᴋɪᴍꜱᴇ ꜰᴀᴢʟᴀ ʙɪʀ Şᴇʏ ᴅÜŞÜɴᴍÜʏᴏʀ ᴅᴇᴍᴇᴋᴛɪʀ ...','İÇɪɴᴇ ᴀᴛᴛɪᴋʟᴀʀɪɴ ᴋᴇᴅᴇʀɪɴᴅɪʀ. İÇɪɴᴅᴇɴ ᴀᴛᴀᴍᴀᴅɪᴋʟᴀʀɪɴ ᴋᴀᴅᴇʀɪɴ ...',
'ᴍᴜᴛʟᴜ ᴍᴜ ᴏʟᴍᴀᴋ ɪꜱᴛɪʏᴏʀꜱᴜɴ , ᴋɪᴍꜱᴇᴅᴇɴ ʙɪʀ Şᴇʏ ʙᴇᴋʟᴇᴍᴇ ...','ɢÜᴢᴇʟɪ ɢÜᴢᴇʟ ʏᴀᴘᴀɴ ᴇᴅᴇᴘᴛɪʀ, ᴇᴅᴇᴘ ɪꜱᴇ ɢÜᴢᴇʟɪ ꜱᴇᴠᴍᴇʏᴇ ꜱᴇʙᴇᴘᴛɪʀ ...','ʏᴏʀᴍᴀ ᴋᴇɴᴅɪɴɪ... ʙɪʀᴀᴋ ʜᴀʏᴀᴛɪɴᴀ ᴇŞʟɪᴋ ᴇᴛᴍᴇᴋ ɪꜱᴛᴇʏᴇɴʟᴇʀ ꜱᴇɴɪɴʟᴇ ɢᴇʟꜱɪɴ ...','ʙɪʀÇᴏᴋ ɪɴꜱᴀɴ ᴍᴜᴛʟᴜʟᴜĞᴜ, ʙᴜʀɴᴜɴᴜɴ ÜꜱᴛÜɴᴅᴇ ᴜɴᴜᴛᴛᴜĞᴜ ɢÖᴢʟÜᴋ ɢɪʙɪ ᴇᴛʀᴀꜰᴛᴀ ᴀʀᴀʀ ...','ᴅÜʀÜꜱᴛ ᴏʟᴍᴀᴋᴛᴀɴ ᴋᴏʀᴋᴍᴀ, ᴋᴀʏʙᴇᴅᴇᴄᴇĞɪɴ ᴇɴ ꜰᴀᴢʟᴀ ʏᴀɴʟɪŞ ɪɴꜱᴀɴʟᴀʀ ᴏʟᴜʀ ...',
)

sor = (
'ᴋᴜʀᴛ ᴍᴜ ᴋᴇʟɪᴍᴇ ᴏʏᴜɴᴜ ᴍᴜ ?','Gʀᴜᴘᴛᴀ ɴᴇʏɪ ᴅᴇɢ̆ɪşᴛɪʀᴍᴇᴋ ɪsᴛᴇʀᴅɪɴ?','ɢʀᴜᴘᴛᴀ ᴋɪᴍʟᴇ ᴄ̧ᴀʏ ɪᴄ̧ᴍᴇᴋ ɪsᴛᴇʀᴅɪɴ ?','ʙᴜ̈ʏᴜ̈ʏᴇɴ ʜᴀʏᴀʟɪ ʙɪʀ ᴀʀᴋᴀᴅᴀşıɴıᴢ ᴠᴀʀ ᴍıʏᴅı?','ʙɪʀ ɢᴜ̈ɴ ᴋᴀʀşı ᴄɪɴs ᴏʟᴀʀᴀᴋ ᴜʏᴀɴıʀsᴀɴ, ɪʟᴋ ʏᴀᴘᴀᴄᴀɢ̆ıɴ şᴇʏ ɴᴇᴅɪʀ?','ɢʀᴜʙᴜɴ ᴏʟᴍᴀᴢsᴀ ᴏʟᴍᴀᴢı sᴇɴᴄᴇ ᴋɪᴍ ᴇᴛɪᴋᴇᴛʟᴇʀ ᴍɪsɪɴ?','ʜᴀʏᴀᴛᴛᴀ ᴜɴᴜᴛᴍᴀᴅıɢ̆ıɴ ʙɪʀɪ ᴠᴀʀ ᴍı?','ᴋᴜ̈ʟᴛᴜ̈ʀᴜ̈ᴍᴜ̈ᴢᴜ̈ɴ ᴇɴ ᴄ̧ᴏᴋ sᴇᴠᴅɪɢ̆ɪɴɪᴢ ʏᴀɴı ɴᴇᴅɪʀ?','ɢʀᴜʙᴜ sᴇᴠɪʏᴏʀ ᴍᴜsᴜɴ ?','ʜᴀʏᴀᴛᴛᴀ ᴜɴᴜᴛᴍᴀᴅıɢ̆ıɴ ʙɪʀɪ ᴠᴀʀ ᴍı?','ʜɪᴄ̧ʙɪʀ sᴏɴᴜᴄᴜ ᴏʟᴍᴀʏᴀᴄᴀɢ̆ıɴı ʙɪʟsᴇɴ ɴᴇ ʏᴀᴘᴍᴀᴋ ɪsᴛᴇʀᴅɪɴ?','ɪʟᴇʀᴅᴇ ᴄ̧ᴏᴄᴜɢ̆ᴜɴ ᴏʟᴜʀsᴀ ɴᴇ ɪsɪᴍ ᴋᴏʏᴍᴀᴋ ɪsᴛᴇʀsɪɴ?',
'şɪᴍᴅɪʏᴇ ᴋᴀᴅᴀʀ ʜɪᴄ̧ ᴀʀᴀʟıᴋsıᴢ 𝟷𝟸 sᴀᴀᴛᴛᴇɴ ғᴀᴢʟᴀ ᴜʏᴜᴅᴜɢ̆ᴜɴ ᴏʟᴅᴜ ᴍᴜ?','ɢʀᴜᴘᴛᴀ ᴋɪ ᴜ̈ᴄ̧ ᴋᴀɴᴋᴀɴı ᴇᴛɪᴋᴇᴛʟᴇʀ ᴍɪsɪɴ?','sıɴıғᴛᴀ ʜɪᴄ̧ ᴜʏᴜʏᴀ ᴋᴀʟᴅıɴ ᴍı?','ɢʀᴜʙᴜɴ ᴇɴ ᴅᴇʀᴛʟɪsɪ ᴋɪᴍ ?','ʀᴇᴀʟ ʜᴀʏᴀᴛᴛᴀ ᴛᴀɴıᴍᴀᴋ ɪsᴛᴇᴅɪɢ̆ɪɴ ᴋɪᴍsᴇ ᴠᴀʀ ᴍı ɢʀᴜᴘᴛᴀ ?','ʙɪʀɪɴɪɴ ᴛᴇʟᴇғᴏɴᴜɴᴅᴀ ɢᴏ̈ʀᴅᴜ̈ɢ̆ᴜ̈ɴ ᴇɴ ᴛᴜʜᴀғ şᴇʏ ɴᴇᴅɪʀ?','ʙɪʀ ʙᴏ̈ᴄᴇᴋ ɪsᴛɪʟᴀsı ɢᴇʀᴄ̧ᴇᴋʟᴇşsᴇ ʜᴀɴɢɪ ᴀʀᴋᴀᴅᴀşıɴ ʜᴀʏᴀᴛᴛᴀ ᴋᴀʟᴍᴀʏı ʙᴀşᴀʀıʀ?','ᴅᴜ̈ɴʏᴀᴅᴀᴋɪ ʜᴇʀʜᴀɴɢɪ ʙɪʀɪɴɪ ᴛᴜ̈ʀᴋɪʏᴇ’ɴɪɴ ʙᴀşᴋᴀɴı ʏᴀᴘᴀʙɪʟsᴇʏᴅɪɴ ʙᴜ ᴋɪᴍ ᴏʟᴜʀᴅᴜ?','ᴋᴜʀᴛ ᴏʏᴜɴᴜɴᴜ sᴇᴠɪʏᴏʀ ᴍᴜsᴜɴ?','ɢʀᴜᴘᴛᴀ ᴅᴇɢ̆ɪşᴍᴇsɪ ɢᴇʀᴇᴋᴇɴ şᴇʏ ᴠᴀʀ ᴍı?','ʜɪᴄ̧ʙɪʀ sᴏɴᴜᴄᴜ ᴏʟᴍᴀʏᴀᴄᴀɢ̆ıɴı ʙɪʟsᴇɴ ɴᴇ ʏᴀᴘᴍᴀᴋ ɪsᴛᴇʀᴅɪɴ?',
'ʙɪʀ ᴀʏɴᴀɴıɴ ᴏ̈ɴᴜ̈ɴᴅᴇ ʏᴀᴘᴛıɢ̆ıɴ ᴇɴ ᴄ̧ıʟɢıɴᴄᴀ şᴇʏ ɴᴇᴅɪʀ?','ᴄ̧ıᴋᴍᴀᴋ ɪsᴛᴇʏᴇᴄᴇɢ̆ɪɴ ᴇɴ ɢᴇɴᴄ̧ ᴋɪşɪ ᴋᴀᴄ̧ ʏᴀşıɴᴅᴀ ᴏʟᴜʀᴅᴜ?','ᴋɪʟᴏ ᴀʟᴅıʀıᴘ ᴀʟᴅıʀᴍᴀᴍᴀsı ᴏ̈ɴᴇᴍʟɪ ᴅᴇɢ̆ɪʟ, ʙɪʀ ᴏᴛᴜʀᴜşᴛᴀ ʜᴇᴘsɪɴɪ ʏᴇʀɪᴍ ᴅᴇᴅɪɢ̆ɪɴ ʏᴇᴍᴇᴋ ɴᴇᴅɪʀ?','ɢʀᴜᴘᴛᴀ ʜᴀɴɢɪ ᴏʏᴜɴᴜ sᴇᴠɪʏᴏʀsᴜɴ ?','ᴜʏᴋᴜɴᴅᴀ ᴋᴏɴᴜşᴜʀ ᴍᴜsᴜɴ?','ᴇɴ ᴋᴏ̈ᴛᴜ̈ ɢʀᴜᴘ ʜᴀɴɢɪsɪᴅɪʀ?','ɪ̇ɴsᴀɴʟᴀʀı ʏᴀɴᴀɴ ʙɪʀ ʙɪɴᴀᴅᴀɴ ᴋᴜʀᴛᴀʀıʏᴏʀ ᴏʟsᴀʏᴅıɴıᴢ ᴠᴇ ʙɪʀ ᴋɪşɪʏɪ ʙᴜ ɢʀᴜᴘᴅᴀɴ ɢᴇʀɪᴅᴇ ʙıʀᴀᴋᴍᴀᴋ ᴢᴏʀᴜɴᴅᴀ ᴋᴀʟıʀsᴀɴıᴢ, ᴋɪᴍ ᴏʟᴜʀᴅᴜ?','ʜᴀʟᴀ ʏᴀᴘᴛıɢ̆ıɴ ᴇɴ ᴄ̧ᴏᴄᴜᴋᴄ̧ᴀ şᴇʏ ɴᴇᴅɪʀ?','ᴠᴜ̈ᴄᴜᴅᴜɴᴜɴ ʜᴀɴɢɪ ʙᴏ̈ʟᴜ̈ᴍᴜ̈ɴᴜ̈ sᴇᴠɪʏᴏʀsᴜɴ, ʜᴀɴɢɪ ᴋısᴍıɴᴅᴀɴ ɴᴇғʀᴇᴛ ᴇᴅɪʏᴏʀsᴜɴ?','sıɴıғᴛᴀ ᴀsʟᴀ ʏᴀɴıɴᴅᴀ ᴏᴛᴜʀᴍᴀᴋ ɪsᴛᴇᴍᴇʏᴇᴄᴇɢ̆ɪɴ ᴋɪᴍ?','ᴋᴀᴄ̧ sᴇᴠɢɪʟɪɴ ᴏʟᴅᴜ?',
'ʜɪᴄ̧ʙɪʀ sᴏɴᴜᴄᴜ ᴏʟᴍᴀʏᴀᴄᴀɢ̆ıɴı ʙɪʟsᴇɴ ɴᴇ ʏᴀᴘᴍᴀᴋ ɪsᴛᴇʀᴅɪɴ?','ᴇɴ ᴋᴏ̈ᴛᴜ̈ ɢʀᴜᴘ ʜᴀɴɢɪsɪᴅɪʀ?','ɢʀᴜᴘᴛᴀ ʜᴏşʟᴀɴᴅıɢ̆ıɴ ʙɪʀɪ ᴠᴀʀ ᴍı ?','ᴄ̧ᴇşɪᴛʟɪ ʙᴀᴛıʟ ɪɴᴀɴᴄ̧ʟᴀʀıɴ ᴠᴀʀ ᴍı, ᴠᴀʀsᴀ ᴏɴʟᴀʀ ɴᴇʟᴇʀ?','ᴇɴ sᴏɴ ɴᴇ ᴢᴀᴍᴀɴ ʜᴜ̈ɴɢᴜ̈ʀ ʜᴜ̈ɴɢᴜ̈ʀ ᴀɢ̆ʟᴀᴅıɢ̆ıɴı ʜᴀᴛıʀʟıʏᴏʀ ᴍᴜsᴜɴ?','ᴏᴛᴏʙᴜ̈sᴛᴇ ʏᴀᴘᴛıɢ̆ıɴ ᴇɴ ᴛᴜʜᴀғ şᴇʏ ɴᴇᴅɪʀ?','ᴇɴ sᴏɴ sᴏ̈ʏʟᴇᴅɪɢ̆ɪɴ ʏᴀʟᴀɴ ɴᴇᴅɪʀ?','ʙᴜ ɢʀᴜᴘᴅᴀɴ ʙɪʀɪʏʟᴇ ᴇᴠʟᴇɴᴍᴇᴋ ᴢᴏʀᴜɴᴅᴀ ᴋᴀʟsᴀɴ ᴋɪᴍ ᴏʟᴜʀᴅᴜ?','ʜɪᴄ̧ ʏᴀşıɴ ʜᴀᴋᴋıɴᴅᴀ ʏᴀʟᴀɴ sᴏ̈ʏʟᴇᴅɪɴ ᴍɪ?','şɪşᴇᴅᴇɴ ʙɪʀ ᴄɪɴ ᴄ̧ıᴋsᴀ ᴜ̈ᴄ̧ ᴅɪʟᴇɢ̆ɪɴ ɴᴇ ᴏʟᴜʀᴅᴜ?','ʙᴜ̈ʏᴜ̈ʀᴋᴇɴ ʜɪᴄ̧ ʜᴀʏᴀʟɪ ᴀʀᴋᴀᴅᴀşıɴ ᴏʟᴅᴜ ᴍᴜ?','ᴠᴜ̈ᴄᴜᴅᴜɴᴜɴ ʜᴀɴɢɪ ʙᴏ̈ʟᴜ̈ᴍʟᴇʀɪɴᴅᴇɴ ɢıᴅıᴋʟᴀɴıʏᴏʀsᴜɴ?',
'ʜᴀʏᴀʟɪɴᴅᴇᴋɪ ɪş ɴᴇ?','ʙᴜ ɢʀᴜᴘᴛᴀᴋɪ ɪɴsᴀɴʟᴀʀᴅᴀɴ ᴋɪᴍɪɴʟᴇ ʜᴀʏᴀᴛıɴı ᴅᴇɢ̆ɪşᴛɪʀᴍᴇᴋ ɪsᴛᴇʀᴅɪɴ?','ʙᴜ ɢʀᴜᴘᴛᴀᴋɪ ɪɴsᴀɴʟᴀʀᴅᴀɴ ᴋɪᴍɪɴʟᴇ ʜᴀʏᴀᴛıɴı ᴅᴇɢ̆ɪşᴛɪʀᴍᴇᴋ ɪsᴛᴇʀᴅɪɴ?','ᴇɴ ᴛᴜʜᴀғ ᴛᴀᴋᴍᴀ ᴀᴅıɴ ɴᴇᴅɪʀ?','ɢᴜ̈ɴᴅᴇ ᴋᴀᴄ̧ ᴛᴀɴᴇ ᴏ̈ᴢᴄ̧ᴇᴋɪᴍ ʏᴀᴘᴀʀsıɴ?','ᴋɪᴍsᴇɴɪɴ ʙɪʟᴍᴇʏᴇᴄᴇɢ̆ɪ ɢᴀʀᴀɴᴛɪ ᴏʟsᴀ ᴋɪᴍɪ ᴏ̈ʟᴅᴜ̈ʀᴍᴇᴋ ɪsᴛᴇʀᴅɪɴ?','ᴛᴇʟᴇғᴏɴᴜɴᴜᴢᴅᴀ ᴀʀᴀᴅıɢ̆ıɴ sᴏɴ şᴇʏ ɴᴇʏᴅɪ?','ɪ̇ɴsᴀɴʟᴀʀıɴ sɪᴢᴇ ɴᴇ sᴏʀᴍᴀsıɴᴅᴀɴ ʙıᴋᴛıɴıᴢ?','ʙᴇʏɴɪɴɪ ʙɪʀ ʀᴏʙᴏᴛᴀ ʏᴇʀʟᴇşᴛɪʀᴇʙɪʟɪʀ ᴠᴇ sᴏɴsᴜᴢᴀ ᴋᴀᴅᴀʀ ʙᴜ şᴇᴋɪʟᴅᴇ ʏᴀşᴀʏᴀʙɪʟsᴇᴅɪɴ,ʙᴜɴᴜ ʏᴀᴘᴀʀ ᴍıʏᴅıɴ?','ɢᴜ̈ɴᴅᴇ ᴋᴀᴄ̧ ᴛᴀɴᴇ ᴏ̈ᴢᴄ̧ᴇᴋɪᴍ ʏᴀᴘᴀʀsıɴ?','ɢɪᴢʟɪ ᴀşᴋıɴ ᴋɪᴍ?','ᴋᴀᴅıɴ/ᴇʀᴋᴇᴋ ᴏʟᴍᴀɴıɴ ᴇɴ ᴋᴏ̈ᴛᴜ̈ ᴠᴇ ᴇɴ ɪʏɪ ʏᴀɴı ɴᴇᴅɪʀ?','ɢʀᴜʙᴜɴ ᴇɴ ᴅᴇʀᴛʟɪsɪ ᴋɪᴍ ?',
'ғɪᴢɪᴋsᴇʟ ᴏʟᴀʀᴋ sᴀɴᴀ ᴇɴ ᴀᴄı ᴠᴇʀᴇɴ ᴅᴇɴᴇʏɪᴍɪɴ ɴᴇ ᴏʟᴅᴜ?','ɢʀᴜᴘᴛᴀ ɢɪᴢʟɪ sᴇᴠᴅɪɢ̆ɪɴ ᴋɪᴍsᴇ ᴠᴀʀ ᴍı?','ɪʟᴇʀᴅᴇ ᴄ̧ᴏᴄᴜɢ̆ᴜɴ ᴏʟᴜʀsᴀ ɴᴇ ɪsɪᴍ ᴋᴏʏᴍᴀᴋ ɪsᴛᴇʀsɪɴ?','ʜᴀʏᴀᴛıɴʟᴀ ɪʟɢɪʟɪ ᴛᴇʟᴇɢʀᴀᴍᴅᴀ ɴᴇ ʏᴀʟᴀɴ sᴏ̈ʏʟᴇᴅɪɴ ?','ʙɪʀɪɴɪ ᴏ̈ᴘᴇʀᴋᴇɴ ᴋᴇɴᴅɪɴɪ ʜɪᴄ̧ ᴋᴏ̈ᴛᴜ̈ ʜɪssᴇᴛᴛɪɴ ᴍɪ?','ʙɪʀɪsɪ ᴋıᴢ ᴀʀᴋᴀᴅᴀşıɴ / ᴇʀᴋᴇᴋ ᴀʀᴋᴀᴅᴀşıɴᴅᴀɴ ᴀʏʀıʟᴍᴀᴋ ɪᴄ̧ɪɴ sᴀɴᴀ 𝟷 ᴍɪʟʏᴏɴ ᴛʟ ᴏ̈ɴᴇʀsᴇʏᴅɪ, ʏᴀᴘᴀʀ ᴍıʏᴅıɴ?','ɢʀᴜᴘᴛᴀ ᴏʟᴍᴀᴍᴀsıɴı ɪsᴛᴇᴅɪɢ̆ɪɴ ᴋɪşɪʏɪ ᴇᴛɪᴋᴇᴛʟᴇʀ ᴍɪsɪɴ?','ʙᴜ ᴏᴅᴀᴅᴀᴋɪ ᴇɴ sɪɴɪʀ ʙᴏᴢᴜᴄᴜ ᴋɪşɪ ᴋɪᴍ?','ɢʀᴜᴘᴛᴀᴋɪ ᴇɴ ɢɪᴢᴇᴍʟɪ ᴋɪşɪ ᴋɪᴍ ?','ʜɪᴄ̧ sıʀғ ғᴀʏᴅᴀ sᴀɢ̆ʟᴀᴅıɢ̆ı ɪᴄ̧ɪɴ ʙɪʀɪʏʟᴇ ᴀʀᴋᴀᴅᴀş ᴋᴀʟᴅıɢ̆ıɴ ᴏʟᴅᴜ ᴍᴜ?','ʙᴜ ʜᴀʏᴀᴛᴛᴀ ʜɪᴄ̧ ᴋɪᴍsᴇʏᴇ sᴏ̈ʏʟᴇᴍᴇᴅɪɢ̆ɪɴ ʙɪʀ sıʀʀıɴ ᴠᴀʀ ᴍı?',
'ʙᴜ ᴏᴅᴀᴅᴀᴋɪ ᴇɴ sɪɴɪʀ ʙᴏᴢᴜᴄᴜ ᴋɪşɪ ᴋɪᴍ?','ʙɪʀ ᴜʏɢᴜʟᴀᴍᴀʏı ᴛᴇʟᴇғᴏɴᴜɴᴜᴢᴅᴀɴ sɪʟᴍᴇᴋ ᴢᴏʀᴜɴᴅᴀ ᴋᴀʟsᴀɴıᴢ ʜᴀɴɢɪsɪɴɪ sɪʟᴇʀᴅɪɴɪᴢ?','ᴇɴ sᴏɴ sᴏ̈ʏʟᴇᴅɪɢ̆ɪɴ ʏᴀʟᴀɴ ɴᴇᴅɪʀ?','ʙᴜ ɢʀᴜᴘᴛᴀ ᴋɪᴍsᴇɴɪɴ ᴀʀᴋᴀsıɴᴅᴀɴ ᴋᴏɴᴜşᴛᴜɴ ᴍᴜ ?','ᴄ̧ᴇşɪᴛʟɪ ʙᴀᴛıʟ ɪɴᴀɴᴄ̧ʟᴀʀıɴ ᴠᴀʀ ᴍı? ᴠᴀʀsᴀ ᴏɴʟᴀʀ ɴᴇʟᴇʀ?','ᴛᴇʟᴇғᴏɴᴜɴᴜᴢᴅᴀ ᴀʀᴀᴅıɢ̆ıɴ sᴏɴ şᴇʏ ɴᴇʏᴅɪ?','Bᴜ ɢʀᴜᴘᴛᴀ ᴋɪᴍsᴇɴɪɴ ᴀʀᴋᴀsıɴᴅᴀɴ ᴋᴏɴᴜşᴛᴜɴ ᴍᴜ ?','ᴍᴇᴠᴄᴜᴛ ᴇʀᴋᴇᴋ ᴀʀᴋᴀᴅᴀşıɴıɴ ʏᴀ ᴅᴀ ᴋıᴢ ᴀʀᴋᴀᴅᴀşıɴıɴ sᴇɴɪɴʟᴇ ᴀʏɴı ᴜ̈ɴɪᴠᴇʀsɪᴛᴇʏᴇ ɢɪᴛᴍᴇsɪɴɪ ɪsᴛᴇʀ ᴍɪsɪɴ?','ɢʀᴜᴘᴛᴀ ᴋɪᴍɪɴ ʜᴇsᴀʙıɴᴀ ɢɪʀᴍᴇᴋ ɪsᴛᴇʀsɪɴ?','ʙᴜ̈ʏᴜ̈ʏᴇɴ ʜᴀʏᴀʟɪ ʙɪʀ ᴀʀᴋᴀᴅᴀşıɴıᴢ ᴠᴀʀ ᴍıʏᴅı?','ᴍᴇᴠᴄᴜᴛ ᴇʀᴋᴇᴋ ᴀʀᴋᴀᴅᴀşıɴıɴ ʏᴀ ᴅᴀ ᴋıᴢ ᴀʀᴋᴀᴅᴀşıɴıɴ sᴇɴɪɴʟᴇ ᴀʏɴı ᴜ̈ɴɪᴠᴇʀsɪᴛᴇʏᴇ ɢɪᴛᴍᴇsɪɴɪ ɪsᴛᴇʀ ᴍɪsɪɴ?',
'ᴋᴀʀşı ᴄɪɴsᴛᴇ ɪʟᴋ ᴅɪᴋᴋᴀᴛɪɴɪ ᴄ̧ᴇᴋᴇɴ ɴᴇ?','ᴛᴇʟᴇғᴏɴᴜɴᴜᴢᴅᴀ ʜᴀɴɢɪ ᴜʏɢᴜʟᴀᴍᴀᴅᴀ ᴇɴ ᴄ̧ᴏᴋ ᴢᴀᴍᴀɴ ʜᴀʀᴄıʏᴏʀsᴜɴᴜᴢ?','şɪᴍᴅɪ sᴀɴᴀ ʙɪʀ ᴇᴠʟᴇɴᴍᴇ ᴛᴇᴋʟɪғɪ ɢᴇʟsᴇ ᴠᴇ sᴇᴠᴍᴇᴅɪɢ̆ɪɴ ʙɪʀɪ ᴏʟsᴀ, ᴠᴇ ʙᴜ sᴀɴᴀ sᴏɴ ɢᴇʟᴇᴄᴇᴋ ᴇᴠʟɪʟɪᴋ ᴛᴇᴋʟɪғɪ ᴏʟsᴀ ᴋᴀʙᴜʟ ᴇᴅᴇʀᴍɪʏᴅɪɴ?','ᴇʀᴋᴇᴋ ᴀʀᴋᴀᴅᴀşıɴ ᴠᴇʏᴀ ᴋıᴢ ᴀʀᴋᴀᴅᴀşıɴ sᴇɴɪ ʜɪᴄ̧ ᴜᴛᴀɴᴅıʀᴅı ᴍı?','ᴇɴ ᴛᴜʜᴀғ ᴛᴀᴋᴍᴀ ᴀᴅıɴ ɴᴇᴅɪʀ?','ʜɪᴄ̧ sıɴıғᴛᴀ ʀᴇᴢɪʟ ᴏʟᴅᴜɴ ᴍᴜ?','ɢʀᴜʙᴜɴ ɴᴇşᴇsɪ ᴋɪᴍ?','ʙɪʀ ᴜʏɢᴜʟᴀᴍᴀʏı ᴛᴇʟᴇғᴏɴᴜɴᴜᴢᴅᴀɴ sɪʟᴍᴇᴋ ᴢᴏʀᴜɴᴅᴀ ᴋᴀʟsᴀɴıᴢ ʜᴀɴɢɪsɪɴɪ sɪʟᴇʀᴅɪɴɪᴢ?','ʜᴀʏᴀᴛıɴᴅᴀ ʏᴀᴘᴛıɢ̆ıɴ ᴇɴ ᴄ̧ıʟɢıɴ şᴇʏ ɴᴇᴅɪʀ?','şɪᴍᴅɪ sᴀɴᴀ ʙɪʀ ᴇᴠʟᴇɴᴍᴇ ᴛᴇᴋʟɪғɪ ɢᴇʟsᴇ ᴠᴇ sᴇᴠᴍᴇᴅɪɢ̆ɪɴ ʙɪʀɪ ᴏʟsᴀ, ᴠᴇ ʙᴜ sᴀɴᴀ sᴏɴ ɢᴇʟᴇᴄᴇᴋ ᴇᴠʟɪʟɪᴋ ᴛᴇᴋʟɪғɪ ᴏʟsᴀ ᴋᴀʙᴜʟ ᴇᴅᴇʀᴍɪʏᴅɪɴ?',
'ʙᴇʏɴɪɴɪ ʙɪʀ ʀᴏʙᴏᴛᴀ ʏᴇʀʟᴇşᴛɪʀᴇʙɪʟɪʀ ᴠᴇ sᴏɴsᴜᴢᴀ ᴋᴀᴅᴀʀ ʙᴜ şᴇᴋɪʟᴅᴇ ʏᴀşᴀʏᴀʙɪʟsᴇᴅɪɴ,ʙᴜɴᴜ ʏᴀᴘᴀʀ ᴍıʏᴅıɴ?','Kᴀʀᴀɴʟıᴋᴛᴀɴ/ʏᴜ̈ᴋsᴇᴋʟɪᴋᴛᴇɴ ᴋᴏʀᴋᴀʀ ᴍısıɴ?','ᴇɴ ᴋᴏ̈ᴛᴜ̈ ɢʀᴜᴘ ʜᴀɴɢɪsɪᴅɪʀ?','ʜɪᴄ̧ sᴇᴠɢɪʟɪɴɪ ʙɪʀɪʏʟᴇ ᴀʟᴅᴀᴛᴛıɴ ᴍı?','ʜɪᴄ̧ sᴀʜᴛᴇ ᴋɪᴍʟɪᴋ ᴋᴜʟʟᴀɴᴅıɴ ᴍı?','ʙᴜ ɢʀᴜᴘᴅᴀ ᴇɴ ᴀᴢ ᴋɪᴍɪ sᴇᴠɪʏᴏʀsᴜɴ ᴠᴇ ɴᴇᴅᴇɴ?','ᴋᴜ̈ʟᴛᴜ̈ʀᴜ̈ᴍᴜ̈ᴢᴜ̈ɴ ᴇɴ ᴄ̧ᴏᴋ sᴇᴠᴅɪɢ̆ɪɴɪᴢ ʏᴀɴı ɴᴇᴅɪʀ?','ɢᴏ̈ʀᴅᴜ̈ɢ̆ᴜ̈ɴ ᴇɴ ɢᴀʀɪᴘ ʀᴜ̈ʏᴀ ɴᴇʏᴅɪ?','ᴀɪʟᴇɴɪɴ sᴇɴɪɴ ʜᴀᴋᴋıɴᴅᴀ ʙɪʟᴍᴇᴅɪɢ̆ɪɴᴇ sᴇᴠɪɴᴅɪɢ̆ɪɴ şᴇʏ ɴᴇᴅɪʀ?','ᴠᴜ̈ᴄᴜᴅᴜɴᴜɴ ʜᴀɴɢɪ ʙᴏ̈ʟᴜ̈ᴍʟᴇʀɪɴᴅᴇɴ ɢıᴅıᴋʟᴀɴıʏᴏʀsᴜɴ?','ʙᴜ ʜᴀʏᴀᴛᴛᴀ ʜɪᴄ̧ ᴋɪᴍsᴇʏᴇ sᴏ̈ʏʟᴇᴍᴇᴅɪɢ̆ɪɴ ʙɪʀ sıʀʀıɴ ᴠᴀʀ ᴍı?','ʙɪʀɪʏʟᴇ ᴄ̧ıᴋᴀʀᴋᴇɴ ʏᴀᴘᴛıɢ̆ıɴ ᴇɴ ᴜᴛᴀɴᴄ̧ ᴠᴇʀɪᴄɪ şᴇʏ ɴᴇʏᴅɪ?',
'ᴀʀᴋᴀᴅᴀşʟᴀʀıɴʟᴀ ʏᴀᴘᴍᴀʏı sᴇᴠᴅɪɢ̆ɪɴ ᴀᴍᴀ sᴇᴠɢɪʟɪɴɪɴ ᴏ̈ɴᴜ̈ɴᴅᴇ ᴀsʟᴀ ʏᴀᴘᴍᴀʏᴀᴄᴀɢ̆ıɴ şᴇʏ ɴᴇᴅɪʀ?','ᴜɴɪᴄᴏʀᴜɴ ᴍᴜ ᴏʟᴍᴀsıɴı ɪsᴛᴇʀᴅɪɴ ᴇᴊᴅᴇʀʜᴀɴ ᴍı?','şᴜ ᴀɴᴋɪ ʀᴜʜ ʜᴀʟɪɴᴇ ʙᴀᴋᴀʀᴀᴋ ɴᴇ ᴛᴜ̈ʀ ғɪʟᴍ ɪᴢʟᴇʀsɪɴ (ᴀᴋsɪʏᴏɴ/ᴅʀᴀᴍ/ʙɪʟɪᴍ ᴋᴜʀɢᴜ/ʀᴏᴍᴀɴᴛɪᴋ ᴋᴏᴍᴇᴅɪ/ʙɪʏᴏɢʀᴀғɪ/ғᴀɴᴛᴀsᴛɪᴋ)','ᴡᴇʙ ɢᴇᴄ̧ᴍɪşɪɴɪᴢɪ, ʙɪʀɪʟᴇʀɪ ɢᴏ̈ʀᴜ̈ʀsᴇ ᴜᴛᴀɴᴀᴄᴀɢ̆ıɴıᴢ şᴇʏ ɴᴇ ᴏʟᴜʀᴅᴜ?','ʜɪᴄ̧ sᴇᴠɢɪʟɪɴɪ ᴀʟᴅᴀᴛᴍᴀʏı ᴅᴜ̈şᴜ̈ɴᴅᴜ̈ɴ ᴍᴜ̈?','ʙɪʀɪsɪ ᴋıᴢ ᴀʀᴋᴀᴅᴀşıɴ / ᴇʀᴋᴇᴋ ᴀʀᴋᴀᴅᴀşıɴᴅᴀɴ ᴀʏʀıʟᴍᴀᴋ ɪᴄ̧ɪɴ sᴀɴᴀ 𝟷 ᴍɪʟʏᴏɴ ᴛʟ ᴏ̈ɴᴇʀsᴇʏᴅɪ, ʏᴀᴘᴀʀ ᴍıʏᴅıɴ?','ɪ̇ɴsᴀɴʟᴀʀıɴ sᴇɴɪɴ ʜᴀᴋᴋıɴᴅᴀ ʙɪʟᴍᴇsɪɴɪ ɪsᴛᴇᴅɪɢ̆ɪɴ şᴇʏ ɴᴇᴅɪʀ?','ʙᴜ ɢʀᴜᴘᴛᴀ ᴋɪᴍsᴇɴɪɴ ᴀʀᴋᴀsıɴᴅᴀɴ ᴋᴏɴᴜşᴛᴜɴ ᴍᴜ ?','şɪᴍᴅɪʏᴇ ᴋᴀᴅᴀʀ ɢᴏ̈ʀᴅᴜ̈ɢ̆ᴜ̈ᴍ ᴇɴ ɢᴀʀɪᴘ ʀᴜ̈ʏᴀʏı ᴀɴʟᴀᴛ.',
'şɪᴍᴅɪʏᴇ ᴋᴀᴅᴀʀ ʙɪʀ ʙᴀşᴋᴀsıɴᴀ sᴏ̈ʏʟᴇᴅɪɢ̆ɪɴ ᴇɴ ᴀᴄıᴍᴀsıᴢᴄᴀ şᴇʏ ɴᴇʏᴅɪ?','ᴅᴜ̈ɴʏᴀᴅᴀᴋɪ ʜᴇʀʜᴀɴɢɪ ʙɪʀɪɴɪ ᴛᴜ̈ʀᴋɪʏᴇ’ɴɪɴ ʙᴀşᴋᴀɴı ʏᴀᴘᴀʙɪʟsᴇʏᴅɪɴ ʙᴜ ᴋɪᴍ ᴏʟᴜʀᴅᴜ?','ᴀɪʟᴇɴɪᴢɪɴ ᴜʏɢᴜʟᴀᴅıɢ̆ı ᴇɴ ᴛᴜʜᴀғ ɢᴇʟᴇɴᴇᴋ ɴᴇᴅɪʀ?','ʙɪʀɪsɪ ᴋıᴢ ᴀʀᴋᴀᴅᴀşıɴ / ᴇʀᴋᴇᴋ ᴀʀᴋᴀᴅᴀşıɴᴅᴀɴ ᴀʏʀıʟᴍᴀᴋ ɪᴄ̧ɪɴ sᴀɴᴀ 𝟷 ᴍɪʟʏᴏɴ ᴛʟ ᴏ̈ɴᴇʀsᴇʏᴅɪ, ʏᴀᴘᴀʀ ᴍıʏᴅıɴ?','ᴋᴜ̈ʟᴛᴜ̈ʀᴜ̈ᴍᴜ̈ᴢᴜ̈ɴ ᴇɴ ᴄ̧ᴏᴋ sᴇᴠᴅɪɢ̆ɪɴɪᴢ ʏᴀɴı ɴᴇᴅɪʀ?','ɢʀᴜᴘᴛᴀ ᴋɪ ᴋᴀɴᴋᴀʟᴀʀıɴı ᴇᴛɪᴋᴇᴛʟᴇʀ ᴍɪsɪɴ ?','ᴅɪʀsᴇɢ̆ɪɴɪ ʏᴀʟᴀʏᴀʙɪʟɪʀ ᴍɪsɪɴ?','ᴋᴀᴅıɴ/ᴇʀᴋᴇᴋ ᴏʟᴍᴀɴıɴ ᴇɴ ᴋᴏ̈ᴛᴜ̈ ᴠᴇ ᴇɴ ɪʏɪ ʏᴀɴı ɴᴇᴅɪʀ?','Hᴀʏᴀᴛᴛᴀ ᴜɴᴜᴛᴍᴀᴅıɢ̆ıɴ ʙɪʀɪ ᴠᴀʀ ᴍı?','ᴀʟışᴠᴇʀɪşɪɴ ᴅɪʙɪɴᴇ ᴠᴜʀᴜʀᴋᴇɴ ᴇɴ ᴄ̧ᴏᴋ ʜᴀʀᴄᴀᴍᴀ ʏᴀᴘᴛıɢ̆ıɴ ɢᴜ̈ɴ ʜᴀɴɢɪsɪʏᴅɪ?','ʙᴜ ɢʀᴜᴘᴛᴀ ᴋɪᴍsᴇɴɪɴ ᴀʀᴋᴀsıɴᴅᴀɴ ᴋᴏɴᴜşᴛᴜɴ ᴍᴜ ?',
'ᴋᴇɴᴅɪɴɪ ᴇɴ ᴇᴢɪᴋ ʜɪssᴇᴛᴛɪɢ̆ɪɴ ᴀɴ ʜᴀɴɢɪsɪʏᴅɪ ?','ᴏʏᴜɴᴜ ᴏʏɴᴀʏᴀɴ ᴏʏᴜɴᴄᴜ ɢʀᴜʙᴜɴᴅᴀ ʏᴇʀ ᴀʟᴀɴʟᴀʀᴅᴀɴ ᴋɪᴍɪ ᴏ̈ᴘᴍᴇᴋ ɪsᴛᴇʀsɪɴ?','ʜɪᴄ̧ ʏᴀsᴀʏᴀ ᴀʏᴋıʀı ʙɪʀ şᴇʏʟᴇʀ ʏᴀᴘᴛıɢ̆ıɴ ᴏʟᴅᴜ ᴍᴜ?','ʜᴀʏᴀᴛıɴıɴ ɢᴇʀɪ ᴋᴀʟᴀɴıɴᴅᴀ sᴀᴅᴇᴄᴇ ʙɪʀ ᴋıʏᴀғᴇᴛ ɢɪʏᴇʙɪʟsᴇʏᴅɪɴ, ʙᴜ ᴋıʏᴀғᴇᴛɪɴ ʜᴀɴɢɪ ʀᴇɴᴋ ᴏʟᴜʀᴅᴜ?','şɪᴍᴅɪʏᴇ ᴋᴀᴅᴀʀ ʙᴀşᴋᴀsıɴᴀ sᴏ̈ʏʟᴇᴅɪɢ̆ɪɴ ᴇɴ ᴀɴʟᴀᴍʟı şᴇʏ ɴᴇʏᴅɪ?','ɢʀᴜᴘᴛᴀ ʙᴜʟᴜɴᴀɴ ᴇɴ ᴜʏᴜᴢ ᴋɪşɪ ᴋɪᴍ ?','ᴋɪᴍsᴇɴɪɴ sᴇɴɪɴ ʜᴀᴋᴋıɴᴅᴀ ʙɪʟᴍᴇᴅɪɢ̆ɪ ʙɪʀ şᴇʏ ɴᴇᴅɪʀ?','ʜɪᴄ̧ sıɴıғᴛᴀ ᴜʏᴜᴅᴜɴ ᴍᴜ?','ʜɪᴄ̧ ʏᴀsᴀʏᴀ ᴀʏᴋıʀı ʙɪʀ şᴇʏʟᴇʀ ʏᴀᴘᴛıɢ̆ıɴ ᴏʟᴅᴜ ᴍᴜ?','şɪᴍᴅɪʏᴇ ᴋᴀᴅᴀʀ ɢᴏ̈ʀᴅᴜ̈ɢ̆ᴜ̈ᴍ ᴇɴ ɢᴀʀɪᴘ ʀᴜ̈ʏᴀʏı ᴀɴʟᴀᴛ','ᴛᴏᴘʟᴜᴍᴅᴀ ᴇɴ ᴜᴛᴀɴᴄ̧ ᴠᴇʀɪᴄɪ ᴀɴıɴıᴢ ɴᴇʏᴅɪ?','ᴋᴀʀşı ᴄɪɴsᴛᴇ ɪʟᴋ ᴅɪᴋᴋᴀᴛɪɴɪ ᴄ̧ᴇᴋᴇɴ ɴᴇ?','ɪ̇ʟᴋ ɪşɪɴ ɴᴇʏᴅɪ?',
'Bu Grupta En Çok Sevdiğin Kişi Kimdir ...','En Çok Gitmek İstediğin Ülke Neresidir ...','Medeni Halin Nedir ...','Özlediğin Bir Kimse Var Mı ...','Fotojenik Misin Kanka ...','Dans Etmeyi Sever Misin ...','Eski Sevgilinin Adı Ne ...','En Sevdigin Film Hangisi ...','En Sevdiğin Sanatçı Kim ...','Ünlü veya Fenomen Olmak İster Misin ...','Gözlerinin Rengi Nedir ...','Boyun Kaç Santim :)',
'Bugün için Bir Planın Var Mı ...','Birini Kahraman Yapan Nedir ...','Bir Dilek Hakkın Olsa Ne Dilerdim ...','Çocukken En Büyük Hayalin Neydi ...','Aşka İnanır Mısın ...','Bir Hedefin Var Mı ...','Karanlıktan Korkar Misin ...','Müzik Dinlemeyi Sever Misin ...','Sizce Anlaşılmak Kolay Mı ...','En Sevdiğin Ders Nedir ...','Nabiyosun Aslanım ...',
'Bu Grupta Sevdiğin Birini Etiketle ...','Bu Gruptaki En Yakışıklı Kişiyi Etiketleyin ...','Bu Gruptaki En Güzel Kız Kim ...','Sizce Gruptaki En Akıllı Kişi Kim ...','Kadere İnanır Mısın ...','Hayatından Memnun Musun ...','Hey, Sen Çok Şanslısın ...','En sevdiğin Ninja Kaplumbağa hangisiydi ...','Güliver olsaydın devler ülkesine mi yoksa cüceler ülkesine mi düşmek isterdin ...',
'En sevdiğin Pokemon hangisi ...','Çocukken izlemeyi en çok sevdiğin çizgi filmler hangileriydi ...','Dünyaya bir dahaki gelişinde hayvan olarak gelseydin hangi hayvan olmak isterdin ...','Bir şiir olsaydın hangi şiir olurdun ...','En sevdiğin Ninja Kaplumbağa hangisiydi ...','Issız bir adaya düşseydin yanına kesinlikle ‘’almayacağın’’ üç şey ne olurdu ...','Küçükken hiç pembe dizi izledin mi, İzlediysen hangisi ...',
'Sihirli bir değneğin olsaydı öncelikle neyi değiştirirdin ...','Arkadaşının sırrını 1 milyon dolar karşılığında ifşa eder miydin ...','Bir dizinin içine ışınlanmak isteseydin bu hangi dizi olurdu ...','Filmlerdeki kötü karakterlerden biri olsaydın hangisi olurdun ...','Küçükken oynamayı en sevdiğin atari oyunu hangisiydi ...','Şu an okuduğun iyi bir kitap var mı , Öneriyor musun ...','Hangi dizileri izliyorsun ...','En son hangi filmi izledin ...',
'Telefonunuzda olmadan yaşayamayacağınız herhangi bir uygulama var mı ...','Hayatın geri kalanında sadece bir film türünü izleyebiliceksen, ne olurdu ...','Herkesin sevdiği sizin nefret ettiğiniz bir kitap var mı, ya da tam tersi ...','Seni ağlatan en son film ne oldu, veya yüksek sesle güldüren ...','İnstagramda kesin takip et dediğin birisi var mı ...','En sevdiğin kitabın ismi ne ...','En son hangi diziyi tek oturuşta bitirdin ...',
'Çocukluğunda en sevdiğin çizgi film hangisiydi ...','Çocukluğunda en sevdiğin çizgi film karakteri hangisiydi ...','İzlemeyi en çok sevdiğin film türü ne ...','Telefonunun ekran süresi ortalama kaç saat ...','Spor yapmayı sever misin ...','Voleybol maçları izler misin ...','Sevdiğin spor dalı ne ...','Çocukken aşık olduğun kurgusal bir karakter var mıydı ...','Sonsuza kadar sadece bir kitap okuyacak olsan bu hangi kitap olurdu ...',
'En sevdiğin distopik eser hangisi ...','Hangi tür kitaplar okumayı seviyorsun ...','Kahve içmek istediğin kitap karakteri var mı ...','Takip ettiğin bir influencer var mı ...','En çok hangi influencerın önerdiği ürünleri kullanıyorsun ...','Okurken ağlamana  neden olacak bir kitap oldu mu ...','En sevdiğin yazar kim ...','En çok hangi dijital platformu kullanıyorsun ...',
'Hayatta gerçekleştirmek istediğin bir hayalin var mı?', 'Kaç tane kız aradaşın oldu ?','Nefret ettiğiniz ancak yine de kullandığın bir uygulama var mı?','En tuhaf korkun nedir?','Hangi takımı tutuyorsun ?','Romayı senmi yaktın?','Fiziksel olarak sana en acı veren deneyimin ne oldu?','Hangi yılda doğdun?','Boyun kaç ?','En sevdiğin hobi nedir?','Nasılsın ?','Gruptaki gizli aşık olduğun kim?',
'Nerelisin?','Naber nasıl gidiyor?','Grupta nefret ettiğin kişi kim?','Kaç tane sevgilin oldu?','Gruptaki partnerin kim?','Kendini 3 kelime ile anlatırmısın','Selam ne yapıyorsun?','En son okuduğun kitabın adı neydi','Grubu yakacakmışsın doğru mu?','En sevdiğin müzik nedir?','Googlede en son neye baktın?','Okumayı en çok sevdiğin kitap türü nedir ...','Çocukluğundan unutmadığın bir çizgi film var mı ...',
'Aşk mı? para mı?','En son yaptığın en saçma olay neydi?','Keşke şu olsada yesek dediğin şey neydi?','Karşı cinste aradığın krater nedir?','Karşı cinsin ilk neresine bakıyorsun?','Grupta sevdiğin 3 kişiyi etiketler misin?','Grupta en sevmediğin 3 kişiyi etiketler misin?','Grupta işte aradığım eş adayı dediğin kişiyi etiketler misin?','En Sevdiğin Renk Nedir ...',
'Aşkın yaşı yoktur diyorlar doğru mu?','Bir adaya düşsen yanına alacağın üç şey ne olurdu?','Grupta sevgilin var mı?','İnstagrama günde kaç story atıyorsun?','Hangi şehirde yaşıyorsun','Şehrini üç kelime ile anlatır mısın?','Memleketini üç kelime ile anlatır mısın?','Geçmişe dönüp yaşadığın bir olayı silebilmen mümkün olsaydı hangi olay olurdu?',
'ʙɪʀ ᴀʏɴᴀɴıɴ ᴏ̈ɴᴜ̈ɴᴅᴇ ʏᴀᴘᴛıɢ̆ıɴ ᴇɴ ᴄ̧ıʟɢıɴᴄᴀ şᴇʏ ɴᴇᴅɪʀ?','ɪ̇ɴsᴀɴʟᴀʀıɴ sɪᴢᴇ ɴᴇ sᴏʀᴍᴀsıɴᴅᴀɴ ʙıᴋᴛıɴıᴢ?ɢɪᴢʟɪᴅᴇɴ ɢɪᴢʟɪᴅᴇɴ sᴀᴅᴇᴄᴇ ᴏɴᴜɴ ɪᴄ̧ɪɴ ɢᴇʟᴅɪɢ̆ɪɴ ᴋɪᴍsᴇ ᴠᴀʀ ᴍı ɢʀᴜᴘᴛᴀ ?','ʜɪᴄ̧ ᴋɪᴍsᴇʏɪ ᴏ̈ᴢᴇʟᴅᴇɴ ʀᴀʜᴀᴛsıᴢ ᴇᴛᴛɪɴ ᴍɪ?','ɪ̇ɴsᴀɴʟᴀʀı ʏᴀɴᴀɴ ʙɪʀ ʙɪɴᴀᴅᴀɴ ᴋᴜʀᴛᴀʀıʏᴏʀ ᴏʟsᴀʏᴅıɴıᴢ ᴠᴇ ʙɪʀ ᴋɪşɪʏɪ ʙᴜ ɢʀᴜᴘᴅᴀɴ ɢᴇʀɪᴅᴇ ʙıʀᴀᴋᴍᴀᴋ ᴢᴏʀᴜɴᴅᴀ ᴋᴀʟıʀsᴀɴıᴢ, ᴋɪᴍ ᴏʟᴜʀᴅᴜ?','ʏᴇʀᴅᴇɴ ʙɪʀ şᴇʏɪ ᴀʟıᴘ ʜɪᴄ̧ ʏᴇᴅɪɴ ᴍɪ?','ɢʀᴜᴘᴛᴀ ᴋɪ ᴜ̈ᴄ̧ ᴋᴀɴᴋᴀɴı ᴇᴛɪᴋᴇᴛʟᴇʀ ᴍɪsɪɴ?','ᴋᴀʀᴀɴʟıᴋᴛᴀɴ/ʏᴜ̈ᴋsᴇᴋʟɪᴋᴛᴇɴ ᴋᴏʀᴋᴀʀ ᴍısıɴ?','ɢʀᴜʙᴜɴ ᴇɴ ʏᴀᴋışıᴋʟısı ᴋɪᴍ ?','ʀᴇᴀʟ ʜᴀʏᴀᴛᴛᴀ ᴛᴀɴıᴍᴀᴋ ɪsᴛᴇᴅɪɢ̆ɪɴ ᴋɪᴍsᴇ ᴠᴀʀ ᴍı ɢʀᴜᴘᴛᴀ ?','ɢʀᴜʙᴜɴ ᴇɴ ʏᴀᴋışıᴋʟısı ᴋɪᴍ ?','ᴄ̧ıᴋᴛıɢ̆ıɴ ᴇɴ ʏᴀşʟı ᴋɪşɪ ᴋɪᴍ?','ɢʀᴜʙᴜɴ ᴇɴ ɢᴜ̈ᴢᴇʟ ᴋıᴢı ᴋɪᴍ ?',
'ɢʀᴜᴘᴛᴀ ᴀᴅᴍɪɴ ᴏʟsᴀɴ ᴋɪᴍɪ ʙᴀɴʟᴀʀᴅıɴ ɴᴇᴅᴇɴ ?','ʜᴀғᴛᴀᴅᴀ ᴋᴀᴄ̧ ᴋᴇᴢ ᴀʏɴı ᴘᴀɴᴛᴏʟᴏɴᴜ ɢɪʏɪʏᴏʀsᴜɴ?','ᴀɪʟᴇɴɪᴢɪɴ ᴜʏɢᴜʟᴀᴅıɢ̆ı ᴇɴ ᴛᴜʜᴀғ ɢᴇʟᴇɴᴇᴋ ɴᴇᴅɪʀ?','ᴋᴇɴᴅɪɴɪ ᴇɴ ᴇᴢɪᴋ ʜɪssᴇᴛᴛɪɢ̆ɪɴ ᴀɴ ʜᴀɴɢɪsɪʏᴅɪ ?','ɢʀᴜᴘᴛᴀ ɴᴇғʀᴇᴛ ᴇᴛᴛɪɢ̆ɪɴ ʙɪʀɪ ᴠᴀʀ ᴍı?','ʙᴜʀᴅᴀ ᴋɪ ᴋɪᴍsᴇʏᴇ ʏᴀʟᴀɴ sᴏ̈ʏʟᴇᴅɪɴ ᴍɪ?','ʙɪʀ ɪʟɪşᴋɪᴅᴇᴋɪ ᴇɴ ʙᴜ̈ʏᴜ̈ᴋ ᴋᴏʀᴋᴜɴ ɴᴇᴅɪʀ?','ʙᴜ ʜᴀʏᴀᴛᴛᴀ ʜɪᴄ̧ ᴋɪᴍsᴇʏᴇ sᴏ̈ʏʟᴇᴍᴇᴅɪɢ̆ɪɴ ʙɪʀ sıʀʀıɴ ᴠᴀʀ ᴍı?','ɢʀᴜʙᴜɴ ᴏʟᴍᴀᴢsᴀ ᴏʟᴍᴀᴢ ᴅᴇᴅɪɢ̆ɪɴ şᴇʏɪ ɴᴇᴅɪʀ?','ɢʀᴜᴘᴛᴀᴋɪ sıʀᴅᴀşıɴ ᴋɪᴍ ?','ɢʀᴜʙᴜ ɴᴇ ᴋᴀᴅᴀʀ sᴇᴠɪʏᴏʀsᴜɴ ?','sᴀᴄ̧ʟᴀʀıɴı ᴜᴢᴀᴛᴍᴀʏı ᴅᴜ̈şᴜ̈ɴsᴇɴ ɴᴇ ᴋᴀᴅᴀʀ ᴜᴢᴀᴛıʀᴅıɴ?','ᴋᴇşᴋᴇ ᴏɴᴜɴ ʜᴀᴋᴋıɴᴅᴀ ʏᴀʟᴀɴ sᴏ̈ʏʟᴇsᴇʏᴅɪᴍ ᴅᴇᴅɪɢ̆ɪɴ şᴇʏ ɴᴇᴅɪʀ?','ɢʀᴜʙᴜɴ ᴇɴ ᴇɢᴏɪsᴛɪ ᴋɪᴍ ?','sᴏɴ ᴀᴛᴛıɢ̆ıɴ ᴍᴇsᴀᴊ ɴᴇʏᴅɪ?',
'ɢʀᴜᴘᴛᴀᴋɪ ᴇɴ sᴇᴠɢɪɢ̆ɪɴ ᴀᴅᴍɪɴ ᴋɪᴍ ?','ᴇɴ ᴜᴛᴀɴ ᴠᴇʀɪᴄɪ ᴋɪşɪsᴇʟ ʙᴀᴋıᴍ ᴀʟışᴋᴀɴʟıɢ̆ıɴ ɴᴇᴅɪʀ?','ɢʀᴜʙᴜ ɴᴇ ᴋᴀᴅᴀʀ sᴇᴠɪʏᴏʀsᴜɴ ?','ɢʀᴜᴘᴛᴀ ɴᴇʏɪ ᴅᴇɢ̆ɪşᴛɪʀᴍᴇᴋ ɪsᴛᴇʀᴅɪɴ?','ɪ̇ʟᴋ ɪşɪɴ ɴᴇʏᴅɪ?','ᴀɪʟᴇɴᴅᴇɴ ʙɪʀɪ sᴇɴɪ ʙᴜ ɢʀᴜᴘᴛᴀ ɢᴏ̈ʀsᴇ ɴᴇ ᴏʟᴜʀ ?','ɢʀᴜᴘᴛᴀ ɴᴇғʀᴇᴛ ᴇᴛᴛɪɢ̆ɪɴ ʙɪʀɪ ᴠᴀʀ ᴍı?','ᴋᴇɴᴅɪ ɢᴏ̈ʀᴜ̈ɴᴜşᴜ̈ɴᴜ̈ 𝟷 ɪʟᴇ 𝟷𝟶 ᴀʀᴀsıɴᴅᴀ ᴘᴜᴀɴʟᴀ :)','ʙɪʀ ᴏᴅᴀᴅᴀ ᴜᴢᴜɴ ʙɪʀ sᴜ̈ʀᴇ ʜᴀᴘsᴏʟᴀᴄᴀɢ̆ıɴı ᴅᴜ̈şᴜ̈ɴsᴇɴ ʏᴀɴıɴᴅᴀ ᴏʟᴍᴀsıɴı ɪsᴛᴇᴅɪɢ̆ɪɴ ᴜ̈ᴄ̧ şᴇʏ ɴᴇ ᴏʟᴜʀᴅᴜ?','ᴇɴ sᴏɴ ɴᴇ ᴢᴀᴍᴀɴ ʜᴜ̈ɴɢᴜ̈ʀ ʜᴜ̈ɴɢᴜ̈ʀ ᴀɢ̆ʟᴀᴅıɢ̆ıɴı ʜᴀᴛıʀʟıʏᴏʀ ᴍᴜsᴜɴ?','ɢʀᴜᴘᴛᴀ ʙᴜʟᴜɴᴀɴ ᴇɴ ᴜʏᴜᴢ ᴋɪşɪ ᴋɪᴍ ?','ᴋᴜʀᴛ ᴍᴜ ᴋᴇʟɪᴍᴇ ᴏʏᴜɴᴜ ᴍᴜ ?','ɢʀᴜᴘᴛᴀ ᴋɪᴍᴅᴇɴ ɢıᴄıᴋ ᴀʟıʏᴏʀsᴜɴ?','ɢʀᴜᴘᴛᴀ ᴏʟᴍᴀᴍᴀsıɴı ɪsᴛᴇᴅɪɢ̆ɪɴ ᴋɪşɪʏɪ ᴇᴛɪᴋᴇᴛʟᴇʀ ᴍɪsɪɴ?',
'ᴀᴋʀᴀʙᴀʟᴀʀıɴᴅᴀɴ ᴋɪᴍsᴇʏɪ ᴅᴀᴠᴇᴛ ᴇᴛᴛɪɴ ᴍɪ ɢʀᴜʙᴀ ?','ʜɪᴄ̧ ᴏᴋᴜʟᴅᴀ ᴋᴀᴠɢᴀ ᴇᴛᴛɪɴ ᴍɪ?','ʙɪʀɪɴɪɴ ᴛᴇʟᴇғᴏɴᴜɴᴅᴀ ɢᴏ̈ʀᴅᴜ̈ɢ̆ᴜ̈ɴ ᴇɴ ᴛᴜʜᴀғ şᴇʏ ɴᴇᴅɪʀ?','ɢʀᴜᴘ sᴇɴɪɴ ɪᴄ̧ɪɴ ɴᴇ ɪғᴀᴅᴇ ᴇᴅɪʏᴏʀ?','ɢʀᴜʙᴜɴ ᴇɴ ᴇɢᴏɪsᴛɪ ᴋɪᴍ ?','ʜɪᴄ̧ sıʀғ ғᴀʏᴅᴀ sᴀɢ̆ʟᴀᴅıɢ̆ı ɪᴄ̧ɪɴ ʙɪʀɪʏʟᴇ ᴀʀᴋᴀᴅᴀş ᴋᴀʟᴅıɢ̆ıɴ ᴏʟᴅᴜ ᴍᴜ?','ᴇɴ ᴛᴜʜᴀғ ᴋᴏʀᴋᴜɴᴜᴢ ɴᴇᴅɪʀ?','ᴋᴜʀᴛ ᴏʏᴜɴᴜɴᴜ sᴇᴠɪʏᴏʀ ᴍᴜsᴜɴ?','ᴇɴ sᴏɴ ɴᴇ ᴢᴀᴍᴀɴ ᴅɪşʟᴇʀɪɴɪ ғıʀᴄ̧ᴀʟᴀᴅıɴ?','ʜɪᴄ̧ ʏᴀşıɴ ʜᴀᴋᴋıɴᴅᴀ ʏᴀʟᴀɴ sᴏ̈ʏʟᴇᴅɪɴ ᴍɪ?','ɢʀᴜᴘᴛᴀ ᴋᴇşᴋᴇ ᴀʙɪᴍ/ᴀʙʟᴀᴍ ᴏʟsᴀʏᴅı ᴅᴇᴅɪɢ̆ɪɴ ᴋɪᴍsᴇ ᴠᴀʀ ᴍı ?','ʙɪʀ ʙᴏ̈ᴄᴇᴋ ɪsᴛɪʟᴀsı ɢᴇʀᴄ̧ᴇᴋʟᴇşsᴇ ʜᴀɴɢɪ ᴀʀᴋᴀᴅᴀşıɴ ʜᴀʏᴀᴛᴛᴀ ᴋᴀʟᴍᴀʏı ʙᴀşᴀʀıʀ?','ɢʀᴜᴘᴛᴀ ᴏʟᴍᴀᴍᴀsıɴı ɪsᴛᴇᴅɪɢ̆ɪɴ ᴋɪşɪʏɪ ᴇᴛɪᴋᴇᴛʟᴇʀ ᴍɪsɪɴ?','ʙᴜ ʜᴀʏᴀᴛᴛᴀ sᴇɴɪ ᴇɴ ᴄ̧ᴏᴋ ᴋıᴢᴅıʀᴀɴ şᴇʏ ɴᴇᴅɪʀ?',
'ᴇɴ ɪʏɪ ᴀʀᴋᴀᴅᴀşıɴıɴ sᴇɴɪɴʟᴇ ᴀʏɴı ᴜ̈ɴɪᴠᴇʀsɪᴛᴇʏᴇ ɢɪᴛᴍᴇsɪɴɪ ɪsᴛᴇʀ ᴍɪsɪɴ?','ᴇʀᴋᴇᴋ ᴀʀᴋᴀᴅᴀşıɴ ᴠᴇʏᴀ ᴋıᴢ ᴀʀᴋᴀᴅᴀşıɴ sᴇɴɪ ʜɪᴄ̧ ᴜᴛᴀɴᴅıʀᴅı ᴍı?','ɢʀᴜʙᴜ ɢᴇʀᴄ̧ᴇᴋᴛᴇɴ sᴇᴠɪʏᴏʀ ᴍᴜsᴜɴ?','ʙɪʀ ᴏᴅᴀᴅᴀ ᴜᴢᴜɴ ʙɪʀ sᴜ̈ʀᴇ ʜᴀᴘsᴏʟᴀᴄᴀɢ̆ıɴı ᴅᴜ̈şᴜ̈ɴsᴇɴ ʏᴀɴıɴᴅᴀ ᴏʟᴍᴀsıɴı ɪsᴛᴇᴅɪɢ̆ɪɴ ᴜ̈ᴄ̧ şᴇʏ ɴᴇ ᴏʟᴜʀᴅᴜ?','ʜᴀᴛıʀʟᴀᴅıɢ̆ıɴ ᴋᴀᴅᴀʀıʏʟᴀ ɪʟᴋ ᴀşıᴋ ᴏʟᴅᴜɢ̆ᴜɴ ᴜ̈ɴʟᴜ̈ ᴋɪᴍᴅɪ?','sᴏ̈ʏʟᴇᴅɪɢ̆ɪɴɪᴢ ᴠᴇʏᴀ ʏᴀᴘᴛıɢ̆ıɴıᴢ ʙɪʀ şᴇʏɪ sɪʟᴍᴇᴋ ɪᴄ̧ɪɴ ᴢᴀᴍᴀɴᴅᴀ ɢᴇʀɪʏᴇ ɢɪᴅᴇʙɪʟsᴇʏᴅɪɴɪᴢ, ʙᴜ ʜᴀɴɢɪ ʏıʟ ᴏʟᴜʀᴅᴜ?','ʙᴜ ɢʀᴜᴘᴅᴀᴋɪ sıʀ ᴛᴜᴛᴍᴀ  ᴋᴏɴᴜsᴜɴᴅᴀ ᴇɴ ᴄ̧ᴏᴋ ᴢᴏʀʟᴀɴᴀɴ ᴋɪşɪ ᴋɪᴍᴅɪʀ?','sᴇɴ ᴀᴅᴍɪɴ ᴏʟsᴀɴ ɴᴇʏɪ ᴅᴇɢ̆ɪşᴛɪʀɪʀᴅɪɴ ?','ɪ̇ʟᴋ ɪşɪɴ ɴᴇʏᴅɪ?','ɢʀᴜʙᴜ ɢᴇʀᴄ̧ᴇᴋᴛᴇɴ sᴇᴠɪʏᴏʀ ᴍᴜsᴜɴ?','ɢʀᴜᴘᴛᴀ ʜᴏşʟᴀɴᴅıɢ̆ıɴ ʙɪʀɪ ᴠᴀʀ ᴍı ?',
'ᴀɪʟᴇɴɪᴢɪɴ ᴜʏɢᴜʟᴀᴅıɢ̆ı ᴇɴ ᴛᴜʜᴀғ ɢᴇʟᴇɴᴇᴋ ɴᴇᴅɪʀ?','ʙɪʀ ʙᴏ̈ᴄᴇᴋ ɪsᴛɪʟᴀsı ɢᴇʀᴄ̧ᴇᴋʟᴇşsᴇ ʜᴀɴɢɪ ᴀʀᴋᴀᴅᴀşıɴ ʜᴀʏᴀᴛᴛᴀ ᴋᴀʟᴍᴀʏı ʙᴀşᴀʀıʀ?','ʙɪʀ ᴏᴅᴀᴅᴀ ᴜᴢᴜɴ ʙɪʀ sᴜ̈ʀᴇ ʜᴀᴘsᴏʟᴀᴄᴀɢ̆ıɴı ᴅᴜ̈şᴜ̈ɴsᴇɴ ʏᴀɴıɴᴅᴀ ᴏʟᴍᴀsıɴı ɪsᴛᴇᴅɪɢ̆ɪɴ ᴜ̈ᴄ̧ şᴇʏ ɴᴇ ᴏʟᴜʀᴅᴜ?','ʜᴀɴɢɪ ᴄ̧ᴏᴄᴜᴋ ғɪʟᴍɪɴɪ ᴛᴇᴋʀᴀʀ ᴛᴇᴋʀᴀʀ ɪᴢʟᴇʏᴇʙɪʟɪʀsɪɴ?','ʙᴜ ʜᴀʏᴀᴛᴛᴀᴋɪ ᴇɴ ʙᴜ̈ʏᴜ̈ᴋ ɢᴜ̈ᴠᴇɴsɪᴢʟɪɢ̆ɪɴ ɴᴇᴅɪʀ?','ʙɪʀ ᴜ̈ɴʟᴜ̈ ɪɴsᴛᴀɢʀᴀᴍ’ᴅᴀ sᴇɴɪ ᴛᴀᴋɪᴘ ᴇᴛsᴇʏᴅɪ ʙᴜ ᴜ̈ɴʟᴜ̈ɴᴜ̈ɴ ᴋɪᴍ ᴏʟᴍᴀsıɴı ɪsᴛᴇʀᴅɪɴ?','ʜɪᴄ̧ sıʀғ ғᴀʏᴅᴀ sᴀɢ̆ʟᴀᴅıɢ̆ı ɪᴄ̧ɪɴ ʙɪʀɪʏʟᴇ ᴀʀᴋᴀᴅᴀş ᴋᴀʟᴅıɢ̆ıɴ ᴏʟᴅᴜ ᴍᴜ?','ᴜɴɪᴄᴏʀᴜɴ ᴍᴜ ᴏʟᴍᴀsıɴı ɪsᴛᴇʀᴅɪɴ ᴇᴊᴅᴇʀʜᴀɴ ᴍı?','ɢʀᴜᴘᴛᴀ ᴀᴅᴍɪɴ ᴏʟsᴀɴ ᴋɪᴍɪ ʙᴀɴʟᴀʀᴅıɴ ɴᴇᴅᴇɴ ?','ɪ̇ɴsᴀɴʟᴀʀıɴ sᴇɴɪɴ ʜᴀᴋᴋıɴᴅᴀ ʙɪʟᴍᴇsɪɴɪ ɪsᴛᴇᴅɪɢ̆ɪɴ şᴇʏ ɴᴇᴅɪʀ?',
'ɢʀᴜᴘᴛᴀ ᴋɪᴍᴅᴇɴ ɢıᴄıᴋ ᴀʟıʏᴏʀsᴜɴ?','ᴍᴇᴠᴄᴜᴛ ᴇʀᴋᴇᴋ ᴀʀᴋᴀᴅᴀşıɴıɴ ʏᴀ ᴅᴀ ᴋıᴢ ᴀʀᴋᴀᴅᴀşıɴıɴ sᴇɴɪɴʟᴇ ᴀʏɴı ᴜ̈ɴɪᴠᴇʀsɪᴛᴇʏᴇ ɢɪᴛᴍᴇsɪɴɪ ɪsᴛᴇʀ ᴍɪsɪɴ?','ɢʀᴜᴘᴛᴀ ʜᴏşʟᴀɴᴅıɢ̆ıɴ ʙɪʀɪ ᴠᴀʀ ᴍı ?','ᴡᴇʙ ɢᴇᴄ̧ᴍɪşɪɴɪᴢɪ, ʙɪʀɪʟᴇʀɪ ɢᴏ̈ʀᴜ̈ʀsᴇ ᴜᴛᴀɴᴀᴄᴀɢ̆ıɴıᴢ şᴇʏ ɴᴇ ᴏʟᴜʀᴅᴜ?','ɢʀᴜᴘᴛᴀ ᴋᴇşᴋᴇ ᴀʙɪᴍ/ᴀʙʟᴀᴍ ᴏʟsᴀʏᴅı ᴅᴇᴅɪɢ̆ɪɴ ᴋɪᴍsᴇ ᴠᴀʀ ᴍı ?','ᴜʏᴋᴜɴᴅᴀ ᴋᴏɴᴜşᴜʀ ᴍᴜsᴜɴ?','sıɴıғᴛᴀ ʜɪᴄ̧ ᴜʏᴜʏᴀ ᴋᴀʟᴅıɴ ᴍı?','ᴋɪᴍsᴇɴɪɴ sᴇɴɪɴ ʜᴀᴋᴋıɴᴅᴀ ʙɪʟᴍᴇᴅɪɢ̆ɪ ʙɪʀ şᴇʏ ɴᴇᴅɪʀ?','ɪʟᴇʀᴅᴇ ᴄ̧ᴏᴄᴜɢ̆ᴜɴ ᴏʟᴜʀsᴀ ɴᴇ ɪsɪᴍ ᴋᴏʏᴍᴀᴋ ɪsᴛᴇʀsɪɴ?','sᴜ̈ᴘᴇʀ ᴋᴀʜʀᴀᴍᴀɴʟᴀʀ ɢᴇʀᴄ̧ᴇᴋᴛᴇɴ ᴠᴀʀ ᴏʟsᴀʏᴅı ᴅᴜ̈ɴʏᴀ ɴᴀsıʟ ʙɪʀ ʏᴇʀ ᴏʟᴜʀᴅᴜ?','ɢʀᴜᴘᴛᴀ ᴋɪᴍɪɴ ʜᴇsᴀʙıɴᴀ ɢɪʀᴍᴇᴋ ɪsᴛᴇʀsɪɴ?','ɢɪʀᴅɪɢ̆ɪɴɪᴢ ᴇɴ sᴀᴄ̧ᴍᴀ ᴛᴀʀᴛışᴍᴀ ɴᴇᴅɪʀ?','ɢʀᴜᴘᴛᴀ ɴᴇғʀᴇᴛ ᴇᴛᴛɪɢ̆ɪɴ ʙɪʀɪ ᴠᴀʀ ᴍı?',
'ᴛᴀᴍ ᴀɴʟᴀᴍıʏʟᴀ ᴇɴ sᴏɴ ɴᴇ ᴢᴀᴍᴀɴ ʏᴀʟᴀɴ sᴏ̈ʏʟᴇᴅɪɴ?','ʜɪᴄ̧ sᴇᴠɢɪʟɪɴɪ ᴀʟᴅᴀᴛᴍᴀʏı ᴅᴜ̈şᴜ̈ɴᴅᴜ̈ɴ ᴍᴜ̈?','ᴇɴ sᴇᴠᴅɪɢ̆ɪɴ ᴘɪᴊᴀᴍᴀʟᴀʀ ɴᴇʏᴇ ʙᴇɴᴢɪʏᴏʀ?','ʜᴀᴋᴋıɴᴅᴀ ʏᴀʟᴀɴ sᴏ̈ʏʟᴇᴅɪɢ̆ɪɴ ᴇɴ ᴋᴏ̈ᴛᴜ̈ şᴇʏ ɴᴇᴅɪʀ?','ᴇɴ ᴋᴏ̈ᴛᴜ̈ ᴀʟışᴋᴀɴʟıɢ̆ıɴıᴢ ɴᴇᴅɪʀ?','ʙᴜ ʜᴀʏᴀᴛᴛᴀᴋɪ ᴇɴ ʙᴜ̈ʏᴜ̈ᴋ ɢᴜ̈ᴠᴇɴsɪᴢʟɪɢ̆ɪɴ ɴᴇᴅɪʀ?','ʜɪᴄ̧ ᴋɪᴍsᴇʏɪ ᴏ̈ᴢᴇʟᴅᴇɴ ʀᴀʜᴀᴛsıᴢ ᴇᴛᴛɪɴ ᴍɪ?','sᴇᴠᴍᴇᴅɪɢ̆ɪɴ ᴋᴏ̈ᴛᴜ̈ ʜᴜʏᴜɴ ᴠᴀʀ ᴍı?','sᴀᴄ̧ʟᴀʀıɴı ᴜᴢᴀᴛᴍᴀʏı ᴅᴜ̈şᴜ̈ɴsᴇɴ ɴᴇ ᴋᴀᴅᴀʀ ᴜᴢᴀᴛıʀᴅıɴ?','ʜᴀʏᴀʟɪɴᴅᴇᴋɪ ɪş ɴᴇ?','ʜɪᴄ̧ ᴍᴀsᴀɴıɴ ᴀʟᴛıɴᴀ sᴀᴋıᴢ ᴀᴛᴛıɴ ᴍı?','ʏᴇʀᴅᴇɴ ʙɪʀ şᴇʏɪ ᴀʟıᴘ ʜɪᴄ̧ ʏᴇᴅɪɴ ᴍɪ?','ɢʀᴜʙᴜɴ ᴋʀᴀʟı ᴋɪᴍ?','ᴋᴜʀᴛ ᴏʏᴜɴᴜɴᴜ sᴇᴠɪʏᴏʀ ᴍᴜsᴜɴ?sᴘᴏʀ ʏᴀᴘᴀʀ ᴍısıɴ?','ɢʀᴜᴘᴛᴀ ᴀɢ̆ᴢıɴı ʙᴜʀɴᴜɴᴜ ᴋıʀᴀʀıᴍ ᴅᴇᴅɪɢ̆ɪɴ ᴋɪᴍsᴇ ᴠᴀʀ ᴍı ?','ɢʀᴜᴘᴛᴀᴋɪ ᴇɴ sᴇᴠɢɪɢ̆ɪɴ ᴀᴅᴍɪɴ ᴋɪᴍ ?',
'ᴅɪʀsᴇɢ̆ɪɴɪ ʏᴀʟᴀʏᴀʙɪʟɪʀ ᴍɪsɪɴ?','ᴍᴇssɪ ᴍɪ ʀᴏɴᴀʟᴅᴏ ᴍᴜ?','şɪᴍᴅɪʏᴇ ᴋᴀᴅᴀʀ ɢᴏ̈ʀᴅᴜ̈ɢ̆ᴜ̈ᴍ ᴇɴ ɢᴀʀɪᴘ ʀᴜ̈ʏᴀʏı ᴀɴʟᴀᴛ.','ʙᴜ ʏıʟ ʜᴀʏᴀᴛıɴᴅᴀ ɴᴇʏɪ ᴅᴇɢ̆ɪşᴍᴇʏɪ ᴜʏɢᴜɴ ɢᴏ̈ʀᴜ̈ʏᴏʀsᴜɴ?','ᴇɴ sᴏɴ ɴᴇ ᴢᴀᴍᴀɴ ʜᴜ̈ɴɢᴜ̈ʀ ʜᴜ̈ɴɢᴜ̈ʀ ᴀɢ̆ʟᴀᴅıɢ̆ıɴı ʜᴀᴛıʀʟıʏᴏʀ ᴍᴜsᴜɴ?','şɪᴍᴅɪʏᴇ ᴋᴀᴅᴀʀ ʜɪᴄ̧ ᴀʀᴀʟıᴋsıᴢ 𝟷𝟸 sᴀᴀᴛᴛᴇɴ ғᴀᴢʟᴀ ᴜʏᴜᴅᴜɢ̆ᴜɴ ᴏʟᴅᴜ ᴍᴜ?','ᴛᴇʟᴇғᴏɴᴅᴀ ᴀʀᴀᴅıɢ̆ıɴ sᴏɴ şᴇʏ ɴᴇʏᴅɪ?','ʙᴜ ʜᴀʏᴀᴛᴛᴀ şɪᴍᴅɪʏᴇ ᴋᴀᴅᴀʀ ʏᴀᴘᴛıɢ̆ıɴ ᴇɴ ʙᴜ̈ʏᴜ̈ᴋ ʜᴀᴛᴀ ɴᴇᴅɪʀ?','ɢʀᴜʙᴜɴ ᴇɴ ᴇɢᴏɪsᴛɪ ᴋɪᴍ ?','ʜɪᴄ̧ ʏᴀsᴀʏᴀ ᴀʏᴋıʀı ʙɪʀ şᴇʏʟᴇʀ ʏᴀᴘᴛıɢ̆ıɴ ᴏʟᴅᴜ ᴍᴜ?','ᴀᴋʀᴀʙᴀʟᴀʀıɴᴅᴀɴ ᴋɪᴍsᴇʏɪ ᴅᴀᴠᴇᴛ ᴇᴛᴛɪɴ ᴍɪ ɢʀᴜʙᴀ ?','ɢʀᴜʙᴜ ɴᴇ ᴋᴀᴅᴀʀ sᴇᴠɪʏᴏʀsᴜɴ?','ɢʀᴜᴘᴛᴀɴ ᴜᴢᴀᴋ ᴋᴀᴄ̧ ᴅᴀᴋɪᴋᴀ ᴅᴜʀᴀʙɪʟɪʀsɪɴ ?','sᴏ̈ʏʟᴇᴅɪɢ̆ɪɴ ᴇɴ sᴏɴ ʏᴀʟᴀɴ ɴᴇʏᴅɪ?','ᴄ̧ᴇşɪᴛʟɪ ʙᴀᴛıʟ ɪɴᴀɴᴄ̧ʟᴀʀıɴ ᴠᴀʀ ᴍı, ᴠᴀʀsᴀ ᴏɴʟᴀʀ ɴᴇʟᴇʀ?',
'ʙɪʀ sıɴᴀᴠᴅᴀɴ ᴀʟᴅıɢ̆ıɴ ᴇɴ ᴋᴏ̈ᴛᴜ̈ ᴘᴜᴀɴ ɴᴇʏᴅɪ?','ʙɪʀ sıɴᴀᴠᴅᴀɴ ᴀʟᴅıɢ̆ıɴ ᴇɴ ᴋᴏ̈ᴛᴜ̈ ᴘᴜᴀɴ ɴᴇʏᴅɪ?','ʜᴀғᴛᴀᴅᴀ ᴋᴀᴄ̧ ᴋᴇᴢ ᴀʏɴı ᴘᴀɴᴛᴏʟᴏɴᴜ ɢɪʏɪʏᴏʀsᴜɴ?',
)
