from config import *

smesajs = ["Hoş Geldin 💕", "Nasılsın 😌", "Seni Özledim 💕", "Nerdesin sen 🙄", "Gel oyun oynayalım ✨", "Şarkı dinleyelim mi 🤭",]
bottst = ["Bana mı dedin bot diye ?", "Ben bot değilim bi kere 🙄", "Bi daha bot dersen 🤬", "Hala bot diyor ya 😡", "Adamı hasta edersin 🙄", "Olm dayak yersin ama 😬",]
bkt = ["He canım ✨", "He aşkım 💕", "Duygularım darmadağın !", "Efendim tatlım 💞", "Bana mı seslendin 🙄", "Yaw ne ne aaaa", "Seni dinliyorum gülüm 🥰", "Al sana harçlık 💰", "Başımın etini yedin 🙄", "Seni tokatlarım 😏", "Buyrun benim ?", "Offff 🙄", "Vay arkadaş bu çocuk abayı yakmış 😅", "Sus artik Sus !", "Dost elinden yaralıyam 😔", "Kırık kalbimi onarır mısın ?", "Seni seviyorum bitanem 💕", "Gel seni öpim 😘", "Dile benden ne dilersen", "Benim başım ağrıyor 🥺", "Yar beni sevmez !", "Şarkı söyleyelim mi ✨", "Efendim hocam ?",]
selam = ["ve aleyküm selam hoş geldin yahu", "Aleyküm Selam Naber 🎉", "Selam Hoş Geldin", "Ase, Hoş Geldin 💕",]
nasilsin = ["Senle iyi, Sen ?", "İyiyim senden naber", "İyiyim sen", "İyim fıstık, ya sen 💕", "Teşekkür ederim iyiyim sen nasılsın", "Tıpkı senin gibi mükemmelim 🥳",]
adam = ["Mermiler seksin, alemde teksin 😏", "Mermiler seksin, tokatımı yersin 😏",]
iyiyim = ["İyi olmana sevindim", "Hep daha iyi olman dileğiyle  ", "Keşke bende senin kadar iyi olsam 😏",]
hoş = ["Naber", "Hoş buldum nabıyon", "Nasılsın",]
merhaba = ["Merhaba, Hoş geldin", "Merhabalar Hoş geldiniz efem 🥳", "Merhaba, nerelerdesin ya sen", "yine özlettin kendini 😏",]
ban = ["İmdatttt, grup boşalıyor 😱", "Grupta üye kalmadı mübarek 🙄", "Ayıp ettin !", "Bak sen 🤔", "Adamın dibisin sen :)", "Grub boşalıyor yetişin .",]
nabiyon = ["Oturuyorum, sen", "Gördüğün gibi takılıyoruz", "Yapacak bişey yok", "Ne yapmamı istersin",]
uzgun = ["Kıyamam ki ben sana 😢", "Üzülme, buda geçer 😔", "Bizi üzenler utansın 😏", "Hoppala, kim üzdü seni",]
valla = ["tamam, tamam inandım 🥴", "de valla", "Deme öyle Allah çarpar", "Sus çarpılırsin .",]
sg = ["Küfür etme turşu !", "Lütfen düzgün konuş 😏", "Dayanamıyacam ben artık ama ...", "Ben buna dalarım ama ...",]
mal = ["Akıllı görünce kıskandı 😏", "Sana özeniyorum, galiba başarıyorum 🙈", "Beni birine benzettin galiba 🙄", "Hop, orda dur beni daha fazla sinirlendirmeyin lütfen ...",]
balim = ["Arı mısın gülüm 🙈", "Canın çektiyse yiyebilirsin beni 😋", "Efendim, hayatım .", "Şımarıyorum ama 🙈",]
canim = ["Gülüm 💕", "Bebeğim 💕", "Bitanem 💕", "Hayatım 💕", "Turşu suratlım 💕",]
gidiyorum = ["Nereye, Karpuz Kesmiştik .", "Hoşuma yeterince gittin, otur oturduğun yerde 🤫", "Görüşürüz, Hakkını helal et ...", "Kal desem kalır mı acaba 🤔",]
sinirlendim = ["Farkettim .", "Sakin ol, Şampiyon .", "Bakıyorum da Domates gibi kızardın .", "Ne yapayım .",]
tanis = ["Olur tanışalım .", "Kim olduğunu biliyorum :)", "Kendini tanıt !", "Düşünmem gerek 🤔",]
adne = ["Buket, ya senin ?", "Sen söylersen bende söylerim 😏", "Söylemem, banane .", "Ben de Buket memnun oldum ❣️",]
iyisen = ["Bende iyiyim teşekürler .", "Senin gibi iyi olamıyorum 😔", "Birazcık kötüyüm .", "Mükemmelim tıpkı senin gibi 🤭",]
gullu = ["Ne gülüyon?", "Açıkta bişey mi gördün .", "Bakıyorum da keyfin yerinde .", "Mutlu olmana sevindim 💕",]
buyuk = ["Senden Büyük Allah var 😎", "Yalan söyleme .", "Hayır, Küçük ✓",]
aiko = ["Buyrun, Asistanı olurum ?", "Aiko kadar başına taş düşsün emi .", "Öldü artık yok 🙄",] 
gnyy = ["Günaydın, naber", "Günüm aydı, hoş geldin 🎉", "Günaydın, tatlım .", "Güneşim doğdu, hoş geldin 🥳",]
igece = ["Tatlı rüyalar 🎉", "İyi geceler, görüşürüz .", "Gecen güzel geçsin kalbi güzel insan .", "Bir günün daha sonuna geldik, iyi geceler .",]
kyas = ["Yaşın bi önemi var mı ?", "Tahmin et kaç yaşındayım .", "Senden büyük olduğum kessin .",]
nereli = ["Dünyalı, ya sen", "Ben bir yerli değilim 😔", "Galiba Dünyanın bir yerindenim .",]
pms = ["Susmasam ne olur 😳", "Lan sus 🙄", "Sen konuşma 🤭", "Hayır, Konuşacam 🙄",]
krdn = ["Ya kıyamam 😔", "Gel sarılalım .", "Oh iyi oldu .",]
skdm = ["Bende, ne yapalım ?", "Benden sıkıldın mı ?", "Hadi uyuyalım .", "Oyun oynayalım mı ?",]
hms = ["hmmmm 🙄", "Yeter ama aaaa 🙄", "Kafana sıkarım senin 🙄",]
bts = ["Sağolun 😔", "Eyvallah Ciğerim .",]
trt = ["Oyun mu istiyorsun /turet yaz .", "/d mi /c mi !", "aaaa oyun oynamayı unuttuk 😬 derhal /sayi yaz .",]
evt = ["Bi sus ya", "Hayır", "Hayır ulan hayır !", "yioooooooo",]
hyrr = ["la havle vela kuvvete", "Ne demek hayır 🙄", "Evet ...", "Evet ulan evet !",]
gzs = ["Gözler ömre bedel 😂", "Yukarıda ne var 🤔", "Tahtalı köyü mü arıyon mübarek 😲",]
ofs = ["pffffff", "of deme oh de 🤪", "Bakıyorum da oflamaya başladın 🙄",]
cklta = ["Aaaaa çok severim 💕", "Bana Çikolata Alsana 🥺", "Çikolatam olur musun 😋",]
lna = ["Lan mı, memleket bize Ana diyor 🙄", "Ne var lan 🙄", "Bana mı dedin 😠", "Lannnnn sus 🙄",]
dddm = ["Duymadım 😜", "Ne dedin ?", "Anlamadım ?", "Neden öyle dedin ?",]
ylna = ["Yalan söyleyen kim 🙄", "Yalan konuşmayın çarparım 🙄", "Terbiyesiz 😠",]
sgll = ["Sende sağol 💕", "Başımız sağolsun .",]
crkn = ["Kimmiş çirkin olan 🙄", "Ben çok güzelim 🙈", "Sus artık 🙄",]
dmy = ["Banın hayırlı olsun 🙄", "Şşşş, yasak ...", "Seni döverim bak 🙄",]
tymm = ["Midemden tuhaf bir ses geliyor 😸", "Galiba acıktım 😋", "Olsa da yesek 🥺",]
kmm= ["Olm sinirleniyorum ama 😬", "Bana bak 🙄", "Seni yollarım 😁", "Acımam ama 😁", "Sen şimdi hapı yuttun 😳",]
kankas = ["Efendim canım 💕", "Kanka diyen ağzını 😁", "Bana mı dedin lan 😳", "Bi daha dersen, fena olur 🙄",]
opsss = ["Muahhhhhhh 😘", "Utandırma beni 🤭", "Yanaş bakim 😲",]
sgne = ["Nasıl sanane 🙄", "Asıl sanane 😏", "Seni alakadar etmez 😏",]
bgne = ["Yok öyle yama 😏", "Asıl banane 😏", "Şşşş bidaha duymim 🙄",]
bnen = ["Hayır ben !", "Yok öyle yama !", "Ben ulan ben 🙄",]
snen = ["Evet ben !", "Eeeee...", "Hayır sen !",]

itirafmsg = "**➻ İtirafınızı nasıl paylaşmak istersiniz 🤔**"
itirafyaz = "**🎉 İşte bir itiraf yaz !\n\n🎂 Daha sonra herkese açık mı yoksa gizli mi olacağını soracağım. 😍**"
gonderildi = f"**✅ İtirafınız gönderildi ve yöneticiler tarafından onaylandıktan sonra @{İTİRAF_CHANNELL} kanalında paylaşılacaktır !**"

ibaslama = "🎂 __**ᴇᴛɪ̇ᴋᴇᴛʟᴇᴍᴇʏᴇ ʙᴀşʟɪʏᴏʀᴜᴍ ʙᴇʙᴇɢ̆ɪ̇ᴍ !**__"
nogroup = "🔹 __**ʙᴜ ᴋᴏᴍᴜᴛᴜ ɢʀᴜᴘʟᴀʀᴅᴀ ᴋᴜʟʟᴀɴ !**__"
noadmin = "😏 __**ʏᴏ̈ɴᴇᴛɪ̇ᴄɪ̇ ᴅᴇɢ̆ɪ̇ʟsɪ̇ɴ ʙᴇʙᴇɢ̆ɪ̇ᴍ !**__"
botnoadmin = "😡 **__ʙᴇɴɪ̇ ʏᴏ̈ɴᴇᴛɪ̇ᴄɪ̇ ʏᴀᴘɪɴ ʟᴀɴ !__**"

emj = " ❤️ 🧡 💛 💚 💙 💜 🖤 🤍 🤎 🙂 🙃 😉 😌 😍 🥰 😘 😗 😙 😚 😋 😛 😝 😜 🤪 🤨 🧐 🤓 😎 🤩 🥳 😏 😒 " \
        "😞 😔 😟 😕 🙁 😣 😖 😫 😩 🥺 😢 😭 😤 😠 😡 🤯 😳 🥵 🥶 😱 😨 😰 😥 😓 🤗 🤔 🤭 🤫 🤥 😶 😐 😑 😬 🙄 " \
        "😯 😦 😧 😮 😲 🥱 😴 🤤 😪 😵 🤐 🥴 🤢 🤮 🤧 😷 🤒 🤕 🤑 🤠 😈 👿 👹 👺 🤡  👻 💀 👽 👾 🤖 🎃 😺 😸 😹 " \
        "😻 😼 😽 🙀 😿 😾 ❄️ 🌺 🌨 🌩 ⛈ 🌧 ☁️ ☀️ 🌈 🌪 ✨ 🌟 ☃️ 🪐 🌏 🌙 🌔 🌚 🌝 🕊 🦩 🦦 🌱 🌿 ☘ 🍂 🌹 🥀 🌾 " \
        "🌦 🍃 🎋".split(" ")

rutbe = (
"ᴇᴍɴɪʏᴇᴛ ᴍᴜ̈ᴅᴜ̈ʀᴜ̈", "ᴇᴍɴɪʏᴇᴛ ᴀᴍɪʀɪ", "ʙᴀşᴋᴏᴍɪsᴇʀ", "ᴋᴏᴍɪsᴇʀ", "ᴏʀɢᴇɴᴇʀᴀʟ", "ᴋᴜʀᴍᴀʏ", "ᴘɪʏᴀᴅᴇ", "sᴜ̈ᴠᴀʀɪ", "ᴛᴀɴᴋᴄ̧ɪ", "ᴛᴏᴘᴄ̧ᴜ", "ᴋᴏʀɢᴇɴᴇʀᴀʟ", "ᴛᴜ̈ᴍɢᴇɴᴇʀᴀʟ", "ᴛᴜɢ̆ɢᴇɴᴇʀᴀʟ",
"ᴀʟʙᴀʏ", "ʏᴀʀʙᴀʏ", "ʙɪɴʙᴀşɪ", "ʏᴜ̈ᴢʙᴀşɪ", "ᴜ̈sᴛᴇɢ̆ᴍᴇɴ", "ᴛᴇɢ̆ᴍᴇɴ", "ᴀsᴛᴇɢ̆ᴍᴇɴ", "ᴀsᴛsᴜʙᴀʏ", "ᴀsᴛsᴜʙᴀʏ ᴜ̈sᴛᴄ̧ᴀᴠᴜş", "ᴀsᴛsᴜʙᴀʏ ᴄ̧ᴀᴠᴜş", "ᴜᴢᴍᴀɴ ᴄ̧ᴀᴠᴜş", "ᴜᴢᴍᴀɴ ᴏɴʙᴀşɪ", "ᴄ̧ᴀᴠᴜş", "ᴏɴʙᴀşɪ",
)

gsos = (
"ʙᴀʟʟɪ ʟᴏᴋᴍᴀᴍ 🍯", "ᴋᴀʏᴍᴀɢ‌ɪᴍ 🎂", "sᴜ‌ᴛʟᴜ‌ ᴄ‌ᴏ‌ʀᴇɢ‌ɪ‌ᴍ 🍩", "ʙᴀʟ ᴋᴀʙᴀɢ‌ɪᴍ 🎃", "ᴄᴀɴ ᴅᴏsᴛᴜᴍ 💕", "ʙɪ‌ʀ ᴛᴀɴᴇᴍ ❤️‍🔥", "ʙᴏ‌ʙʀᴇɢ‌ɪ‌ᴍ 🫀", "ᴋᴀs‌ᴀʀʟɪ ᴛᴏsᴛᴜᴍ 🥪", "ᴀʏɪᴄɪɢ‌ɪᴍ 🧸", "ᴛᴀᴛʟɪ ᴀʏɪᴄɪᴋ 🐻",
"ɢᴜ‌ᴢᴇʟɪ‌ᴍ 💅🏻", "ʏᴀʀɪ‌ᴍ 🌹", "ᴅᴜ‌ɴʏᴀᴍ 🌍", "ᴍᴜᴛʟᴜʟᴜᴋ ᴋᴀʏɴᴀɢ‌ɪᴍ 🌸", "ᴍᴇʟᴏᴅɪ‌ᴍ 🫧", "ᴄᴀɴ ᴅᴏsᴛᴜᴍ 🌈", "ᴊᴇʟɪ‌ʙᴏɴᴜᴍ 🌥", "ʜᴀʀɪ‌ʙᴏᴍ 🫖", "ᴅᴏsᴛᴜᴍ 👻", "ᴋᴜᴢᴜᴍ 🐑", "s‌ᴇᴋᴇʀᴘᴀʀᴇᴍ 🍭", "ᴇɴᴇʀᴊɪ ᴋᴀʏɴᴀɢ‌ɪᴍ🌟",
"ᴋʀᴇᴍᴀʟɪ ᴅᴏɴᴅᴜʀᴍᴀᴍ 🍨", "ᴋʀᴇᴍᴀʟɪ ᴋᴇᴋɪ‌ᴍ 🍰",
)

guzelsoz = (
'ᴜsʟᴜᴘ ᴋᴀʀᴀᴋᴛᴇʀɪᴅɪʀ ʙɪʀ ɪɴsᴀɴɪɴ ...','ɪʏɪʏɪᴍ ᴅᴇsᴇᴍ ɪɴᴀɴᴀᴄᴀᴋ , ᴏ ᴋᴀᴅᴀʀ ʜᴀʙᴇʀsɪᴢ ʙᴇɴᴅᴇɴ ...','ᴍᴇsᴀғᴇʟᴇʀ ᴜᴍʀᴜᴍᴅᴀ ᴅᴇɢɪʟ , ɪᴄɪᴍᴅᴇ ᴇɴ ɢᴜᴢᴇʟ ʏᴇʀᴅᴇsɪɴ ...','ʙɪʀ ᴍᴜᴄɪᴢᴇʏᴇ ɪʜᴛɪʏᴀᴄɪᴍ ᴠᴀʀᴅɪ , ʜᴀʏᴀᴛ sᴇɴɪ ᴋᴀʀsɪᴍᴀ ᴄɪᴋᴀʀᴅɪ ...', 'ᴏʏʟᴇ ɢᴜᴢᴇʟ ʙᴀᴋᴛɪɴ ᴋɪ , ᴋᴀʟʙɪɴ ᴅᴇ ɢᴜʟᴜsᴜɴ ᴋᴀᴅᴀʀ ɢᴜᴢᴇʟ sᴀɴᴍɪsᴛɪᴍ ...','ʜᴀʏᴀᴛ ɴᴇ ɢɪᴅᴇɴɪ ɢᴇʀɪ ɢᴇᴛɪʀɪʀ , ɴᴇ ᴅᴇ ᴋᴀʏʙᴇᴛᴛɪɢɪɴ ᴢᴀᴍᴀɴɪ ɢᴇʀɪ ɢᴇᴛɪʀɪʀ ...','sᴇᴠᴍᴇᴋ ɪᴄɪɴ sᴇʙᴇᴘ ᴀʀᴀᴍᴀᴅɪᴍ , ʙɪʀ ᴛᴇᴋ sᴇsɪ ʏᴇᴛᴛɪ ᴋᴀʟʙɪᴍᴇ ...', 
'ᴍᴜᴛʟᴜʏᴜɴ ᴀᴍᴀ sᴀᴅᴇᴄᴇ sᴇɴɪɴʟᴇ ...','ʙᴇɴ ʜᴇᴘ sᴇᴠɪʟᴍᴇᴋ ɪsᴛᴇᴅɪɢɪᴍ ɢɪʙɪ sᴇᴠɪɴᴅɪᴍ ...', 'ʙɪʀɪ ᴠᴀʀ ɴᴇ ᴏᴢʟᴇᴍᴇᴋᴛᴇɴ ʏᴏʀᴜʟᴅᴜᴍ ɴᴇ sᴇᴠᴍᴇᴋᴛᴇɴ ...', 'ᴄᴏᴋ ᴢᴏʀ ʙᴇ sᴇɴɪ sᴇᴠᴍᴇʏᴇɴ ʙɪʀɪɴᴇ ᴀsɪᴋ ᴏʟᴍᴀᴋ ...','ɴᴇ ᴋᴀᴅᴀʀ ʏᴀŞᴀᴅɪĞɪᴍɪᴢ ᴅᴇĞɪʟ, ɴᴀꜱɪʟ ʏᴀŞᴀᴅɪĞɪᴍɪᴢ Öɴᴇᴍʟɪᴅɪʀ ...',
'ᴄᴏᴋ ᴏɴᴇᴍsɪᴢʟɪᴋ ɪsᴇ ʏᴀʀᴀᴍᴀᴅɪ ᴀʀᴛɪᴋ ʙᴏs ᴠᴇʀɪʏᴏʀᴜᴢ ...', 'ʜᴇʀᴋᴇsɪɴ ʙɪʀ ɢᴇᴄᴍɪsɪ ᴠᴀʀ , ʙɪʀ ᴅᴇ ᴠᴀᴢɢᴇᴄᴍɪsɪ ...', 'ᴀsɪᴋ ᴏʟᴍᴀᴋ ɢᴜᴢᴇʟ ʙɪʀ sᴇʏ ᴀᴍᴀ sᴀᴅᴇᴄᴇ sᴀɴᴀ ...', 'ᴀɴʟᴀʏᴀɴ ʏᴏᴋᴛᴜ , sᴜsᴍᴀʏɪ ᴛᴇʀᴄɪʜ ᴇᴛᴛɪᴍ ...', 'sᴇɴ ᴄᴏᴋ sᴇᴠ ᴅᴇ ʙɪʀᴀᴋɪᴘ ɢɪᴅᴇɴ ʏᴀʀ ᴜᴛᴀɴsɪɴ ...', 'ᴏ ɢɪᴛᴛɪᴋᴛᴇɴ sᴏɴʀᴀ ɢᴇᴄᴇᴍ ɢᴜɴᴅᴜᴢᴇ ʜᴀsʀᴇᴛ ᴋᴀʟᴅɪ ...','ɢᴜᴠᴇɴᴍᴇᴋ  sᴇᴠᴍᴇᴋᴛᴇɴ ᴅᴀʜᴀ ᴅᴇɢᴇʀʟɪ , ᴢᴀᴍᴀɴʟᴀ ᴀɴʟᴀʀsɪɴ ...', 
'ɪɴsᴀɴ ʙᴀᴢᴇɴ ʙᴜʏᴜᴋ ʜᴀʏᴀʟʟᴇʀɪɴɪ ᴋᴜᴄᴜᴋ ɪɴsᴀɴʟᴀʀʟᴀ ᴢɪʏᴀɴ ᴇᴅᴇʀ ...', 'ᴋɪᴍsᴇ ᴋɪᴍsᴇʏɪ ᴋᴀʏʙᴇᴛᴍᴇᴢ  ɢɪᴅᴇɴ ʙᴀsᴋᴀsɪɴɪ ʙᴜʟᴜʀ , ᴋᴀʟᴀɴ ᴋᴇɴᴅɪɴɪ ...', 'ɢᴜᴄʟᴜ ɢᴏʀᴜɴᴇʙɪʟɪʀɪᴍ ᴀᴍᴀ ɪɴᴀɴ ʙᴀɴᴀ ʏᴏʀɢᴜɴᴜᴍ ...', 'ᴏᴍʀᴜɴᴜᴢᴜ sᴜsᴛᴜᴋʟᴀʀɪɴɪᴢɪ ᴅᴜʏᴀɴ  ʙɪʀɪʏʟᴇ ɢᴇᴄɪʀɪɴ ...', 'ʜᴀʏᴀᴛ ɪʟᴇʀɪʏᴇ ʙᴀᴋɪʟᴀʀᴀᴋ ʏᴀsᴀɴɪʀ ɢᴇʀɪʏᴇ ʙᴀᴋᴀʀᴀᴋ ᴀɴʟᴀsɪʟɪʀ ...', 'ᴀʀᴛɪᴋ ʜɪᴄʙɪʀ sᴇʏ ᴇsᴋɪsɪ ɢɪʙɪ ᴅᴇɢɪʟ ʙᴜɴᴀ ʙᴇɴᴅᴇ ᴅᴀʜɪʟɪᴍ ...', 'ᴋɪʏᴍᴇᴛ ʙɪʟᴇɴᴇ ɢᴏɴᴜʟᴅᴇ ᴠᴇʀɪʟɪʀ ᴏᴍᴜʀᴅᴇ ...', 
'ʙɪʀ ᴄɪᴄᴇᴋʟᴇ ɢᴜʟᴇʀ ᴋᴀᴅɪɴ , ʙɪʀ ʟᴀғʟᴀ ʜᴜᴢᴜɴ ...', 'ᴋᴀʟʙɪ ɢᴜᴢᴇʟ ᴏʟᴀɴ ɪɴsᴀɴɪɴ ɢᴏᴢᴜɴᴅᴇɴ ʏᴀs ᴇᴋsɪᴋ ᴏʟᴍᴀᴢᴍɪs ...', 'ʜᴇʀ sᴇʏɪ ʙɪʟᴇɴ ᴅᴇɢɪʟ ᴋɪʏᴍᴇᴛ ʙɪʟᴇɴ ɪɴsᴀɴʟᴀʀ ᴏʟsᴜɴ ʜᴀʏᴀᴛɪɴɪᴢᴅᴀ ...', 'ᴍᴇsᴀғᴇ ɪʏɪᴅɪʀ ɴᴇ ʜᴀᴅᴅɪɴɪ ᴀsᴀɴ ᴏʟᴜʀ , ɴᴇ ᴅᴇ ᴄᴀɴɪɴɪ sɪᴋᴀɴ ...', 'ʏᴜʀᴇɢɪᴍɪɴ ᴛᴀᴍ ᴏʀᴛᴀsɪɴᴅᴀ ʙᴜʏᴜᴋ ʙɪʀ ʏᴏʀɢᴜɴʟᴜᴋ ᴠᴀʀ ...', 'ᴠᴇʀɪʟᴇɴ ᴅᴇɢᴇʀɪɴ ɴᴀɴᴋᴏʀᴜ ᴏʟᴍᴀʏɪɴ ɢᴇʀɪsɪ ʜᴀʟʟ ᴏʟᴜʀ ...', 
'ʜᴇᴍ ɢᴜᴄʟᴜ ᴏʟᴜᴘ ʜᴇᴍ ʜᴀssᴀs ᴋᴀʟᴘʟɪ ʙɪʀɪ ᴏʟᴍᴀᴋ ᴄᴏᴋ ᴢᴏʀ ...', 'ᴍᴜʜᴛᴀᴄ ᴋᴀʟɪɴ ʏᴜʀᴇɢɪ ɢᴜᴢᴇʟ  ɪɴsᴀɴʟᴀʀᴀ ...', 'ɪɴsᴀɴ ᴀɴʟᴀᴅɪɢɪ ᴠᴇ ᴀɴʟᴀsɪʟᴅɪɢɪ ɪɴsᴀɴᴅᴀ ᴄɪᴄᴇᴋ ᴀᴄᴀʀ ...', 'ɪsᴛᴇʏᴇɴ ᴅᴀɢʟᴀʀɪ ᴀsᴀʀ ɪsᴛᴇᴍᴇʏᴇɴ ᴛᴜᴍsᴇɢɪ ʙɪʟᴇ ɢᴇᴄᴇᴍᴇᴢ ...', 'ɪɴsᴀʟʟᴀʜ sᴀʙɪʀʟᴀ ʙᴇᴋʟᴇᴅɪɢɪɴ sᴇʏ ɪᴄɪɴ ʜᴀʏɪʀʟɪ ʙɪʀ ʜᴀʙᴇʀ ᴀʟɪʀsɪɴ ...', 'ɪʏɪ ᴏʟᴀɴ ᴋᴀʏʙᴇᴛsᴇ ᴅᴇ ᴋᴀᴢᴀɴɪʀ ...', 'ɢᴏɴʟᴜɴᴜᴢᴇ ᴀʟᴅɪɢɪɴɪᴢ , ɢᴏɴʟᴜɴᴜᴢᴜ ᴀʟᴍᴀʏɪ ʙɪʟsɪɴ ...', 
'ʏɪɴᴇ ʏɪʀᴛɪᴋ ᴄᴇʙɪᴍᴇ ᴋᴏʏᴍᴜsᴜᴍ ᴜᴍᴜᴅᴜᴍᴜ ...', 'ᴏʟᴍᴇᴋ ʙɪʀ sᴇʏ ᴅᴇɢɪʟ ʏᴀsᴀᴍᴀᴋ ᴋᴏʀᴋᴜɴᴄ ...', 'ɴᴇ ɪᴄɪᴍᴅᴇᴋɪ sᴏᴋᴀᴋʟᴀʀᴀ sɪɢᴀʙɪʟᴅɪᴍ ɴᴇ ᴅᴇ ᴅɪsᴀʀɪᴅᴀᴋɪ ᴅᴜɴʏᴀʏᴀ ...', 'ɪɴsᴀɴ sᴇᴠɪʟᴍᴇᴋᴛᴇɴ ᴄᴏᴋ ᴀɴʟᴀsɪʟᴍᴀʏɪ ɪsᴛɪʏᴏʀᴅᴜ ʙᴇʟᴋɪ ᴅᴇ ...', 'ᴇᴋᴍᴇᴋ ᴘᴀʜᴀʟɪ , ᴇᴍᴇᴋ ᴜᴄᴜᴢᴅᴜʀ ...', 'sᴀᴠᴀsᴍᴀʏɪ ʙɪʀᴀᴋɪʏᴏʀᴜᴍ ʙᴜɴᴜ ᴠᴇᴅᴀ sᴀʏ ...','ᴋÜÇÜᴋ ɪŞʟᴇʀᴇ ɢᴇʀᴇĞɪɴᴅᴇɴ Çᴏᴋ Öɴᴇᴍ ᴠᴇʀᴇɴʟᴇʀ, ᴇʟɪɴᴅᴇɴ ʙÜʏÜᴋ ɪŞ ɢᴇʟᴍᴇʏᴇɴʟᴇʀᴅɪʀ ...',
'ᴀŞᴋ ʙɪʀ ᴋᴀᴅɪɴɪɴ ʏᴀŞᴀᴍɪɴɪɴ ᴛÜᴍ ÖʏᴋÜꜱÜ, ᴇʀᴋᴇĞɪɴ ɪꜱᴇ ʏᴀʟɴɪᴢᴄᴀ ʙɪʀ ꜱᴇʀÜᴠᴇɴɪᴅɪʀ ...','ʜᴇʀŞᴇʏɪ ᴅᴇɴᴇʀɪᴍ; ᴀᴍᴀ ʏᴀᴘᴀʙɪʟᴅɪᴋʟᴇʀɪᴍɪ ʏᴀᴘᴀʀɪᴍ ...','ʏᴀɴʟɪŞ ʙɪʟᴅɪĞɪɴ ʏᴏʟᴅᴀ; ʜЕʀᴋЕꜱʟЕ ʏÜʀÜʏЕᴄЕĞɪɴЕ, ᴅᴏĞʀᴜ ʙɪʟᴅɪĞɪɴ ʏᴏʟᴅᴀ; ᴛЕᴋ ʙᴀŞɪɴᴀ ʏÜʀÜ ...','ᴏ ᴅᴀ ɢᴀᴢɪ ᴏʟᴍᴀᴋ ɪꜱᴛᴇᴅɪ, ꜰᴀᴋᴀᴛ ᴏɴᴀ ᴀɴʟᴀᴛᴍᴀᴋ ɢᴇʀᴇᴋᴛɪ ᴋɪ, Şᴇʜɪᴅ ᴏʟᴍᴀʏɪ ɢÖᴢᴇ ᴀʟᴀᴍᴀʏᴀɴ ɢᴀᴢɪ ᴏʟᴀᴍᴀᴢᴅɪ ...','ɴᴇ ᴋᴀᴅᴀʀ ʏÜᴋꜱᴇʟɪʀꜱᴇɴ, ᴜÇᴍᴀʏɪ ʙɪʟᴍᴇʏᴇɴʟᴇʀᴇ ᴏ ᴋᴀᴅᴀʀ ᴋÜÇÜᴋ ɢÖʀÜɴÜʀꜱÜɴ ...',
'ɴᴇ ᴋᴀᴅᴀʀ ʜᴀᴢɪɴ ʙɪʀ ÇᴀĞᴅᴀ ʏᴀŞɪʏᴏʀᴜᴢ, ʙɪʀ Öɴʏᴀʀɢɪʏɪ ᴏʀᴛᴀᴅᴀɴ ᴋᴀʟᴅɪʀᴍᴀᴋ ᴀᴛᴏᴍᴜ ᴘᴀʀÇᴀʟᴀᴍᴀᴋᴛᴀɴ ᴅᴀʜᴀ ɢÜÇ ...','ᴍᴜᴛʟᴜʟᴜᴋ ʜᴇʀ Şᴇʏᴅᴇɴ Öɴᴄᴇ ᴠÜᴄᴜᴛ ꜱᴀĞʟɪĞɪɴᴅᴀᴅɪʀ ...','ʙᴀᴢᴇɴ ʙɪʀ Şᴇʏᴇ ꜱᴏɴ ᴠᴇʀᴍᴇᴋ ɪÇɪɴ ɪꜱᴛᴇᴍᴇᴅɪĞɪɴ ʙɪʀ Şᴇʏ ʏᴀᴘᴍᴀɴ ɢᴇʀᴇᴋɪʀ ...','ᴋɪᴍ ᴋᴀᴢᴀɴᴍᴀᴢꜱᴀ ʙᴜ ᴅÜɴʏᴀᴅᴀ ʙɪʀ ᴇᴋᴍᴇᴋ ᴘᴀʀᴀꜱɪ ʏᴀ ᴅᴏꜱᴛᴜɴᴜɴ ʏÜᴢ ᴋᴀʀᴀꜱɪ ʏᴀ ᴅᴀ ᴅÜŞᴍᴀɴɪɴɪɴ ᴍᴀꜱᴋᴀʀᴀꜱɪ ...','ᴀᴠᴜᴄᴜ ᴋᴀᴅᴀʀ ʏÜʀᴇĞɪ ᴏʟᴍᴀʏᴀɴ ɪɴꜱᴀɴʟᴀʀɪ ᴋÜʀᴇᴋ ɢɪʙɪ ᴅɪʟɪ ᴠᴀʀ ...','ᴍᴜᴛʟᴜʟᴜᴋ ʜᴇʀ Şᴇʏᴅᴇɴ Öɴᴄᴇ ᴠÜᴄᴜᴛ ꜱᴀĞʟɪĞɪɴᴅᴀᴅɪʀ ...',
'ᴏᴋʏᴀɴᴜꜱᴛᴀ Öʟᴍᴇᴢ ᴅᴇ ɪɴꜱᴀɴ, ɢɪᴅᴇʀ ʙɪʀ ᴋᴀŞɪᴋ ꜱᴇᴠᴅᴀᴅᴀ ʙᴏĞᴜʟᴜʀ ...','ᴍᴜᴛʟᴜʟᴜᴋ ʜᴇʀ Şᴇʏᴅᴇɴ Öɴᴄᴇ ᴠÜᴄᴜᴛ ꜱᴀĞʟɪĞɪɴᴅᴀᴅɪʀ ...','ɴᴇʀᴇʏᴇ ɢɪᴛᴛɪĞɪɴɪ ʙɪʟᴍɪʏᴏʀꜱᴀɴ, ʜᴀɴɢɪ ʏᴏʟᴅᴀɴ ɢɪᴛᴛɪĞɪɴɪɴ ʜɪÇʙɪʀ Öɴᴇᴍɪ ʏᴏᴋᴛᴜʀ ...','ʙᴀᴢᴇɴ ɪʟᴋ ɢÖʀÜŞᴛᴇ ʙɪʟɪʀꜱɪɴ, ᴏ ɪɴꜱᴀɴ ꜱᴇɴɪɴ ᴋᴀᴅᴇʀɪɴᴅɪʀ. ʙᴀᴢᴇɴ ʙɪʀ ÖᴍÜʀ ᴀʀᴀʀꜱɪɴ, ʙᴜʟᴜɴᴍᴀᴢ ...','ʟᴀɴᴇᴛ ᴏʟꜱᴜɴ. ɴᴇ ᴍᴜᴀᴢᴢᴀᴍ Şᴇʏ ꜱᴇɴɪ ꜱᴇᴠᴍᴇᴋ ...','ʏᴀʀɪᴍ ɴᴇꜰᴇꜱʟɪᴋ ʙᴜ ʜᴀʏᴀᴛᴛᴀ. ꜱᴇᴠɢɪᴅᴇɴ ʙᴀŞᴋᴀ ʜɪÇʙɪʀ Şᴇʏ ᴘʟᴀɴʟᴀᴍᴀ ...',
'İʟɪᴍ ᴀŞᴀĞɪᴅᴀᴋɪʟᴇʀɪ ʏÜᴋꜱᴇʟᴛɪʀ, ᴄᴀʜɪʟʟɪᴋ ɪꜱᴇ ʏÜᴋꜱᴇᴋᴛᴇᴋɪʟᴇʀɪ ᴀʟÇᴀʟᴛɪʀ ...','ᴋɪᴍ ɪʟɪᴍ ᴀʀᴀᴍᴀ ʏᴏʟᴜɴᴅᴀ ᴏʟᴜʀꜱᴀ, ᴄᴇɴɴᴇᴛ ᴅᴇ ᴏɴᴜ ᴀʀᴀᴍᴀ ʏᴏʟᴜɴᴅᴀ ᴏʟᴜʀ ...','ʏᴀɴɪʟᴛᴍᴀꜱɪɴ ꜱᴇɴɪ ᴍᴀꜱᴜᴍ ʙᴀᴋɪŞʟᴀʀ, ʙᴀᴢɪʟᴀʀɪɴɪ Şᴇʏᴛᴀɴ ᴀʏᴀᴋᴛᴀ ᴀʟᴋɪŞʟᴀʀ ...','İɴꜱᴀɴʟᴀʀɪ ᴛᴀɴɪŞɪʀᴋᴇɴ ᴅᴇĞɪʟ, ᴛᴀʀᴛɪŞɪʀᴋᴇɴ ᴛᴀɴɪʀꜱɪɴ. ÇÜɴᴋÜ Öꜰᴋᴇ, ꜱᴀʟʟᴀɴᴀɴ ᴋɪŞɪʟɪĞɪ ᴏʀᴛᴀʏᴀ Çɪᴋᴀʀɪʀ ...','ɢᴇʀÇᴇᴋ ᴀŞᴋ ɪÇɪɴ ᴀꜱʟᴀ ʙɪʀ ᴢᴀᴍᴀɴ ʏᴀ ᴅᴀ ʏᴇʀ ʏᴏᴋᴛᴜʀ ...','ᴇĞᴇʀ ᴅᴏĞʀᴜʏᴜ ꜱÖʏʟᴇʀꜱᴇɴ ʜɪÇʙɪʀ Şᴇʏɪ ʜᴀᴛɪʀʟᴀᴍᴀᴋ ᴢᴏʀᴜɴᴅᴀ ᴅᴇĞɪʟꜱɪɴ ...',
'ʜᴇʀ ᴇʟɪɴɪ ꜱɪᴋᴀɴʟᴀ ᴅᴏꜱᴛ, ʜᴇʀ ᴄᴀɴɪɴɪ ꜱɪᴋᴀɴʟᴀ ᴅÜŞᴍᴀɴ ᴏʟᴍᴀ ...','ᴇᴅᴇᴘ ᴀᴋʟɪɴ ᴛᴇʀᴄÜᴍᴀɴɪᴅɪʀ. ʜᴇʀᴋᴇꜱ ᴇᴅᴇʙɪ ᴋᴀᴅᴀʀ ᴀᴋɪʟʟɪ, ᴀᴋʟɪ ᴋᴀᴅᴀʀ Şᴇʀᴇꜰʟɪ, Şᴇʀᴇꜰɪ ᴋᴀᴅᴀʀ ᴅᴇĞᴇʀʟɪᴅɪʀ ...','ʏᴀŞɪɴ ᴅᴇĞɪʟ ʏᴀŞᴀᴅɪᴋʟᴀʀɪɴ ÖĞʀᴇᴛɪʀ ꜱᴀɴᴀ ʜᴀʏᴀᴛɪ ...','Şᴜɴᴜ ᴀꜱʟᴀ ᴜɴᴜᴛᴍᴀ; ɢÜʟᴇʀᴋᴇɴ ᴋᴀʏʙᴇᴛᴛɪᴋʟᴇʀɪɴɪ, ᴀĞʟᴀʏᴀʀᴀᴋ ᴋᴀᴢᴀɴᴀᴍᴀᴢꜱɪɴ ...','ꜰᴀᴢʟᴀ ʙÜʏÜᴛᴍᴇ ᴋᴇɴᴅɪɴɪ, ᴇɴ ꜰᴀᴢʟᴀ ꜱᴇᴠᴇʙɪʟᴅɪĞɪᴍ ᴋᴀᴅᴀʀꜱɪɴ; ᴅᴀʜᴀꜱɪ ʏᴏᴋ ...','ᴀŞᴋ Çᴏᴋ ᴋɪꜱᴀ ᴀᴍᴀ ᴜɴᴜᴛᴍᴀꜱɪ Çᴏᴋ ᴢᴏʀ ...',
'İʏɪʏɪ ᴀʀᴀ, ᴅᴏĞʀᴜʏᴜ ᴀʀᴀ, ɢÜᴢᴇʟɪ ᴀʀᴀ ꜰᴀᴋᴀᴛ ᴋᴜꜱᴜʀᴜ ᴀʀᴀᴍᴀ ...','ʜᴀʏᴀᴛɪ ɢÖᴢʏᴀŞʟᴀʀɪɴʟᴀ ÖᴅÜʟʟᴇɴᴅɪʀᴇᴄᴇĞɪɴᴇ; ɢÜʟÜᴄÜᴋʟᴇʀɪɴʟᴇ ᴄᴇᴢᴀʟᴀɴᴅɪʀ ...','ᴜᴢᴀᴋᴋᴇɴ ʙɪʟᴇ ʙɪʀ ɴᴇꜰᴇꜱ ᴋᴀᴅᴀʀ ʏᴀᴋɪɴɪᴍᴅᴀꜱɪɴ ...','ʜᴇʀ ᴍÜɴᴀᴋᴀŞᴀɴɪɴ ᴛᴇᴍᴇʟɪɴᴅᴇ ʙɪʀɪꜱɪɴɪɴ ᴄᴀʜɪʟʟɪĞɪ ʏᴀᴛᴀʀ ...','ʙɪʟɢᴇʟɪᴋ ᴋᴀʟᴘᴛᴇɴ ɢᴇʟɪʀ. ᴀᴋɪʟʟᴀ ɪʟɢɪꜱɪ ʏᴏᴋᴛᴜʀ. ʙɪʟɢᴇʟɪᴋ, ᴠᴀʀʟɪĞɪɴɪɴ ᴇɴ ᴅᴇʀɪɴ ɴᴏᴋᴛᴀꜱɪɴᴅᴀɴ Çɪᴋᴀʀ. ᴋᴀꜰᴀʏᴀ ᴀɪᴛ ᴅᴇĞɪʟᴅɪʀ ...',
'ʏᴀŞᴀᴅɪĞɪɴ ʏᴇʀɪ ᴄᴇɴɴᴇᴛ ʏᴀᴘᴀᴍᴀᴅɪĞɪɴ ꜱÜʀᴇᴄᴇ ᴋᴀÇᴛɪĞɪɴ ʜᴇʀ ʏᴇʀ ᴄᴇʜᴇɴɴᴇᴍᴅɪʀ ...','ᴋɪʀɪʟᴍɪŞ ʙɪʀɪ Çᴏᴋ ɢÜᴢᴇʟ ꜱᴜꜱᴀʀ. ʜᴇʀ Şᴇʏɪɴᴇ ʜᴀꜱʀᴇᴛ ᴋᴀʟɪʀꜱɪɴ ...','İɴᴀɴÇ, ᴘᴀʀÇᴀʟᴀɴᴍɪŞ ʙɪʀ ᴅÜɴʏᴀɴɪɴ ɪŞɪĞᴀ ÇɪᴋᴀᴄᴀĞɪ ɢÜÇᴛÜʀ ...','ʙᴇʟᴋɪ ᴅᴇ ɪɴꜱᴀɴ ʜᴇʀ Şᴇʏɪ ɪÇɪɴᴇ ᴀᴛᴍᴀᴋᴛᴀɴ ʙᴏĞᴜʟᴜʏᴏʀ ᴢᴀᴍᴀɴʟᴀ ...','ᴀŞᴋ ʙɪʀ ᴋᴀᴅɪɴɪɴ ʏᴀŞᴀᴍɪɴɪɴ ᴛÜᴍ ÖʏᴋÜꜱÜ, ᴇʀᴋᴇĞɪɴ ɪꜱᴇ ʏᴀʟɴɪᴢᴄᴀ ʙɪʀ ꜱᴇʀÜᴠᴇɴɪᴅɪʀ ...','ᴀŞᴋ ʀÜᴢɢᴀʀ ɢɪʙɪᴅɪʀ, ɢÖʀᴇᴍᴇᴢꜱɪɴ ᴀᴍᴀ ʜɪꜱꜱᴇᴅᴇʙɪʟɪʀꜱɪɴ ...',
'ᴅᴇĞɪŞɪᴍ ᴇʙᴇᴅɪ, ÖʟÜᴍꜱÜᴢʟÜᴋ ᴋᴀʟɪᴄɪᴅɪʀ ...','ᴋÖʀʟᴇʀɪɴ Üʟᴋᴇꜱɪɴᴅᴇ, ᴛᴇᴋ ɢÖᴢʟÜ ɪɴꜱᴀɴ ᴋʀᴀʟ ᴏʟᴜʀ ...''ᴏʏꜱᴀ ʏÜʀᴇĞɪ ᴛᴇᴍɪᴢ ᴏʟᴍᴀʏᴀɴɪɴ, ᴀɴʟᴀʏɪŞɪ ᴅᴀ ᴋɪᴛᴛɪʀ ...','ʜɪÇ ʙᴜ ᴋᴀᴅᴀʀ ꜱᴜꜱᴍᴀᴋ ɪꜱᴛᴇᴍᴇᴍɪŞᴛɪᴍ ...','ŞÜᴋʀᴇᴛᴍᴇʏɪ ÖĞʀᴇɴᴍᴇʏᴇɴ ɴᴀɴᴋÖʀ ᴇʟʙᴇᴛᴛᴇ ŞɪᴋÂʏᴇᴛ ᴇᴅᴇʀ ...','Öʏʟᴇ ʙɪʀ ɢᴇʟ ᴅᴇᴍᴇʟɪꜱɪɴ ᴋɪ, ᴍᴇꜱᴀꜰᴇʟᴇʀ ᴀɴʟᴀᴍɪɴɪ ʏɪᴛɪʀᴍᴇʟɪ ...',
'ꜱᴀʙɪʀ ᴠᴀᴢɢᴇÇᴍᴇᴋ ᴅᴇĞɪʟ, ᴜᴍᴜᴅᴜ ʏᴀʀɪɴᴀ ᴇʀᴛᴇʟᴇᴍᴇᴋᴛɪʀ ...','ꜱᴇᴠᴅɪᴋʟᴇʀɪɴɪᴢᴇ ᴢᴀᴍᴀɴ ᴀʏɪʀɪɴ ʏᴏᴋꜱᴀ ᴢᴀᴍᴀɴ ꜱɪᴢɪ ꜱᴇᴠᴅɪᴋʟᴇʀɪɴɪᴢᴅᴇɴ ᴀʏɪʀɪʀ ...','ʙᴀŞᴋᴀꜱɪɴɪɴ ÖɴÜɴÜ ᴀʏᴅɪɴʟᴀᴛɪʀᴋᴇɴ ᴋᴇɴᴅɪ ʏᴏʟᴜᴍᴜᴢᴀ ᴅᴀ ɪŞɪᴋ ᴛᴜᴛᴀʀɪᴢ ...','ʜᴇʀᴋᴇꜱ ᴀʏɴɪ Şᴇʏɪ ᴅÜŞÜɴÜʏᴏʀꜱᴀ, ʜɪÇ ᴋɪᴍꜱᴇ ꜰᴀᴢʟᴀ ʙɪʀ Şᴇʏ ᴅÜŞÜɴᴍÜʏᴏʀ ᴅᴇᴍᴇᴋᴛɪʀ ...','İÇɪɴᴇ ᴀᴛᴛɪᴋʟᴀʀɪɴ ᴋᴇᴅᴇʀɪɴᴅɪʀ. İÇɪɴᴅᴇɴ ᴀᴛᴀᴍᴀᴅɪᴋʟᴀʀɪɴ ᴋᴀᴅᴇʀɪɴ ...',
'ᴍᴜᴛʟᴜ ᴍᴜ ᴏʟᴍᴀᴋ ɪꜱᴛɪʏᴏʀꜱᴜɴ , ᴋɪᴍꜱᴇᴅᴇɴ ʙɪʀ Şᴇʏ ʙᴇᴋʟᴇᴍᴇ ...','ɢÜᴢᴇʟɪ ɢÜᴢᴇʟ ʏᴀᴘᴀɴ ᴇᴅᴇᴘᴛɪʀ, ᴇᴅᴇᴘ ɪꜱᴇ ɢÜᴢᴇʟɪ ꜱᴇᴠᴍᴇʏᴇ ꜱᴇʙᴇᴘᴛɪʀ ...','ʏᴏʀᴍᴀ ᴋᴇɴᴅɪɴɪ... ʙɪʀᴀᴋ ʜᴀʏᴀᴛɪɴᴀ ᴇŞʟɪᴋ ᴇᴛᴍᴇᴋ ɪꜱᴛᴇʏᴇɴʟᴇʀ ꜱᴇɴɪɴʟᴇ ɢᴇʟꜱɪɴ ...','ʙɪʀÇᴏᴋ ɪɴꜱᴀɴ ᴍᴜᴛʟᴜʟᴜĞᴜ, ʙᴜʀɴᴜɴᴜɴ ÜꜱᴛÜɴᴅᴇ ᴜɴᴜᴛᴛᴜĞᴜ ɢÖᴢʟÜᴋ ɢɪʙɪ ᴇᴛʀᴀꜰᴛᴀ ᴀʀᴀʀ ...','ᴅÜʀÜꜱᴛ ᴏʟᴍᴀᴋᴛᴀɴ ᴋᴏʀᴋᴍᴀ, ᴋᴀʏʙᴇᴅᴇᴄᴇĞɪɴ ᴇɴ ꜰᴀᴢʟᴀ ʏᴀɴʟɪŞ ɪɴꜱᴀɴʟᴀʀ ᴏʟᴜʀ ...',
)

sor = (
'ᴋᴜʀᴛ ᴍᴜ ᴋᴇʟɪᴍᴇ ᴏʏᴜɴᴜ ᴍᴜ ?','Gʀᴜᴘᴛᴀ ɴᴇʏɪ ᴅᴇɢ̆ɪşᴛɪʀᴍᴇᴋ ɪsᴛᴇʀᴅɪɴ?','ɢʀᴜᴘᴛᴀ ᴋɪᴍʟᴇ ᴄ̧ᴀʏ ɪᴄ̧ᴍᴇᴋ ɪsᴛᴇʀᴅɪɴ ?','ʙᴜ̈ʏᴜ̈ʏᴇɴ ʜᴀʏᴀʟɪ ʙɪʀ ᴀʀᴋᴀᴅᴀşıɴıᴢ ᴠᴀʀ ᴍıʏᴅı?','ʙɪʀ ɢᴜ̈ɴ ᴋᴀʀşı ᴄɪɴs ᴏʟᴀʀᴀᴋ ᴜʏᴀɴıʀsᴀɴ, ɪʟᴋ ʏᴀᴘᴀᴄᴀɢ̆ıɴ şᴇʏ ɴᴇᴅɪʀ?','ɢʀᴜʙᴜɴ ᴏʟᴍᴀᴢsᴀ ᴏʟᴍᴀᴢı sᴇɴᴄᴇ ᴋɪᴍ ᴇᴛɪᴋᴇᴛʟᴇʀ ᴍɪsɪɴ?','ʜᴀʏᴀᴛᴛᴀ ᴜɴᴜᴛᴍᴀᴅıɢ̆ıɴ ʙɪʀɪ ᴠᴀʀ ᴍı?','ᴋᴜ̈ʟᴛᴜ̈ʀᴜ̈ᴍᴜ̈ᴢᴜ̈ɴ ᴇɴ ᴄ̧ᴏᴋ sᴇᴠᴅɪɢ̆ɪɴɪᴢ ʏᴀɴı ɴᴇᴅɪʀ?','ɢʀᴜʙᴜ sᴇᴠɪʏᴏʀ ᴍᴜsᴜɴ ?','ʜᴀʏᴀᴛᴛᴀ ᴜɴᴜᴛᴍᴀᴅıɢ̆ıɴ ʙɪʀɪ ᴠᴀʀ ᴍı?','ʜɪᴄ̧ʙɪʀ sᴏɴᴜᴄᴜ ᴏʟᴍᴀʏᴀᴄᴀɢ̆ıɴı ʙɪʟsᴇɴ ɴᴇ ʏᴀᴘᴍᴀᴋ ɪsᴛᴇʀᴅɪɴ?','ɪʟᴇʀᴅᴇ ᴄ̧ᴏᴄᴜɢ̆ᴜɴ ᴏʟᴜʀsᴀ ɴᴇ ɪsɪᴍ ᴋᴏʏᴍᴀᴋ ɪsᴛᴇʀsɪɴ?',
'şɪᴍᴅɪʏᴇ ᴋᴀᴅᴀʀ ʜɪᴄ̧ ᴀʀᴀʟıᴋsıᴢ 𝟷𝟸 sᴀᴀᴛᴛᴇɴ ғᴀᴢʟᴀ ᴜʏᴜᴅᴜɢ̆ᴜɴ ᴏʟᴅᴜ ᴍᴜ?','ɢʀᴜᴘᴛᴀ ᴋɪ ᴜ̈ᴄ̧ ᴋᴀɴᴋᴀɴı ᴇᴛɪᴋᴇᴛʟᴇʀ ᴍɪsɪɴ?','sıɴıғᴛᴀ ʜɪᴄ̧ ᴜʏᴜʏᴀ ᴋᴀʟᴅıɴ ᴍı?','ɢʀᴜʙᴜɴ ᴇɴ ᴅᴇʀᴛʟɪsɪ ᴋɪᴍ ?','ʀᴇᴀʟ ʜᴀʏᴀᴛᴛᴀ ᴛᴀɴıᴍᴀᴋ ɪsᴛᴇᴅɪɢ̆ɪɴ ᴋɪᴍsᴇ ᴠᴀʀ ᴍı ɢʀᴜᴘᴛᴀ ?','ʙɪʀɪɴɪɴ ᴛᴇʟᴇғᴏɴᴜɴᴅᴀ ɢᴏ̈ʀᴅᴜ̈ɢ̆ᴜ̈ɴ ᴇɴ ᴛᴜʜᴀғ şᴇʏ ɴᴇᴅɪʀ?','ʙɪʀ ʙᴏ̈ᴄᴇᴋ ɪsᴛɪʟᴀsı ɢᴇʀᴄ̧ᴇᴋʟᴇşsᴇ ʜᴀɴɢɪ ᴀʀᴋᴀᴅᴀşıɴ ʜᴀʏᴀᴛᴛᴀ ᴋᴀʟᴍᴀʏı ʙᴀşᴀʀıʀ?','ᴅᴜ̈ɴʏᴀᴅᴀᴋɪ ʜᴇʀʜᴀɴɢɪ ʙɪʀɪɴɪ ᴛᴜ̈ʀᴋɪʏᴇ’ɴɪɴ ʙᴀşᴋᴀɴı ʏᴀᴘᴀʙɪʟsᴇʏᴅɪɴ ʙᴜ ᴋɪᴍ ᴏʟᴜʀᴅᴜ?','ᴋᴜʀᴛ ᴏʏᴜɴᴜɴᴜ sᴇᴠɪʏᴏʀ ᴍᴜsᴜɴ?','ɢʀᴜᴘᴛᴀ ᴅᴇɢ̆ɪşᴍᴇsɪ ɢᴇʀᴇᴋᴇɴ şᴇʏ ᴠᴀʀ ᴍı?','ʜɪᴄ̧ʙɪʀ sᴏɴᴜᴄᴜ ᴏʟᴍᴀʏᴀᴄᴀɢ̆ıɴı ʙɪʟsᴇɴ ɴᴇ ʏᴀᴘᴍᴀᴋ ɪsᴛᴇʀᴅɪɴ?',
'ʙɪʀ ᴀʏɴᴀɴıɴ ᴏ̈ɴᴜ̈ɴᴅᴇ ʏᴀᴘᴛıɢ̆ıɴ ᴇɴ ᴄ̧ıʟɢıɴᴄᴀ şᴇʏ ɴᴇᴅɪʀ?','ᴄ̧ıᴋᴍᴀᴋ ɪsᴛᴇʏᴇᴄᴇɢ̆ɪɴ ᴇɴ ɢᴇɴᴄ̧ ᴋɪşɪ ᴋᴀᴄ̧ ʏᴀşıɴᴅᴀ ᴏʟᴜʀᴅᴜ?','ᴋɪʟᴏ ᴀʟᴅıʀıᴘ ᴀʟᴅıʀᴍᴀᴍᴀsı ᴏ̈ɴᴇᴍʟɪ ᴅᴇɢ̆ɪʟ, ʙɪʀ ᴏᴛᴜʀᴜşᴛᴀ ʜᴇᴘsɪɴɪ ʏᴇʀɪᴍ ᴅᴇᴅɪɢ̆ɪɴ ʏᴇᴍᴇᴋ ɴᴇᴅɪʀ?','ɢʀᴜᴘᴛᴀ ʜᴀɴɢɪ ᴏʏᴜɴᴜ sᴇᴠɪʏᴏʀsᴜɴ ?','ᴜʏᴋᴜɴᴅᴀ ᴋᴏɴᴜşᴜʀ ᴍᴜsᴜɴ?','ᴇɴ ᴋᴏ̈ᴛᴜ̈ ɢʀᴜᴘ ʜᴀɴɢɪsɪᴅɪʀ?','ɪ̇ɴsᴀɴʟᴀʀı ʏᴀɴᴀɴ ʙɪʀ ʙɪɴᴀᴅᴀɴ ᴋᴜʀᴛᴀʀıʏᴏʀ ᴏʟsᴀʏᴅıɴıᴢ ᴠᴇ ʙɪʀ ᴋɪşɪʏɪ ʙᴜ ɢʀᴜᴘᴅᴀɴ ɢᴇʀɪᴅᴇ ʙıʀᴀᴋᴍᴀᴋ ᴢᴏʀᴜɴᴅᴀ ᴋᴀʟıʀsᴀɴıᴢ, ᴋɪᴍ ᴏʟᴜʀᴅᴜ?','ʜᴀʟᴀ ʏᴀᴘᴛıɢ̆ıɴ ᴇɴ ᴄ̧ᴏᴄᴜᴋᴄ̧ᴀ şᴇʏ ɴᴇᴅɪʀ?','ᴠᴜ̈ᴄᴜᴅᴜɴᴜɴ ʜᴀɴɢɪ ʙᴏ̈ʟᴜ̈ᴍᴜ̈ɴᴜ̈ sᴇᴠɪʏᴏʀsᴜɴ, ʜᴀɴɢɪ ᴋısᴍıɴᴅᴀɴ ɴᴇғʀᴇᴛ ᴇᴅɪʏᴏʀsᴜɴ?','sıɴıғᴛᴀ ᴀsʟᴀ ʏᴀɴıɴᴅᴀ ᴏᴛᴜʀᴍᴀᴋ ɪsᴛᴇᴍᴇʏᴇᴄᴇɢ̆ɪɴ ᴋɪᴍ?','ᴋᴀᴄ̧ sᴇᴠɢɪʟɪɴ ᴏʟᴅᴜ?',
'ʜɪᴄ̧ʙɪʀ sᴏɴᴜᴄᴜ ᴏʟᴍᴀʏᴀᴄᴀɢ̆ıɴı ʙɪʟsᴇɴ ɴᴇ ʏᴀᴘᴍᴀᴋ ɪsᴛᴇʀᴅɪɴ?','ᴇɴ ᴋᴏ̈ᴛᴜ̈ ɢʀᴜᴘ ʜᴀɴɢɪsɪᴅɪʀ?','ɢʀᴜᴘᴛᴀ ʜᴏşʟᴀɴᴅıɢ̆ıɴ ʙɪʀɪ ᴠᴀʀ ᴍı ?','ᴄ̧ᴇşɪᴛʟɪ ʙᴀᴛıʟ ɪɴᴀɴᴄ̧ʟᴀʀıɴ ᴠᴀʀ ᴍı, ᴠᴀʀsᴀ ᴏɴʟᴀʀ ɴᴇʟᴇʀ?','ᴇɴ sᴏɴ ɴᴇ ᴢᴀᴍᴀɴ ʜᴜ̈ɴɢᴜ̈ʀ ʜᴜ̈ɴɢᴜ̈ʀ ᴀɢ̆ʟᴀᴅıɢ̆ıɴı ʜᴀᴛıʀʟıʏᴏʀ ᴍᴜsᴜɴ?','ᴏᴛᴏʙᴜ̈sᴛᴇ ʏᴀᴘᴛıɢ̆ıɴ ᴇɴ ᴛᴜʜᴀғ şᴇʏ ɴᴇᴅɪʀ?','ᴇɴ sᴏɴ sᴏ̈ʏʟᴇᴅɪɢ̆ɪɴ ʏᴀʟᴀɴ ɴᴇᴅɪʀ?','ʙᴜ ɢʀᴜᴘᴅᴀɴ ʙɪʀɪʏʟᴇ ᴇᴠʟᴇɴᴍᴇᴋ ᴢᴏʀᴜɴᴅᴀ ᴋᴀʟsᴀɴ ᴋɪᴍ ᴏʟᴜʀᴅᴜ?','ʜɪᴄ̧ ʏᴀşıɴ ʜᴀᴋᴋıɴᴅᴀ ʏᴀʟᴀɴ sᴏ̈ʏʟᴇᴅɪɴ ᴍɪ?','şɪşᴇᴅᴇɴ ʙɪʀ ᴄɪɴ ᴄ̧ıᴋsᴀ ᴜ̈ᴄ̧ ᴅɪʟᴇɢ̆ɪɴ ɴᴇ ᴏʟᴜʀᴅᴜ?','ʙᴜ̈ʏᴜ̈ʀᴋᴇɴ ʜɪᴄ̧ ʜᴀʏᴀʟɪ ᴀʀᴋᴀᴅᴀşıɴ ᴏʟᴅᴜ ᴍᴜ?','ᴠᴜ̈ᴄᴜᴅᴜɴᴜɴ ʜᴀɴɢɪ ʙᴏ̈ʟᴜ̈ᴍʟᴇʀɪɴᴅᴇɴ ɢıᴅıᴋʟᴀɴıʏᴏʀsᴜɴ?',
'ʜᴀʏᴀʟɪɴᴅᴇᴋɪ ɪş ɴᴇ?','ʙᴜ ɢʀᴜᴘᴛᴀᴋɪ ɪɴsᴀɴʟᴀʀᴅᴀɴ ᴋɪᴍɪɴʟᴇ ʜᴀʏᴀᴛıɴı ᴅᴇɢ̆ɪşᴛɪʀᴍᴇᴋ ɪsᴛᴇʀᴅɪɴ?','ʙᴜ ɢʀᴜᴘᴛᴀᴋɪ ɪɴsᴀɴʟᴀʀᴅᴀɴ ᴋɪᴍɪɴʟᴇ ʜᴀʏᴀᴛıɴı ᴅᴇɢ̆ɪşᴛɪʀᴍᴇᴋ ɪsᴛᴇʀᴅɪɴ?','ᴇɴ ᴛᴜʜᴀғ ᴛᴀᴋᴍᴀ ᴀᴅıɴ ɴᴇᴅɪʀ?','ɢᴜ̈ɴᴅᴇ ᴋᴀᴄ̧ ᴛᴀɴᴇ ᴏ̈ᴢᴄ̧ᴇᴋɪᴍ ʏᴀᴘᴀʀsıɴ?','ᴋɪᴍsᴇɴɪɴ ʙɪʟᴍᴇʏᴇᴄᴇɢ̆ɪ ɢᴀʀᴀɴᴛɪ ᴏʟsᴀ ᴋɪᴍɪ ᴏ̈ʟᴅᴜ̈ʀᴍᴇᴋ ɪsᴛᴇʀᴅɪɴ?','ᴛᴇʟᴇғᴏɴᴜɴᴜᴢᴅᴀ ᴀʀᴀᴅıɢ̆ıɴ sᴏɴ şᴇʏ ɴᴇʏᴅɪ?','ɪ̇ɴsᴀɴʟᴀʀıɴ sɪᴢᴇ ɴᴇ sᴏʀᴍᴀsıɴᴅᴀɴ ʙıᴋᴛıɴıᴢ?','ʙᴇʏɴɪɴɪ ʙɪʀ ʀᴏʙᴏᴛᴀ ʏᴇʀʟᴇşᴛɪʀᴇʙɪʟɪʀ ᴠᴇ sᴏɴsᴜᴢᴀ ᴋᴀᴅᴀʀ ʙᴜ şᴇᴋɪʟᴅᴇ ʏᴀşᴀʏᴀʙɪʟsᴇᴅɪɴ,ʙᴜɴᴜ ʏᴀᴘᴀʀ ᴍıʏᴅıɴ?','ɢᴜ̈ɴᴅᴇ ᴋᴀᴄ̧ ᴛᴀɴᴇ ᴏ̈ᴢᴄ̧ᴇᴋɪᴍ ʏᴀᴘᴀʀsıɴ?','ɢɪᴢʟɪ ᴀşᴋıɴ ᴋɪᴍ?','ᴋᴀᴅıɴ/ᴇʀᴋᴇᴋ ᴏʟᴍᴀɴıɴ ᴇɴ ᴋᴏ̈ᴛᴜ̈ ᴠᴇ ᴇɴ ɪʏɪ ʏᴀɴı ɴᴇᴅɪʀ?','ɢʀᴜʙᴜɴ ᴇɴ ᴅᴇʀᴛʟɪsɪ ᴋɪᴍ ?',
'ғɪᴢɪᴋsᴇʟ ᴏʟᴀʀᴋ sᴀɴᴀ ᴇɴ ᴀᴄı ᴠᴇʀᴇɴ ᴅᴇɴᴇʏɪᴍɪɴ ɴᴇ ᴏʟᴅᴜ?','ɢʀᴜᴘᴛᴀ ɢɪᴢʟɪ sᴇᴠᴅɪɢ̆ɪɴ ᴋɪᴍsᴇ ᴠᴀʀ ᴍı?','ɪʟᴇʀᴅᴇ ᴄ̧ᴏᴄᴜɢ̆ᴜɴ ᴏʟᴜʀsᴀ ɴᴇ ɪsɪᴍ ᴋᴏʏᴍᴀᴋ ɪsᴛᴇʀsɪɴ?','ʜᴀʏᴀᴛıɴʟᴀ ɪʟɢɪʟɪ ᴛᴇʟᴇɢʀᴀᴍᴅᴀ ɴᴇ ʏᴀʟᴀɴ sᴏ̈ʏʟᴇᴅɪɴ ?','ʙɪʀɪɴɪ ᴏ̈ᴘᴇʀᴋᴇɴ ᴋᴇɴᴅɪɴɪ ʜɪᴄ̧ ᴋᴏ̈ᴛᴜ̈ ʜɪssᴇᴛᴛɪɴ ᴍɪ?','ʙɪʀɪsɪ ᴋıᴢ ᴀʀᴋᴀᴅᴀşıɴ / ᴇʀᴋᴇᴋ ᴀʀᴋᴀᴅᴀşıɴᴅᴀɴ ᴀʏʀıʟᴍᴀᴋ ɪᴄ̧ɪɴ sᴀɴᴀ 𝟷 ᴍɪʟʏᴏɴ ᴛʟ ᴏ̈ɴᴇʀsᴇʏᴅɪ, ʏᴀᴘᴀʀ ᴍıʏᴅıɴ?','ɢʀᴜᴘᴛᴀ ᴏʟᴍᴀᴍᴀsıɴı ɪsᴛᴇᴅɪɢ̆ɪɴ ᴋɪşɪʏɪ ᴇᴛɪᴋᴇᴛʟᴇʀ ᴍɪsɪɴ?','ʙᴜ ᴏᴅᴀᴅᴀᴋɪ ᴇɴ sɪɴɪʀ ʙᴏᴢᴜᴄᴜ ᴋɪşɪ ᴋɪᴍ?','ɢʀᴜᴘᴛᴀᴋɪ ᴇɴ ɢɪᴢᴇᴍʟɪ ᴋɪşɪ ᴋɪᴍ ?','ʜɪᴄ̧ sıʀғ ғᴀʏᴅᴀ sᴀɢ̆ʟᴀᴅıɢ̆ı ɪᴄ̧ɪɴ ʙɪʀɪʏʟᴇ ᴀʀᴋᴀᴅᴀş ᴋᴀʟᴅıɢ̆ıɴ ᴏʟᴅᴜ ᴍᴜ?','ʙᴜ ʜᴀʏᴀᴛᴛᴀ ʜɪᴄ̧ ᴋɪᴍsᴇʏᴇ sᴏ̈ʏʟᴇᴍᴇᴅɪɢ̆ɪɴ ʙɪʀ sıʀʀıɴ ᴠᴀʀ ᴍı?',
'ʙᴜ ᴏᴅᴀᴅᴀᴋɪ ᴇɴ sɪɴɪʀ ʙᴏᴢᴜᴄᴜ ᴋɪşɪ ᴋɪᴍ?','ʙɪʀ ᴜʏɢᴜʟᴀᴍᴀʏı ᴛᴇʟᴇғᴏɴᴜɴᴜᴢᴅᴀɴ sɪʟᴍᴇᴋ ᴢᴏʀᴜɴᴅᴀ ᴋᴀʟsᴀɴıᴢ ʜᴀɴɢɪsɪɴɪ sɪʟᴇʀᴅɪɴɪᴢ?','ᴇɴ sᴏɴ sᴏ̈ʏʟᴇᴅɪɢ̆ɪɴ ʏᴀʟᴀɴ ɴᴇᴅɪʀ?','ʙᴜ ɢʀᴜᴘᴛᴀ ᴋɪᴍsᴇɴɪɴ ᴀʀᴋᴀsıɴᴅᴀɴ ᴋᴏɴᴜşᴛᴜɴ ᴍᴜ ?','ᴄ̧ᴇşɪᴛʟɪ ʙᴀᴛıʟ ɪɴᴀɴᴄ̧ʟᴀʀıɴ ᴠᴀʀ ᴍı? ᴠᴀʀsᴀ ᴏɴʟᴀʀ ɴᴇʟᴇʀ?','ᴛᴇʟᴇғᴏɴᴜɴᴜᴢᴅᴀ ᴀʀᴀᴅıɢ̆ıɴ sᴏɴ şᴇʏ ɴᴇʏᴅɪ?','Bᴜ ɢʀᴜᴘᴛᴀ ᴋɪᴍsᴇɴɪɴ ᴀʀᴋᴀsıɴᴅᴀɴ ᴋᴏɴᴜşᴛᴜɴ ᴍᴜ ?','ᴍᴇᴠᴄᴜᴛ ᴇʀᴋᴇᴋ ᴀʀᴋᴀᴅᴀşıɴıɴ ʏᴀ ᴅᴀ ᴋıᴢ ᴀʀᴋᴀᴅᴀşıɴıɴ sᴇɴɪɴʟᴇ ᴀʏɴı ᴜ̈ɴɪᴠᴇʀsɪᴛᴇʏᴇ ɢɪᴛᴍᴇsɪɴɪ ɪsᴛᴇʀ ᴍɪsɪɴ?','ɢʀᴜᴘᴛᴀ ᴋɪᴍɪɴ ʜᴇsᴀʙıɴᴀ ɢɪʀᴍᴇᴋ ɪsᴛᴇʀsɪɴ?','ʙᴜ̈ʏᴜ̈ʏᴇɴ ʜᴀʏᴀʟɪ ʙɪʀ ᴀʀᴋᴀᴅᴀşıɴıᴢ ᴠᴀʀ ᴍıʏᴅı?','ᴍᴇᴠᴄᴜᴛ ᴇʀᴋᴇᴋ ᴀʀᴋᴀᴅᴀşıɴıɴ ʏᴀ ᴅᴀ ᴋıᴢ ᴀʀᴋᴀᴅᴀşıɴıɴ sᴇɴɪɴʟᴇ ᴀʏɴı ᴜ̈ɴɪᴠᴇʀsɪᴛᴇʏᴇ ɢɪᴛᴍᴇsɪɴɪ ɪsᴛᴇʀ ᴍɪsɪɴ?',
'ᴋᴀʀşı ᴄɪɴsᴛᴇ ɪʟᴋ ᴅɪᴋᴋᴀᴛɪɴɪ ᴄ̧ᴇᴋᴇɴ ɴᴇ?','ᴛᴇʟᴇғᴏɴᴜɴᴜᴢᴅᴀ ʜᴀɴɢɪ ᴜʏɢᴜʟᴀᴍᴀᴅᴀ ᴇɴ ᴄ̧ᴏᴋ ᴢᴀᴍᴀɴ ʜᴀʀᴄıʏᴏʀsᴜɴᴜᴢ?','şɪᴍᴅɪ sᴀɴᴀ ʙɪʀ ᴇᴠʟᴇɴᴍᴇ ᴛᴇᴋʟɪғɪ ɢᴇʟsᴇ ᴠᴇ sᴇᴠᴍᴇᴅɪɢ̆ɪɴ ʙɪʀɪ ᴏʟsᴀ, ᴠᴇ ʙᴜ sᴀɴᴀ sᴏɴ ɢᴇʟᴇᴄᴇᴋ ᴇᴠʟɪʟɪᴋ ᴛᴇᴋʟɪғɪ ᴏʟsᴀ ᴋᴀʙᴜʟ ᴇᴅᴇʀᴍɪʏᴅɪɴ?','ᴇʀᴋᴇᴋ ᴀʀᴋᴀᴅᴀşıɴ ᴠᴇʏᴀ ᴋıᴢ ᴀʀᴋᴀᴅᴀşıɴ sᴇɴɪ ʜɪᴄ̧ ᴜᴛᴀɴᴅıʀᴅı ᴍı?','ᴇɴ ᴛᴜʜᴀғ ᴛᴀᴋᴍᴀ ᴀᴅıɴ ɴᴇᴅɪʀ?','ʜɪᴄ̧ sıɴıғᴛᴀ ʀᴇᴢɪʟ ᴏʟᴅᴜɴ ᴍᴜ?','ɢʀᴜʙᴜɴ ɴᴇşᴇsɪ ᴋɪᴍ?','ʙɪʀ ᴜʏɢᴜʟᴀᴍᴀʏı ᴛᴇʟᴇғᴏɴᴜɴᴜᴢᴅᴀɴ sɪʟᴍᴇᴋ ᴢᴏʀᴜɴᴅᴀ ᴋᴀʟsᴀɴıᴢ ʜᴀɴɢɪsɪɴɪ sɪʟᴇʀᴅɪɴɪᴢ?','ʜᴀʏᴀᴛıɴᴅᴀ ʏᴀᴘᴛıɢ̆ıɴ ᴇɴ ᴄ̧ıʟɢıɴ şᴇʏ ɴᴇᴅɪʀ?','şɪᴍᴅɪ sᴀɴᴀ ʙɪʀ ᴇᴠʟᴇɴᴍᴇ ᴛᴇᴋʟɪғɪ ɢᴇʟsᴇ ᴠᴇ sᴇᴠᴍᴇᴅɪɢ̆ɪɴ ʙɪʀɪ ᴏʟsᴀ, ᴠᴇ ʙᴜ sᴀɴᴀ sᴏɴ ɢᴇʟᴇᴄᴇᴋ ᴇᴠʟɪʟɪᴋ ᴛᴇᴋʟɪғɪ ᴏʟsᴀ ᴋᴀʙᴜʟ ᴇᴅᴇʀᴍɪʏᴅɪɴ?',
'ʙᴇʏɴɪɴɪ ʙɪʀ ʀᴏʙᴏᴛᴀ ʏᴇʀʟᴇşᴛɪʀᴇʙɪʟɪʀ ᴠᴇ sᴏɴsᴜᴢᴀ ᴋᴀᴅᴀʀ ʙᴜ şᴇᴋɪʟᴅᴇ ʏᴀşᴀʏᴀʙɪʟsᴇᴅɪɴ,ʙᴜɴᴜ ʏᴀᴘᴀʀ ᴍıʏᴅıɴ?','Kᴀʀᴀɴʟıᴋᴛᴀɴ/ʏᴜ̈ᴋsᴇᴋʟɪᴋᴛᴇɴ ᴋᴏʀᴋᴀʀ ᴍısıɴ?','ᴇɴ ᴋᴏ̈ᴛᴜ̈ ɢʀᴜᴘ ʜᴀɴɢɪsɪᴅɪʀ?','ʜɪᴄ̧ sᴇᴠɢɪʟɪɴɪ ʙɪʀɪʏʟᴇ ᴀʟᴅᴀᴛᴛıɴ ᴍı?','ʜɪᴄ̧ sᴀʜᴛᴇ ᴋɪᴍʟɪᴋ ᴋᴜʟʟᴀɴᴅıɴ ᴍı?','ʙᴜ ɢʀᴜᴘᴅᴀ ᴇɴ ᴀᴢ ᴋɪᴍɪ sᴇᴠɪʏᴏʀsᴜɴ ᴠᴇ ɴᴇᴅᴇɴ?','ᴋᴜ̈ʟᴛᴜ̈ʀᴜ̈ᴍᴜ̈ᴢᴜ̈ɴ ᴇɴ ᴄ̧ᴏᴋ sᴇᴠᴅɪɢ̆ɪɴɪᴢ ʏᴀɴı ɴᴇᴅɪʀ?','ɢᴏ̈ʀᴅᴜ̈ɢ̆ᴜ̈ɴ ᴇɴ ɢᴀʀɪᴘ ʀᴜ̈ʏᴀ ɴᴇʏᴅɪ?','ᴀɪʟᴇɴɪɴ sᴇɴɪɴ ʜᴀᴋᴋıɴᴅᴀ ʙɪʟᴍᴇᴅɪɢ̆ɪɴᴇ sᴇᴠɪɴᴅɪɢ̆ɪɴ şᴇʏ ɴᴇᴅɪʀ?','ᴠᴜ̈ᴄᴜᴅᴜɴᴜɴ ʜᴀɴɢɪ ʙᴏ̈ʟᴜ̈ᴍʟᴇʀɪɴᴅᴇɴ ɢıᴅıᴋʟᴀɴıʏᴏʀsᴜɴ?','ʙᴜ ʜᴀʏᴀᴛᴛᴀ ʜɪᴄ̧ ᴋɪᴍsᴇʏᴇ sᴏ̈ʏʟᴇᴍᴇᴅɪɢ̆ɪɴ ʙɪʀ sıʀʀıɴ ᴠᴀʀ ᴍı?','ʙɪʀɪʏʟᴇ ᴄ̧ıᴋᴀʀᴋᴇɴ ʏᴀᴘᴛıɢ̆ıɴ ᴇɴ ᴜᴛᴀɴᴄ̧ ᴠᴇʀɪᴄɪ şᴇʏ ɴᴇʏᴅɪ?',
'ᴀʀᴋᴀᴅᴀşʟᴀʀıɴʟᴀ ʏᴀᴘᴍᴀʏı sᴇᴠᴅɪɢ̆ɪɴ ᴀᴍᴀ sᴇᴠɢɪʟɪɴɪɴ ᴏ̈ɴᴜ̈ɴᴅᴇ ᴀsʟᴀ ʏᴀᴘᴍᴀʏᴀᴄᴀɢ̆ıɴ şᴇʏ ɴᴇᴅɪʀ?','ᴜɴɪᴄᴏʀᴜɴ ᴍᴜ ᴏʟᴍᴀsıɴı ɪsᴛᴇʀᴅɪɴ ᴇᴊᴅᴇʀʜᴀɴ ᴍı?','şᴜ ᴀɴᴋɪ ʀᴜʜ ʜᴀʟɪɴᴇ ʙᴀᴋᴀʀᴀᴋ ɴᴇ ᴛᴜ̈ʀ ғɪʟᴍ ɪᴢʟᴇʀsɪɴ (ᴀᴋsɪʏᴏɴ/ᴅʀᴀᴍ/ʙɪʟɪᴍ ᴋᴜʀɢᴜ/ʀᴏᴍᴀɴᴛɪᴋ ᴋᴏᴍᴇᴅɪ/ʙɪʏᴏɢʀᴀғɪ/ғᴀɴᴛᴀsᴛɪᴋ)','ᴡᴇʙ ɢᴇᴄ̧ᴍɪşɪɴɪᴢɪ, ʙɪʀɪʟᴇʀɪ ɢᴏ̈ʀᴜ̈ʀsᴇ ᴜᴛᴀɴᴀᴄᴀɢ̆ıɴıᴢ şᴇʏ ɴᴇ ᴏʟᴜʀᴅᴜ?','ʜɪᴄ̧ sᴇᴠɢɪʟɪɴɪ ᴀʟᴅᴀᴛᴍᴀʏı ᴅᴜ̈şᴜ̈ɴᴅᴜ̈ɴ ᴍᴜ̈?','ʙɪʀɪsɪ ᴋıᴢ ᴀʀᴋᴀᴅᴀşıɴ / ᴇʀᴋᴇᴋ ᴀʀᴋᴀᴅᴀşıɴᴅᴀɴ ᴀʏʀıʟᴍᴀᴋ ɪᴄ̧ɪɴ sᴀɴᴀ 𝟷 ᴍɪʟʏᴏɴ ᴛʟ ᴏ̈ɴᴇʀsᴇʏᴅɪ, ʏᴀᴘᴀʀ ᴍıʏᴅıɴ?','ɪ̇ɴsᴀɴʟᴀʀıɴ sᴇɴɪɴ ʜᴀᴋᴋıɴᴅᴀ ʙɪʟᴍᴇsɪɴɪ ɪsᴛᴇᴅɪɢ̆ɪɴ şᴇʏ ɴᴇᴅɪʀ?','ʙᴜ ɢʀᴜᴘᴛᴀ ᴋɪᴍsᴇɴɪɴ ᴀʀᴋᴀsıɴᴅᴀɴ ᴋᴏɴᴜşᴛᴜɴ ᴍᴜ ?','şɪᴍᴅɪʏᴇ ᴋᴀᴅᴀʀ ɢᴏ̈ʀᴅᴜ̈ɢ̆ᴜ̈ᴍ ᴇɴ ɢᴀʀɪᴘ ʀᴜ̈ʏᴀʏı ᴀɴʟᴀᴛ.',
'şɪᴍᴅɪʏᴇ ᴋᴀᴅᴀʀ ʙɪʀ ʙᴀşᴋᴀsıɴᴀ sᴏ̈ʏʟᴇᴅɪɢ̆ɪɴ ᴇɴ ᴀᴄıᴍᴀsıᴢᴄᴀ şᴇʏ ɴᴇʏᴅɪ?','ᴅᴜ̈ɴʏᴀᴅᴀᴋɪ ʜᴇʀʜᴀɴɢɪ ʙɪʀɪɴɪ ᴛᴜ̈ʀᴋɪʏᴇ’ɴɪɴ ʙᴀşᴋᴀɴı ʏᴀᴘᴀʙɪʟsᴇʏᴅɪɴ ʙᴜ ᴋɪᴍ ᴏʟᴜʀᴅᴜ?','ᴀɪʟᴇɴɪᴢɪɴ ᴜʏɢᴜʟᴀᴅıɢ̆ı ᴇɴ ᴛᴜʜᴀғ ɢᴇʟᴇɴᴇᴋ ɴᴇᴅɪʀ?','ʙɪʀɪsɪ ᴋıᴢ ᴀʀᴋᴀᴅᴀşıɴ / ᴇʀᴋᴇᴋ ᴀʀᴋᴀᴅᴀşıɴᴅᴀɴ ᴀʏʀıʟᴍᴀᴋ ɪᴄ̧ɪɴ sᴀɴᴀ 𝟷 ᴍɪʟʏᴏɴ ᴛʟ ᴏ̈ɴᴇʀsᴇʏᴅɪ, ʏᴀᴘᴀʀ ᴍıʏᴅıɴ?','ᴋᴜ̈ʟᴛᴜ̈ʀᴜ̈ᴍᴜ̈ᴢᴜ̈ɴ ᴇɴ ᴄ̧ᴏᴋ sᴇᴠᴅɪɢ̆ɪɴɪᴢ ʏᴀɴı ɴᴇᴅɪʀ?','ɢʀᴜᴘᴛᴀ ᴋɪ ᴋᴀɴᴋᴀʟᴀʀıɴı ᴇᴛɪᴋᴇᴛʟᴇʀ ᴍɪsɪɴ ?','ᴅɪʀsᴇɢ̆ɪɴɪ ʏᴀʟᴀʏᴀʙɪʟɪʀ ᴍɪsɪɴ?','ᴋᴀᴅıɴ/ᴇʀᴋᴇᴋ ᴏʟᴍᴀɴıɴ ᴇɴ ᴋᴏ̈ᴛᴜ̈ ᴠᴇ ᴇɴ ɪʏɪ ʏᴀɴı ɴᴇᴅɪʀ?','Hᴀʏᴀᴛᴛᴀ ᴜɴᴜᴛᴍᴀᴅıɢ̆ıɴ ʙɪʀɪ ᴠᴀʀ ᴍı?','ᴀʟışᴠᴇʀɪşɪɴ ᴅɪʙɪɴᴇ ᴠᴜʀᴜʀᴋᴇɴ ᴇɴ ᴄ̧ᴏᴋ ʜᴀʀᴄᴀᴍᴀ ʏᴀᴘᴛıɢ̆ıɴ ɢᴜ̈ɴ ʜᴀɴɢɪsɪʏᴅɪ?','ʙᴜ ɢʀᴜᴘᴛᴀ ᴋɪᴍsᴇɴɪɴ ᴀʀᴋᴀsıɴᴅᴀɴ ᴋᴏɴᴜşᴛᴜɴ ᴍᴜ ?',
'ᴋᴇɴᴅɪɴɪ ᴇɴ ᴇᴢɪᴋ ʜɪssᴇᴛᴛɪɢ̆ɪɴ ᴀɴ ʜᴀɴɢɪsɪʏᴅɪ ?','ᴏʏᴜɴᴜ ᴏʏɴᴀʏᴀɴ ᴏʏᴜɴᴄᴜ ɢʀᴜʙᴜɴᴅᴀ ʏᴇʀ ᴀʟᴀɴʟᴀʀᴅᴀɴ ᴋɪᴍɪ ᴏ̈ᴘᴍᴇᴋ ɪsᴛᴇʀsɪɴ?','ʜɪᴄ̧ ʏᴀsᴀʏᴀ ᴀʏᴋıʀı ʙɪʀ şᴇʏʟᴇʀ ʏᴀᴘᴛıɢ̆ıɴ ᴏʟᴅᴜ ᴍᴜ?','ʜᴀʏᴀᴛıɴıɴ ɢᴇʀɪ ᴋᴀʟᴀɴıɴᴅᴀ sᴀᴅᴇᴄᴇ ʙɪʀ ᴋıʏᴀғᴇᴛ ɢɪʏᴇʙɪʟsᴇʏᴅɪɴ, ʙᴜ ᴋıʏᴀғᴇᴛɪɴ ʜᴀɴɢɪ ʀᴇɴᴋ ᴏʟᴜʀᴅᴜ?','şɪᴍᴅɪʏᴇ ᴋᴀᴅᴀʀ ʙᴀşᴋᴀsıɴᴀ sᴏ̈ʏʟᴇᴅɪɢ̆ɪɴ ᴇɴ ᴀɴʟᴀᴍʟı şᴇʏ ɴᴇʏᴅɪ?','ɢʀᴜᴘᴛᴀ ʙᴜʟᴜɴᴀɴ ᴇɴ ᴜʏᴜᴢ ᴋɪşɪ ᴋɪᴍ ?','ᴋɪᴍsᴇɴɪɴ sᴇɴɪɴ ʜᴀᴋᴋıɴᴅᴀ ʙɪʟᴍᴇᴅɪɢ̆ɪ ʙɪʀ şᴇʏ ɴᴇᴅɪʀ?','ʜɪᴄ̧ sıɴıғᴛᴀ ᴜʏᴜᴅᴜɴ ᴍᴜ?','ʜɪᴄ̧ ʏᴀsᴀʏᴀ ᴀʏᴋıʀı ʙɪʀ şᴇʏʟᴇʀ ʏᴀᴘᴛıɢ̆ıɴ ᴏʟᴅᴜ ᴍᴜ?','şɪᴍᴅɪʏᴇ ᴋᴀᴅᴀʀ ɢᴏ̈ʀᴅᴜ̈ɢ̆ᴜ̈ᴍ ᴇɴ ɢᴀʀɪᴘ ʀᴜ̈ʏᴀʏı ᴀɴʟᴀᴛ','ᴛᴏᴘʟᴜᴍᴅᴀ ᴇɴ ᴜᴛᴀɴᴄ̧ ᴠᴇʀɪᴄɪ ᴀɴıɴıᴢ ɴᴇʏᴅɪ?','ᴋᴀʀşı ᴄɪɴsᴛᴇ ɪʟᴋ ᴅɪᴋᴋᴀᴛɪɴɪ ᴄ̧ᴇᴋᴇɴ ɴᴇ?','ɪ̇ʟᴋ ɪşɪɴ ɴᴇʏᴅɪ?',
'Bu Grupta En Çok Sevdiğin Kişi Kimdir ...','En Çok Gitmek İstediğin Ülke Neresidir ...','Medeni Halin Nedir ...','Özlediğin Bir Kimse Var Mı ...','Fotojenik Misin Kanka ...','Dans Etmeyi Sever Misin ...','Eski Sevgilinin Adı Ne ...','En Sevdigin Film Hangisi ...','En Sevdiğin Sanatçı Kim ...','Ünlü veya Fenomen Olmak İster Misin ...','Gözlerinin Rengi Nedir ...','Boyun Kaç Santim :)',
'Bugün için Bir Planın Var Mı ...','Birini Kahraman Yapan Nedir ...','Bir Dilek Hakkın Olsa Ne Dilerdim ...','Çocukken En Büyük Hayalin Neydi ...','Aşka İnanır Mısın ...','Bir Hedefin Var Mı ...','Karanlıktan Korkar Misin ...','Müzik Dinlemeyi Sever Misin ...','Sizce Anlaşılmak Kolay Mı ...','En Sevdiğin Ders Nedir ...','Nabiyosun Aslanım ...',
'Bu Grupta Sevdiğin Birini Etiketle ...','Bu Gruptaki En Yakışıklı Kişiyi Etiketleyin ...','Bu Gruptaki En Güzel Kız Kim ...','Sizce Gruptaki En Akıllı Kişi Kim ...','Kadere İnanır Mısın ...','Hayatından Memnun Musun ...','Hey, Sen Çok Şanslısın ...','En sevdiğin Ninja Kaplumbağa hangisiydi ...','Güliver olsaydın devler ülkesine mi yoksa cüceler ülkesine mi düşmek isterdin ...',
'En sevdiğin Pokemon hangisi ...','Çocukken izlemeyi en çok sevdiğin çizgi filmler hangileriydi ...','Dünyaya bir dahaki gelişinde hayvan olarak gelseydin hangi hayvan olmak isterdin ...','Bir şiir olsaydın hangi şiir olurdun ...','En sevdiğin Ninja Kaplumbağa hangisiydi ...','Issız bir adaya düşseydin yanına kesinlikle ‘’almayacağın’’ üç şey ne olurdu ...','Küçükken hiç pembe dizi izledin mi, İzlediysen hangisi ...',
'Sihirli bir değneğin olsaydı öncelikle neyi değiştirirdin ...','Arkadaşının sırrını 1 milyon dolar karşılığında ifşa eder miydin ...','Bir dizinin içine ışınlanmak isteseydin bu hangi dizi olurdu ...','Filmlerdeki kötü karakterlerden biri olsaydın hangisi olurdun ...','Küçükken oynamayı en sevdiğin atari oyunu hangisiydi ...','Şu an okuduğun iyi bir kitap var mı , Öneriyor musun ...','Hangi dizileri izliyorsun ...','En son hangi filmi izledin ...',
'Telefonunuzda olmadan yaşayamayacağınız herhangi bir uygulama var mı ...','Hayatın geri kalanında sadece bir film türünü izleyebiliceksen, ne olurdu ...','Herkesin sevdiği sizin nefret ettiğiniz bir kitap var mı, ya da tam tersi ...','Seni ağlatan en son film ne oldu, veya yüksek sesle güldüren ...','İnstagramda kesin takip et dediğin birisi var mı ...','En sevdiğin kitabın ismi ne ...','En son hangi diziyi tek oturuşta bitirdin ...',
'Çocukluğunda en sevdiğin çizgi film hangisiydi ...','Çocukluğunda en sevdiğin çizgi film karakteri hangisiydi ...','İzlemeyi en çok sevdiğin film türü ne ...','Telefonunun ekran süresi ortalama kaç saat ...','Spor yapmayı sever misin ...','Voleybol maçları izler misin ...','Sevdiğin spor dalı ne ...','Çocukken aşık olduğun kurgusal bir karakter var mıydı ...','Sonsuza kadar sadece bir kitap okuyacak olsan bu hangi kitap olurdu ...',
'En sevdiğin distopik eser hangisi ...','Hangi tür kitaplar okumayı seviyorsun ...','Kahve içmek istediğin kitap karakteri var mı ...','Takip ettiğin bir influencer var mı ...','En çok hangi influencerın önerdiği ürünleri kullanıyorsun ...','Okurken ağlamana  neden olacak bir kitap oldu mu ...','En sevdiğin yazar kim ...','En çok hangi dijital platformu kullanıyorsun ...',
'Hayatta gerçekleştirmek istediğin bir hayalin var mı?', 'Kaç tane kız aradaşın oldu ?','Nefret ettiğiniz ancak yine de kullandığın bir uygulama var mı?','En tuhaf korkun nedir?','Hangi takımı tutuyorsun ?','Romayı senmi yaktın?','Fiziksel olarak sana en acı veren deneyimin ne oldu?','Hangi yılda doğdun?','Boyun kaç ?','En sevdiğin hobi nedir?','Nasılsın ?','Gruptaki gizli aşık olduğun kim?',
'Nerelisin?','Naber nasıl gidiyor?','Grupta nefret ettiğin kişi kim?','Kaç tane sevgilin oldu?','Gruptaki partnerin kim?','Kendini 3 kelime ile anlatırmısın','Selam ne yapıyorsun?','En son okuduğun kitabın adı neydi','Grubu yakacakmışsın doğru mu?','En sevdiğin müzik nedir?','Googlede en son neye baktın?','Okumayı en çok sevdiğin kitap türü nedir ...','Çocukluğundan unutmadığın bir çizgi film var mı ...',
'Aşk mı? para mı?','En son yaptığın en saçma olay neydi?','Keşke şu olsada yesek dediğin şey neydi?','Karşı cinste aradığın krater nedir?','Karşı cinsin ilk neresine bakıyorsun?','Grupta sevdiğin 3 kişiyi etiketler misin?','Grupta en sevmediğin 3 kişiyi etiketler misin?','Grupta işte aradığım eş adayı dediğin kişiyi etiketler misin?','En Sevdiğin Renk Nedir ...',
'Aşkın yaşı yoktur diyorlar doğru mu?','Bir adaya düşsen yanına alacağın üç şey ne olurdu?','Grupta sevgilin var mı?','İnstagrama günde kaç story atıyorsun?','Hangi şehirde yaşıyorsun','Şehrini üç kelime ile anlatır mısın?','Memleketini üç kelime ile anlatır mısın?','Geçmişe dönüp yaşadığın bir olayı silebilmen mümkün olsaydı hangi olay olurdu?',
'ʙɪʀ ᴀʏɴᴀɴıɴ ᴏ̈ɴᴜ̈ɴᴅᴇ ʏᴀᴘᴛıɢ̆ıɴ ᴇɴ ᴄ̧ıʟɢıɴᴄᴀ şᴇʏ ɴᴇᴅɪʀ?','ɪ̇ɴsᴀɴʟᴀʀıɴ sɪᴢᴇ ɴᴇ sᴏʀᴍᴀsıɴᴅᴀɴ ʙıᴋᴛıɴıᴢ?ɢɪᴢʟɪᴅᴇɴ ɢɪᴢʟɪᴅᴇɴ sᴀᴅᴇᴄᴇ ᴏɴᴜɴ ɪᴄ̧ɪɴ ɢᴇʟᴅɪɢ̆ɪɴ ᴋɪᴍsᴇ ᴠᴀʀ ᴍı ɢʀᴜᴘᴛᴀ ?','ʜɪᴄ̧ ᴋɪᴍsᴇʏɪ ᴏ̈ᴢᴇʟᴅᴇɴ ʀᴀʜᴀᴛsıᴢ ᴇᴛᴛɪɴ ᴍɪ?','ɪ̇ɴsᴀɴʟᴀʀı ʏᴀɴᴀɴ ʙɪʀ ʙɪɴᴀᴅᴀɴ ᴋᴜʀᴛᴀʀıʏᴏʀ ᴏʟsᴀʏᴅıɴıᴢ ᴠᴇ ʙɪʀ ᴋɪşɪʏɪ ʙᴜ ɢʀᴜᴘᴅᴀɴ ɢᴇʀɪᴅᴇ ʙıʀᴀᴋᴍᴀᴋ ᴢᴏʀᴜɴᴅᴀ ᴋᴀʟıʀsᴀɴıᴢ, ᴋɪᴍ ᴏʟᴜʀᴅᴜ?','ʏᴇʀᴅᴇɴ ʙɪʀ şᴇʏɪ ᴀʟıᴘ ʜɪᴄ̧ ʏᴇᴅɪɴ ᴍɪ?','ɢʀᴜᴘᴛᴀ ᴋɪ ᴜ̈ᴄ̧ ᴋᴀɴᴋᴀɴı ᴇᴛɪᴋᴇᴛʟᴇʀ ᴍɪsɪɴ?','ᴋᴀʀᴀɴʟıᴋᴛᴀɴ/ʏᴜ̈ᴋsᴇᴋʟɪᴋᴛᴇɴ ᴋᴏʀᴋᴀʀ ᴍısıɴ?','ɢʀᴜʙᴜɴ ᴇɴ ʏᴀᴋışıᴋʟısı ᴋɪᴍ ?','ʀᴇᴀʟ ʜᴀʏᴀᴛᴛᴀ ᴛᴀɴıᴍᴀᴋ ɪsᴛᴇᴅɪɢ̆ɪɴ ᴋɪᴍsᴇ ᴠᴀʀ ᴍı ɢʀᴜᴘᴛᴀ ?','ɢʀᴜʙᴜɴ ᴇɴ ʏᴀᴋışıᴋʟısı ᴋɪᴍ ?','ᴄ̧ıᴋᴛıɢ̆ıɴ ᴇɴ ʏᴀşʟı ᴋɪşɪ ᴋɪᴍ?','ɢʀᴜʙᴜɴ ᴇɴ ɢᴜ̈ᴢᴇʟ ᴋıᴢı ᴋɪᴍ ?',
'ɢʀᴜᴘᴛᴀ ᴀᴅᴍɪɴ ᴏʟsᴀɴ ᴋɪᴍɪ ʙᴀɴʟᴀʀᴅıɴ ɴᴇᴅᴇɴ ?','ʜᴀғᴛᴀᴅᴀ ᴋᴀᴄ̧ ᴋᴇᴢ ᴀʏɴı ᴘᴀɴᴛᴏʟᴏɴᴜ ɢɪʏɪʏᴏʀsᴜɴ?','ᴀɪʟᴇɴɪᴢɪɴ ᴜʏɢᴜʟᴀᴅıɢ̆ı ᴇɴ ᴛᴜʜᴀғ ɢᴇʟᴇɴᴇᴋ ɴᴇᴅɪʀ?','ᴋᴇɴᴅɪɴɪ ᴇɴ ᴇᴢɪᴋ ʜɪssᴇᴛᴛɪɢ̆ɪɴ ᴀɴ ʜᴀɴɢɪsɪʏᴅɪ ?','ɢʀᴜᴘᴛᴀ ɴᴇғʀᴇᴛ ᴇᴛᴛɪɢ̆ɪɴ ʙɪʀɪ ᴠᴀʀ ᴍı?','ʙᴜʀᴅᴀ ᴋɪ ᴋɪᴍsᴇʏᴇ ʏᴀʟᴀɴ sᴏ̈ʏʟᴇᴅɪɴ ᴍɪ?','ʙɪʀ ɪʟɪşᴋɪᴅᴇᴋɪ ᴇɴ ʙᴜ̈ʏᴜ̈ᴋ ᴋᴏʀᴋᴜɴ ɴᴇᴅɪʀ?','ʙᴜ ʜᴀʏᴀᴛᴛᴀ ʜɪᴄ̧ ᴋɪᴍsᴇʏᴇ sᴏ̈ʏʟᴇᴍᴇᴅɪɢ̆ɪɴ ʙɪʀ sıʀʀıɴ ᴠᴀʀ ᴍı?','ɢʀᴜʙᴜɴ ᴏʟᴍᴀᴢsᴀ ᴏʟᴍᴀᴢ ᴅᴇᴅɪɢ̆ɪɴ şᴇʏɪ ɴᴇᴅɪʀ?','ɢʀᴜᴘᴛᴀᴋɪ sıʀᴅᴀşıɴ ᴋɪᴍ ?','ɢʀᴜʙᴜ ɴᴇ ᴋᴀᴅᴀʀ sᴇᴠɪʏᴏʀsᴜɴ ?','sᴀᴄ̧ʟᴀʀıɴı ᴜᴢᴀᴛᴍᴀʏı ᴅᴜ̈şᴜ̈ɴsᴇɴ ɴᴇ ᴋᴀᴅᴀʀ ᴜᴢᴀᴛıʀᴅıɴ?','ᴋᴇşᴋᴇ ᴏɴᴜɴ ʜᴀᴋᴋıɴᴅᴀ ʏᴀʟᴀɴ sᴏ̈ʏʟᴇsᴇʏᴅɪᴍ ᴅᴇᴅɪɢ̆ɪɴ şᴇʏ ɴᴇᴅɪʀ?','ɢʀᴜʙᴜɴ ᴇɴ ᴇɢᴏɪsᴛɪ ᴋɪᴍ ?','sᴏɴ ᴀᴛᴛıɢ̆ıɴ ᴍᴇsᴀᴊ ɴᴇʏᴅɪ?',
'ɢʀᴜᴘᴛᴀᴋɪ ᴇɴ sᴇᴠɢɪɢ̆ɪɴ ᴀᴅᴍɪɴ ᴋɪᴍ ?','ᴇɴ ᴜᴛᴀɴ ᴠᴇʀɪᴄɪ ᴋɪşɪsᴇʟ ʙᴀᴋıᴍ ᴀʟışᴋᴀɴʟıɢ̆ıɴ ɴᴇᴅɪʀ?','ɢʀᴜʙᴜ ɴᴇ ᴋᴀᴅᴀʀ sᴇᴠɪʏᴏʀsᴜɴ ?','ɢʀᴜᴘᴛᴀ ɴᴇʏɪ ᴅᴇɢ̆ɪşᴛɪʀᴍᴇᴋ ɪsᴛᴇʀᴅɪɴ?','ɪ̇ʟᴋ ɪşɪɴ ɴᴇʏᴅɪ?','ᴀɪʟᴇɴᴅᴇɴ ʙɪʀɪ sᴇɴɪ ʙᴜ ɢʀᴜᴘᴛᴀ ɢᴏ̈ʀsᴇ ɴᴇ ᴏʟᴜʀ ?','ɢʀᴜᴘᴛᴀ ɴᴇғʀᴇᴛ ᴇᴛᴛɪɢ̆ɪɴ ʙɪʀɪ ᴠᴀʀ ᴍı?','ᴋᴇɴᴅɪ ɢᴏ̈ʀᴜ̈ɴᴜşᴜ̈ɴᴜ̈ 𝟷 ɪʟᴇ 𝟷𝟶 ᴀʀᴀsıɴᴅᴀ ᴘᴜᴀɴʟᴀ :)','ʙɪʀ ᴏᴅᴀᴅᴀ ᴜᴢᴜɴ ʙɪʀ sᴜ̈ʀᴇ ʜᴀᴘsᴏʟᴀᴄᴀɢ̆ıɴı ᴅᴜ̈şᴜ̈ɴsᴇɴ ʏᴀɴıɴᴅᴀ ᴏʟᴍᴀsıɴı ɪsᴛᴇᴅɪɢ̆ɪɴ ᴜ̈ᴄ̧ şᴇʏ ɴᴇ ᴏʟᴜʀᴅᴜ?','ᴇɴ sᴏɴ ɴᴇ ᴢᴀᴍᴀɴ ʜᴜ̈ɴɢᴜ̈ʀ ʜᴜ̈ɴɢᴜ̈ʀ ᴀɢ̆ʟᴀᴅıɢ̆ıɴı ʜᴀᴛıʀʟıʏᴏʀ ᴍᴜsᴜɴ?','ɢʀᴜᴘᴛᴀ ʙᴜʟᴜɴᴀɴ ᴇɴ ᴜʏᴜᴢ ᴋɪşɪ ᴋɪᴍ ?','ᴋᴜʀᴛ ᴍᴜ ᴋᴇʟɪᴍᴇ ᴏʏᴜɴᴜ ᴍᴜ ?','ɢʀᴜᴘᴛᴀ ᴋɪᴍᴅᴇɴ ɢıᴄıᴋ ᴀʟıʏᴏʀsᴜɴ?','ɢʀᴜᴘᴛᴀ ᴏʟᴍᴀᴍᴀsıɴı ɪsᴛᴇᴅɪɢ̆ɪɴ ᴋɪşɪʏɪ ᴇᴛɪᴋᴇᴛʟᴇʀ ᴍɪsɪɴ?',
'ᴀᴋʀᴀʙᴀʟᴀʀıɴᴅᴀɴ ᴋɪᴍsᴇʏɪ ᴅᴀᴠᴇᴛ ᴇᴛᴛɪɴ ᴍɪ ɢʀᴜʙᴀ ?','ʜɪᴄ̧ ᴏᴋᴜʟᴅᴀ ᴋᴀᴠɢᴀ ᴇᴛᴛɪɴ ᴍɪ?','ʙɪʀɪɴɪɴ ᴛᴇʟᴇғᴏɴᴜɴᴅᴀ ɢᴏ̈ʀᴅᴜ̈ɢ̆ᴜ̈ɴ ᴇɴ ᴛᴜʜᴀғ şᴇʏ ɴᴇᴅɪʀ?','ɢʀᴜᴘ sᴇɴɪɴ ɪᴄ̧ɪɴ ɴᴇ ɪғᴀᴅᴇ ᴇᴅɪʏᴏʀ?','ɢʀᴜʙᴜɴ ᴇɴ ᴇɢᴏɪsᴛɪ ᴋɪᴍ ?','ʜɪᴄ̧ sıʀғ ғᴀʏᴅᴀ sᴀɢ̆ʟᴀᴅıɢ̆ı ɪᴄ̧ɪɴ ʙɪʀɪʏʟᴇ ᴀʀᴋᴀᴅᴀş ᴋᴀʟᴅıɢ̆ıɴ ᴏʟᴅᴜ ᴍᴜ?','ᴇɴ ᴛᴜʜᴀғ ᴋᴏʀᴋᴜɴᴜᴢ ɴᴇᴅɪʀ?','ᴋᴜʀᴛ ᴏʏᴜɴᴜɴᴜ sᴇᴠɪʏᴏʀ ᴍᴜsᴜɴ?','ᴇɴ sᴏɴ ɴᴇ ᴢᴀᴍᴀɴ ᴅɪşʟᴇʀɪɴɪ ғıʀᴄ̧ᴀʟᴀᴅıɴ?','ʜɪᴄ̧ ʏᴀşıɴ ʜᴀᴋᴋıɴᴅᴀ ʏᴀʟᴀɴ sᴏ̈ʏʟᴇᴅɪɴ ᴍɪ?','ɢʀᴜᴘᴛᴀ ᴋᴇşᴋᴇ ᴀʙɪᴍ/ᴀʙʟᴀᴍ ᴏʟsᴀʏᴅı ᴅᴇᴅɪɢ̆ɪɴ ᴋɪᴍsᴇ ᴠᴀʀ ᴍı ?','ʙɪʀ ʙᴏ̈ᴄᴇᴋ ɪsᴛɪʟᴀsı ɢᴇʀᴄ̧ᴇᴋʟᴇşsᴇ ʜᴀɴɢɪ ᴀʀᴋᴀᴅᴀşıɴ ʜᴀʏᴀᴛᴛᴀ ᴋᴀʟᴍᴀʏı ʙᴀşᴀʀıʀ?','ɢʀᴜᴘᴛᴀ ᴏʟᴍᴀᴍᴀsıɴı ɪsᴛᴇᴅɪɢ̆ɪɴ ᴋɪşɪʏɪ ᴇᴛɪᴋᴇᴛʟᴇʀ ᴍɪsɪɴ?','ʙᴜ ʜᴀʏᴀᴛᴛᴀ sᴇɴɪ ᴇɴ ᴄ̧ᴏᴋ ᴋıᴢᴅıʀᴀɴ şᴇʏ ɴᴇᴅɪʀ?',
'ᴇɴ ɪʏɪ ᴀʀᴋᴀᴅᴀşıɴıɴ sᴇɴɪɴʟᴇ ᴀʏɴı ᴜ̈ɴɪᴠᴇʀsɪᴛᴇʏᴇ ɢɪᴛᴍᴇsɪɴɪ ɪsᴛᴇʀ ᴍɪsɪɴ?','ᴇʀᴋᴇᴋ ᴀʀᴋᴀᴅᴀşıɴ ᴠᴇʏᴀ ᴋıᴢ ᴀʀᴋᴀᴅᴀşıɴ sᴇɴɪ ʜɪᴄ̧ ᴜᴛᴀɴᴅıʀᴅı ᴍı?','ɢʀᴜʙᴜ ɢᴇʀᴄ̧ᴇᴋᴛᴇɴ sᴇᴠɪʏᴏʀ ᴍᴜsᴜɴ?','ʙɪʀ ᴏᴅᴀᴅᴀ ᴜᴢᴜɴ ʙɪʀ sᴜ̈ʀᴇ ʜᴀᴘsᴏʟᴀᴄᴀɢ̆ıɴı ᴅᴜ̈şᴜ̈ɴsᴇɴ ʏᴀɴıɴᴅᴀ ᴏʟᴍᴀsıɴı ɪsᴛᴇᴅɪɢ̆ɪɴ ᴜ̈ᴄ̧ şᴇʏ ɴᴇ ᴏʟᴜʀᴅᴜ?','ʜᴀᴛıʀʟᴀᴅıɢ̆ıɴ ᴋᴀᴅᴀʀıʏʟᴀ ɪʟᴋ ᴀşıᴋ ᴏʟᴅᴜɢ̆ᴜɴ ᴜ̈ɴʟᴜ̈ ᴋɪᴍᴅɪ?','sᴏ̈ʏʟᴇᴅɪɢ̆ɪɴɪᴢ ᴠᴇʏᴀ ʏᴀᴘᴛıɢ̆ıɴıᴢ ʙɪʀ şᴇʏɪ sɪʟᴍᴇᴋ ɪᴄ̧ɪɴ ᴢᴀᴍᴀɴᴅᴀ ɢᴇʀɪʏᴇ ɢɪᴅᴇʙɪʟsᴇʏᴅɪɴɪᴢ, ʙᴜ ʜᴀɴɢɪ ʏıʟ ᴏʟᴜʀᴅᴜ?','ʙᴜ ɢʀᴜᴘᴅᴀᴋɪ sıʀ ᴛᴜᴛᴍᴀ  ᴋᴏɴᴜsᴜɴᴅᴀ ᴇɴ ᴄ̧ᴏᴋ ᴢᴏʀʟᴀɴᴀɴ ᴋɪşɪ ᴋɪᴍᴅɪʀ?','sᴇɴ ᴀᴅᴍɪɴ ᴏʟsᴀɴ ɴᴇʏɪ ᴅᴇɢ̆ɪşᴛɪʀɪʀᴅɪɴ ?','ɪ̇ʟᴋ ɪşɪɴ ɴᴇʏᴅɪ?','ɢʀᴜʙᴜ ɢᴇʀᴄ̧ᴇᴋᴛᴇɴ sᴇᴠɪʏᴏʀ ᴍᴜsᴜɴ?','ɢʀᴜᴘᴛᴀ ʜᴏşʟᴀɴᴅıɢ̆ıɴ ʙɪʀɪ ᴠᴀʀ ᴍı ?',
'ᴀɪʟᴇɴɪᴢɪɴ ᴜʏɢᴜʟᴀᴅıɢ̆ı ᴇɴ ᴛᴜʜᴀғ ɢᴇʟᴇɴᴇᴋ ɴᴇᴅɪʀ?','ʙɪʀ ʙᴏ̈ᴄᴇᴋ ɪsᴛɪʟᴀsı ɢᴇʀᴄ̧ᴇᴋʟᴇşsᴇ ʜᴀɴɢɪ ᴀʀᴋᴀᴅᴀşıɴ ʜᴀʏᴀᴛᴛᴀ ᴋᴀʟᴍᴀʏı ʙᴀşᴀʀıʀ?','ʙɪʀ ᴏᴅᴀᴅᴀ ᴜᴢᴜɴ ʙɪʀ sᴜ̈ʀᴇ ʜᴀᴘsᴏʟᴀᴄᴀɢ̆ıɴı ᴅᴜ̈şᴜ̈ɴsᴇɴ ʏᴀɴıɴᴅᴀ ᴏʟᴍᴀsıɴı ɪsᴛᴇᴅɪɢ̆ɪɴ ᴜ̈ᴄ̧ şᴇʏ ɴᴇ ᴏʟᴜʀᴅᴜ?','ʜᴀɴɢɪ ᴄ̧ᴏᴄᴜᴋ ғɪʟᴍɪɴɪ ᴛᴇᴋʀᴀʀ ᴛᴇᴋʀᴀʀ ɪᴢʟᴇʏᴇʙɪʟɪʀsɪɴ?','ʙᴜ ʜᴀʏᴀᴛᴛᴀᴋɪ ᴇɴ ʙᴜ̈ʏᴜ̈ᴋ ɢᴜ̈ᴠᴇɴsɪᴢʟɪɢ̆ɪɴ ɴᴇᴅɪʀ?','ʙɪʀ ᴜ̈ɴʟᴜ̈ ɪɴsᴛᴀɢʀᴀᴍ’ᴅᴀ sᴇɴɪ ᴛᴀᴋɪᴘ ᴇᴛsᴇʏᴅɪ ʙᴜ ᴜ̈ɴʟᴜ̈ɴᴜ̈ɴ ᴋɪᴍ ᴏʟᴍᴀsıɴı ɪsᴛᴇʀᴅɪɴ?','ʜɪᴄ̧ sıʀғ ғᴀʏᴅᴀ sᴀɢ̆ʟᴀᴅıɢ̆ı ɪᴄ̧ɪɴ ʙɪʀɪʏʟᴇ ᴀʀᴋᴀᴅᴀş ᴋᴀʟᴅıɢ̆ıɴ ᴏʟᴅᴜ ᴍᴜ?','ᴜɴɪᴄᴏʀᴜɴ ᴍᴜ ᴏʟᴍᴀsıɴı ɪsᴛᴇʀᴅɪɴ ᴇᴊᴅᴇʀʜᴀɴ ᴍı?','ɢʀᴜᴘᴛᴀ ᴀᴅᴍɪɴ ᴏʟsᴀɴ ᴋɪᴍɪ ʙᴀɴʟᴀʀᴅıɴ ɴᴇᴅᴇɴ ?','ɪ̇ɴsᴀɴʟᴀʀıɴ sᴇɴɪɴ ʜᴀᴋᴋıɴᴅᴀ ʙɪʟᴍᴇsɪɴɪ ɪsᴛᴇᴅɪɢ̆ɪɴ şᴇʏ ɴᴇᴅɪʀ?',
'ɢʀᴜᴘᴛᴀ ᴋɪᴍᴅᴇɴ ɢıᴄıᴋ ᴀʟıʏᴏʀsᴜɴ?','ᴍᴇᴠᴄᴜᴛ ᴇʀᴋᴇᴋ ᴀʀᴋᴀᴅᴀşıɴıɴ ʏᴀ ᴅᴀ ᴋıᴢ ᴀʀᴋᴀᴅᴀşıɴıɴ sᴇɴɪɴʟᴇ ᴀʏɴı ᴜ̈ɴɪᴠᴇʀsɪᴛᴇʏᴇ ɢɪᴛᴍᴇsɪɴɪ ɪsᴛᴇʀ ᴍɪsɪɴ?','ɢʀᴜᴘᴛᴀ ʜᴏşʟᴀɴᴅıɢ̆ıɴ ʙɪʀɪ ᴠᴀʀ ᴍı ?','ᴡᴇʙ ɢᴇᴄ̧ᴍɪşɪɴɪᴢɪ, ʙɪʀɪʟᴇʀɪ ɢᴏ̈ʀᴜ̈ʀsᴇ ᴜᴛᴀɴᴀᴄᴀɢ̆ıɴıᴢ şᴇʏ ɴᴇ ᴏʟᴜʀᴅᴜ?','ɢʀᴜᴘᴛᴀ ᴋᴇşᴋᴇ ᴀʙɪᴍ/ᴀʙʟᴀᴍ ᴏʟsᴀʏᴅı ᴅᴇᴅɪɢ̆ɪɴ ᴋɪᴍsᴇ ᴠᴀʀ ᴍı ?','ᴜʏᴋᴜɴᴅᴀ ᴋᴏɴᴜşᴜʀ ᴍᴜsᴜɴ?','sıɴıғᴛᴀ ʜɪᴄ̧ ᴜʏᴜʏᴀ ᴋᴀʟᴅıɴ ᴍı?','ᴋɪᴍsᴇɴɪɴ sᴇɴɪɴ ʜᴀᴋᴋıɴᴅᴀ ʙɪʟᴍᴇᴅɪɢ̆ɪ ʙɪʀ şᴇʏ ɴᴇᴅɪʀ?','ɪʟᴇʀᴅᴇ ᴄ̧ᴏᴄᴜɢ̆ᴜɴ ᴏʟᴜʀsᴀ ɴᴇ ɪsɪᴍ ᴋᴏʏᴍᴀᴋ ɪsᴛᴇʀsɪɴ?','sᴜ̈ᴘᴇʀ ᴋᴀʜʀᴀᴍᴀɴʟᴀʀ ɢᴇʀᴄ̧ᴇᴋᴛᴇɴ ᴠᴀʀ ᴏʟsᴀʏᴅı ᴅᴜ̈ɴʏᴀ ɴᴀsıʟ ʙɪʀ ʏᴇʀ ᴏʟᴜʀᴅᴜ?','ɢʀᴜᴘᴛᴀ ᴋɪᴍɪɴ ʜᴇsᴀʙıɴᴀ ɢɪʀᴍᴇᴋ ɪsᴛᴇʀsɪɴ?','ɢɪʀᴅɪɢ̆ɪɴɪᴢ ᴇɴ sᴀᴄ̧ᴍᴀ ᴛᴀʀᴛışᴍᴀ ɴᴇᴅɪʀ?','ɢʀᴜᴘᴛᴀ ɴᴇғʀᴇᴛ ᴇᴛᴛɪɢ̆ɪɴ ʙɪʀɪ ᴠᴀʀ ᴍı?',
'ᴛᴀᴍ ᴀɴʟᴀᴍıʏʟᴀ ᴇɴ sᴏɴ ɴᴇ ᴢᴀᴍᴀɴ ʏᴀʟᴀɴ sᴏ̈ʏʟᴇᴅɪɴ?','ʜɪᴄ̧ sᴇᴠɢɪʟɪɴɪ ᴀʟᴅᴀᴛᴍᴀʏı ᴅᴜ̈şᴜ̈ɴᴅᴜ̈ɴ ᴍᴜ̈?','ᴇɴ sᴇᴠᴅɪɢ̆ɪɴ ᴘɪᴊᴀᴍᴀʟᴀʀ ɴᴇʏᴇ ʙᴇɴᴢɪʏᴏʀ?','ʜᴀᴋᴋıɴᴅᴀ ʏᴀʟᴀɴ sᴏ̈ʏʟᴇᴅɪɢ̆ɪɴ ᴇɴ ᴋᴏ̈ᴛᴜ̈ şᴇʏ ɴᴇᴅɪʀ?','ᴇɴ ᴋᴏ̈ᴛᴜ̈ ᴀʟışᴋᴀɴʟıɢ̆ıɴıᴢ ɴᴇᴅɪʀ?','ʙᴜ ʜᴀʏᴀᴛᴛᴀᴋɪ ᴇɴ ʙᴜ̈ʏᴜ̈ᴋ ɢᴜ̈ᴠᴇɴsɪᴢʟɪɢ̆ɪɴ ɴᴇᴅɪʀ?','ʜɪᴄ̧ ᴋɪᴍsᴇʏɪ ᴏ̈ᴢᴇʟᴅᴇɴ ʀᴀʜᴀᴛsıᴢ ᴇᴛᴛɪɴ ᴍɪ?','sᴇᴠᴍᴇᴅɪɢ̆ɪɴ ᴋᴏ̈ᴛᴜ̈ ʜᴜʏᴜɴ ᴠᴀʀ ᴍı?','sᴀᴄ̧ʟᴀʀıɴı ᴜᴢᴀᴛᴍᴀʏı ᴅᴜ̈şᴜ̈ɴsᴇɴ ɴᴇ ᴋᴀᴅᴀʀ ᴜᴢᴀᴛıʀᴅıɴ?','ʜᴀʏᴀʟɪɴᴅᴇᴋɪ ɪş ɴᴇ?','ʜɪᴄ̧ ᴍᴀsᴀɴıɴ ᴀʟᴛıɴᴀ sᴀᴋıᴢ ᴀᴛᴛıɴ ᴍı?','ʏᴇʀᴅᴇɴ ʙɪʀ şᴇʏɪ ᴀʟıᴘ ʜɪᴄ̧ ʏᴇᴅɪɴ ᴍɪ?','ɢʀᴜʙᴜɴ ᴋʀᴀʟı ᴋɪᴍ?','ᴋᴜʀᴛ ᴏʏᴜɴᴜɴᴜ sᴇᴠɪʏᴏʀ ᴍᴜsᴜɴ?sᴘᴏʀ ʏᴀᴘᴀʀ ᴍısıɴ?','ɢʀᴜᴘᴛᴀ ᴀɢ̆ᴢıɴı ʙᴜʀɴᴜɴᴜ ᴋıʀᴀʀıᴍ ᴅᴇᴅɪɢ̆ɪɴ ᴋɪᴍsᴇ ᴠᴀʀ ᴍı ?','ɢʀᴜᴘᴛᴀᴋɪ ᴇɴ sᴇᴠɢɪɢ̆ɪɴ ᴀᴅᴍɪɴ ᴋɪᴍ ?',
'ᴅɪʀsᴇɢ̆ɪɴɪ ʏᴀʟᴀʏᴀʙɪʟɪʀ ᴍɪsɪɴ?','ᴍᴇssɪ ᴍɪ ʀᴏɴᴀʟᴅᴏ ᴍᴜ?','şɪᴍᴅɪʏᴇ ᴋᴀᴅᴀʀ ɢᴏ̈ʀᴅᴜ̈ɢ̆ᴜ̈ᴍ ᴇɴ ɢᴀʀɪᴘ ʀᴜ̈ʏᴀʏı ᴀɴʟᴀᴛ.','ʙᴜ ʏıʟ ʜᴀʏᴀᴛıɴᴅᴀ ɴᴇʏɪ ᴅᴇɢ̆ɪşᴍᴇʏɪ ᴜʏɢᴜɴ ɢᴏ̈ʀᴜ̈ʏᴏʀsᴜɴ?','ᴇɴ sᴏɴ ɴᴇ ᴢᴀᴍᴀɴ ʜᴜ̈ɴɢᴜ̈ʀ ʜᴜ̈ɴɢᴜ̈ʀ ᴀɢ̆ʟᴀᴅıɢ̆ıɴı ʜᴀᴛıʀʟıʏᴏʀ ᴍᴜsᴜɴ?','şɪᴍᴅɪʏᴇ ᴋᴀᴅᴀʀ ʜɪᴄ̧ ᴀʀᴀʟıᴋsıᴢ 𝟷𝟸 sᴀᴀᴛᴛᴇɴ ғᴀᴢʟᴀ ᴜʏᴜᴅᴜɢ̆ᴜɴ ᴏʟᴅᴜ ᴍᴜ?','ᴛᴇʟᴇғᴏɴᴅᴀ ᴀʀᴀᴅıɢ̆ıɴ sᴏɴ şᴇʏ ɴᴇʏᴅɪ?','ʙᴜ ʜᴀʏᴀᴛᴛᴀ şɪᴍᴅɪʏᴇ ᴋᴀᴅᴀʀ ʏᴀᴘᴛıɢ̆ıɴ ᴇɴ ʙᴜ̈ʏᴜ̈ᴋ ʜᴀᴛᴀ ɴᴇᴅɪʀ?','ɢʀᴜʙᴜɴ ᴇɴ ᴇɢᴏɪsᴛɪ ᴋɪᴍ ?','ʜɪᴄ̧ ʏᴀsᴀʏᴀ ᴀʏᴋıʀı ʙɪʀ şᴇʏʟᴇʀ ʏᴀᴘᴛıɢ̆ıɴ ᴏʟᴅᴜ ᴍᴜ?','ᴀᴋʀᴀʙᴀʟᴀʀıɴᴅᴀɴ ᴋɪᴍsᴇʏɪ ᴅᴀᴠᴇᴛ ᴇᴛᴛɪɴ ᴍɪ ɢʀᴜʙᴀ ?','ɢʀᴜʙᴜ ɴᴇ ᴋᴀᴅᴀʀ sᴇᴠɪʏᴏʀsᴜɴ?','ɢʀᴜᴘᴛᴀɴ ᴜᴢᴀᴋ ᴋᴀᴄ̧ ᴅᴀᴋɪᴋᴀ ᴅᴜʀᴀʙɪʟɪʀsɪɴ ?','sᴏ̈ʏʟᴇᴅɪɢ̆ɪɴ ᴇɴ sᴏɴ ʏᴀʟᴀɴ ɴᴇʏᴅɪ?','ᴄ̧ᴇşɪᴛʟɪ ʙᴀᴛıʟ ɪɴᴀɴᴄ̧ʟᴀʀıɴ ᴠᴀʀ ᴍı, ᴠᴀʀsᴀ ᴏɴʟᴀʀ ɴᴇʟᴇʀ?',
'ʙɪʀ sıɴᴀᴠᴅᴀɴ ᴀʟᴅıɢ̆ıɴ ᴇɴ ᴋᴏ̈ᴛᴜ̈ ᴘᴜᴀɴ ɴᴇʏᴅɪ?','ʙɪʀ sıɴᴀᴠᴅᴀɴ ᴀʟᴅıɢ̆ıɴ ᴇɴ ᴋᴏ̈ᴛᴜ̈ ᴘᴜᴀɴ ɴᴇʏᴅɪ?','ʜᴀғᴛᴀᴅᴀ ᴋᴀᴄ̧ ᴋᴇᴢ ᴀʏɴı ᴘᴀɴᴛᴏʟᴏɴᴜ ɢɪʏɪʏᴏʀsᴜɴ?',
)

d = (
"Telefonunda en son aradığın şey neydi?","Birisi kız arkadaşın / erkek arkadaşından ayrılmak için sana 1 milyon tl önerseydi, yapar mıydın?","Bu grupda en az kimi seviyorsun ve neden?","Hiç sınıfta yüksek sesle geğirdin mi?","Hiç sınıfta yüksek sesle geğirdin mi?","Yerden bir şeyi alıp hiç yedin mi?","Bir gün karşı cins olarak uyanırsan, ilk yapacağın şey nedir?","Hiç havuzda işedin mi?","Asansörde hiç gaz kaçırdın mı?",
"Tuvalette otururken aklınıza gelen şeyler nelerdir?","Büyüyen hayali bir arkadaşınız var mıydı?","En kötü alışkanlığınız nedir?","Burnunu karıştırır mısın?","Banyoda şarkı söyler misin?","Hiç üzerine işedin mi?","Toplumda en utanç verici anınız neydi?","Aynada kendinle hiç konuştun mu?",
"Web geçmişinizi, birileri görürse utanacağınız şey ne olurdu?","Uykunda konuşur musun?","Gizli aşkın kim?","Benim hakkımda neyi sevmiyorsun?","Şu an ne renk iç çamaşır giyiyorsun?","Son attığın mesaj neydi?","İnsanları yanan bir binadan kurtarıyor olsaydınız ve bir kişiyi bu grupdan geride bırakmak zorunda kalırsanız, kim olurdu?",
"İç çamaşırlarını ne sıklıkla yıkıyorsun?","Hiç kulak kiri tattın mı?","Hiç osurup başka birini suçladın mı?","Hiç terinin tadına baktın mı?","Bu odadaki kim bugüne kadarki en kötü insan olurdu? Neden?",
"Yeniden doğmuş olsaydın, hangi yüz yılda doğmak isterdin?","Söylediğiniz veya yaptığınız bir şeyi silmek için zamanda geriye gidebilseydiniz, bu hangi yıl olurdu?","Erkek arkadaşın veya kız arkadaşın seni hiç utandırdı mı?","Birdenbire görünmez olsaydın ne yapardın?",
"Banyoda kaldığınız en uzun süre nedir ve neden bu kadar uzun süre kaldınız?","Şimdiye kadar gördüğüm en garip rüyayı anlat.","Duşta işiyor musun?","Hala yaptığın en çocukça şey nedir?","Hangi çocuk filmini tekrar tekrar izleyebilirsin?",
"Ayak kokunuz kötü mü?","Saçma takma adların var mı?","Telefonunuzda hangi uygulamada en çok zaman harcıyorsunuz?","Tek bir oturuşta yediğin en çok yemek ne?","Tek başınayken dans ediyor musun?","Karanlıktan korkar mısın?",
"Bütün gün evdeysen ne yapardın?","Günde kaç öz çekim yapıyorsunuz?","En son ne zaman dişlerini fırçaladın?","En sevdiğin pijamalar neye benziyor?","Hiç yerden bir şey yedin mi?","Yapmaman gereken bir şeyi yaparken hiç yakalandın mı?","Vücudunun hangi bölümünü seviyorsun, hangi kısmından nefret ediyorsun?","Hiç bitlendin mi?","Pantolonunu hiç kestin mi?","Tabağını yalıyor musun?","Kimsenin senin hakkında bilmediği bir şey nedir?",
"Hiç tabağını yaladın mı?","Dirseğini yalayabilir misin?","Eğer buradaki herkesi yanan bir binadan kurtarmaya çalışıyor olsaydın ve birini geride bırakmak zorunda kalırsan, kimi geride bırakırdın?","Telefonda aradığın son şey neydi?","Bir uygulamayı telefonunuzdan silmek zorunda kalsanız hangisini silerdiniz?","Bir ilişkideki en büyük korkun nedir?",
"Odanın her bir kişi hakkında bir tane olumlu, bir tane olumsuz şey söyleyin.","Sevmediğin kötü huyun var mı?","Hayatında yaptığın en çılgın şey nedir?","Üç gün boyunca bir adada mahsur kalmış olsaydınız, bu grupdan kimleri seçerdiniz?","Bu odadaki en sinir bozucu kişi kim?","Bu grupdan biriyle evlenmek zorunda kalsan kim olurdu?","En uzun ilişkiniz ne kadar sürdü?",
"Bir ünlü Instagram’da seni takip etseydi bu ünlünün kim olmasını isterdin?","Instagram’da 5 kişiyi silmek zorunda olsan kimleri silerdin?","Kaç çocuk sahibi olmak istersin?","Hayallerinizdeki kişiyi tarif edin.","Messi mi Ronaldo mu?","Pes mi Fifa mı?",
"İlk işin neydi?","Üniversite hakkındaki en büyük korkun nedir?","En iyi arkadaşının seninle aynı üniversiteye gitmesini ister misin?","Mevcut erkek arkadaşının ya da kız arkadaşının seninle aynı üniversiteye gitmesini ister misin?","Hayalindeki iş ne?",
"Hiç bir dersten başarısız oldun mu?","Hiç kopya çektin mi?","Hiç sınıfta uyudun mu?","Sınıfta asla yanında oturmak istemeyeceğin kim?","Derse hiç geç kaldın mı?","Bir öğretmenin önünde yaptığın en utanç verici şey nedir?","Hiç masanın altına sakız attın mı?",
"Hiç okulda kavga ettin mi?","Bir sınavdan aldığın en kötü puan neydi?","Sınıfta hiç uyuya kaldın mı?","Hiç gözaltına alındın mı?","Eğer görünmez olsaydın hangi derse gizlice girerdin?","En kötü grup hangisidir?","Bu grupdaki sır tutma  konusunda en çok zorlanan kişi kimdir?",
"s‌ɪᴍᴅɪʏᴇ ᴋᴀᴅᴀʀ ʙɪʀ ʙᴀs‌ᴋᴀsıɴᴀ sᴏ‌ʏʟᴇᴅɪɢ‌ɪɴ ᴇɴ ᴀᴄıᴍᴀsıᴢᴄᴀ s‌ᴇʏ ɴᴇʏᴅɪ?","ᴄ‌ıᴋᴛıɢ‌ıɴ ᴇɴ ʏᴀs‌ʟı ᴋɪs‌ɪ ᴋɪᴍ?","ɢʀᴜᴘᴛᴀ ᴋɪ sᴇᴠᴍᴇᴅᴇɢ‌ɪɴ ᴋɪs‌ɪʏɪ ᴇᴛɪᴋᴇᴛʟᴇʀ ᴍɪsɪɴ ?","ᴇɴ sᴏɴ ɴᴇ ᴢᴀᴍᴀɴ ʜᴜ‌ɴɢᴜ‌ʀ ʜᴜ‌ɴɢᴜ‌ʀ ᴀɢ‌ʟᴀᴅıɢ‌ıɴı ʜᴀᴛıʀʟıʏᴏʀ ᴍᴜsᴜɴ?","ʙɪʀɪʏʟᴇ ᴄ‌ıᴋᴀʀᴋᴇɴ ʏᴀᴘᴛıɢ‌ıɴ ᴇɴ ᴜᴛᴀɴᴄ‌ ᴠᴇʀɪᴄɪ s‌ᴇʏ ɴᴇʏᴅɪ?","ᴜ‌ᴄ‌ ɢᴜ‌ɴ ʙᴏʏᴜɴᴄᴀ ʙɪʀ ᴀᴅᴀᴅᴀ ᴍᴀʜsᴜʀ ᴋᴀʟᴍıs‌ ᴏʟsᴀʏᴅıɴıᴢ, ʙᴜ ɢʀᴜᴘᴅᴀɴ ᴋɪᴍʟᴇʀɪ sᴇᴄ‌ᴇʀᴅɪɴɪᴢ?","ᴇɴ sᴏɴ ɴᴇ ᴢᴀᴍᴀɴ ᴅɪs‌ʟᴇʀɪɴɪ ғıʀᴄ‌ᴀʟᴀᴅıɴ?",
"ᴋᴜ‌ʟᴛᴜ‌ʀᴜ‌ᴍᴜ‌ᴢᴜ‌ɴ ᴇɴ ᴄ‌ᴏᴋ sᴇᴠᴅɪɢ‌ɪɴɪᴢ ʏᴀɴı ɴᴇᴅɪʀ?","ʙɪʀ ɪʟɪs‌ᴋɪᴅᴇᴋɪ ᴇɴ ʙᴜ‌ʏᴜ‌ᴋ ᴋᴏʀᴋᴜɴ ɴᴇᴅɪʀ?","ʙᴜʀᴅᴀ ᴋɪ ᴋɪᴍsᴇʏᴇ ʏᴀʟᴀɴ sᴏ‌ʏʟᴇᴅɪɴ ᴍɪ?","ᴀɪʟᴇɴɪɴ sᴇɴɪɴ ʜᴀᴋᴋıɴᴅᴀ ʙɪʟᴍᴇᴅɪɢ‌ɪɴᴇ sᴇᴠɪɴᴅɪɢ‌ɪɴ s‌ᴇʏ ɴᴇᴅɪʀ?","s‌ᴜ ᴀɴᴋɪ ʀᴜʜ ʜᴀʟɪɴᴇ ʙᴀᴋᴀʀᴀᴋ ɴᴇ ᴛᴜ‌ʀ ғɪʟᴍ ɪᴢʟᴇʀsɪɴ (ᴀᴋsɪʏᴏɴ/ᴅʀᴀᴍ/ʙɪʟɪᴍ ᴋᴜʀɢᴜ/ʀᴏᴍᴀɴᴛɪᴋ ᴋᴏᴍᴇᴅɪ/ʙɪʏᴏɢʀᴀғɪ/ғᴀɴᴛᴀsᴛɪᴋ)","ʙɪʀ ᴜ‌ɴʟᴜ‌ ɪɴsᴛᴀɢʀᴀᴍ’ᴅᴀ sᴇɴɪ ᴛᴀᴋɪᴘ ᴇᴛsᴇʏᴅɪ ʙᴜ ᴜ‌ɴʟᴜ‌ɴᴜ‌ɴ ᴋɪᴍ ᴏʟᴍᴀsıɴı ɪsᴛᴇʀᴅɪɴ?",
"sᴏ‌ʏʟᴇᴅɪɢ‌ɪɴɪᴢ ᴠᴇʏᴀ ʏᴀᴘᴛıɢ‌ıɴıᴢ ʙɪʀ s‌ᴇʏɪ sɪʟᴍᴇᴋ ɪᴄ‌ɪɴ ᴢᴀᴍᴀɴᴅᴀ ɢᴇʀɪʏᴇ ɢɪᴅᴇʙɪʟsᴇʏᴅɪɴɪᴢ, ʙᴜ ʜᴀɴɢɪ ʏıʟ ᴏʟᴜʀᴅᴜ?","ɢɪᴢʟɪ ᴀs‌ᴋıɴ ᴋɪᴍ?","ʜɪᴄ‌ ʏᴇʀᴅᴇɴ ʙɪʀ s‌ᴇʏ ʏᴇᴅɪɴ ᴍɪ?","ʜɪᴄ‌ sᴇᴠɢɪʟɪɴɪ ᴀʟᴅᴀᴛᴍᴀʏı ᴅᴜ‌s‌ᴜ‌ɴᴅᴜ‌ɴ ᴍᴜ‌?","ʜɪᴄ‌ ʏᴇʀᴅᴇɴ ʙɪʀ s‌ᴇʏ ʏᴇᴅɪɴ ᴍɪ?","ʙɪʀ sıɴᴀᴠᴅᴀɴ ᴀʟᴅıɢ‌ıɴ ᴇɴ ᴋᴏ‌ᴛᴜ‌ ᴘᴜᴀɴ ɴᴇʏᴅɪ?","ʙɪʀ ᴄɪɴ sᴀɴᴀ ᴜ‌ᴄ‌ ᴅɪʟᴇᴋ ʜᴀᴋᴋı sᴜɴsᴀʏᴅı ɴᴇʟᴇʀ ᴅɪʟᴇʀᴅɪɴ?","ɢʀᴜᴘᴛᴀɴ ᴜᴢᴀᴋ ᴋᴀᴄ‌ ᴅᴀᴋɪᴋᴀ ᴅᴜʀᴀʙɪʟɪʀsɪɴ ?",
"sɪᴢᴄᴇ ᴛᴜ‌ʀᴋɪʏᴇ’ɴɪɴ ᴇɢ‌ɪᴛɪᴍ sɪsᴛᴇᴍɪɴᴅᴇ ʏᴀᴘıʟᴍᴀsı ɢᴇʀᴇᴋᴇɴ ᴇɴ ᴏ‌ɴᴇᴍʟɪ ᴅᴇɢ‌ɪs‌ɪᴋʟɪᴋ ɴᴇᴅɪʀ?","ʜᴀʟᴀ ʏᴀᴘᴛıɢ‌ıɴ ᴇɴ ᴄ‌ᴏᴄᴜᴋᴄ‌ᴀ s‌ᴇʏ ɴᴇᴅɪʀ?","ɢʀᴜʙᴜɴ ᴇɴ ʏᴀᴋıs‌ıᴋʟısı ᴋɪᴍ ?","ʜᴀғᴛᴀᴅᴀ ᴋᴀᴄ‌ ᴋᴇᴢ ᴀʏɴı ᴘᴀɴᴛᴏʟᴏɴᴜ ɢɪʏɪʏᴏʀsᴜɴ?","sıɴıғᴛᴀ ᴀsʟᴀ ʏᴀɴıɴᴅᴀ ᴏᴛᴜʀᴍᴀᴋ ɪsᴛᴇᴍᴇʏᴇᴄᴇɢ‌ɪɴ ᴋɪᴍ?","sᴜ‌ᴘᴇʀ ᴋᴀʜʀᴀᴍᴀɴʟᴀʀ ɢᴇʀᴄ‌ᴇᴋᴛᴇɴ ᴠᴀʀ ᴏʟsᴀʏᴅı ᴅᴜ‌ɴʏᴀ ɴᴀsıʟ ʙɪʀ ʏᴇʀ ᴏʟᴜʀᴅᴜ?","sᴏ‌ᴢʟᴜ‌ ᴅᴇsᴛᴀɴʟᴀʀ ʜᴀᴋᴋıɴᴅᴀ ɴᴇ ᴅᴜ‌s‌ᴜ‌ɴᴜ‌ʏᴏʀsᴜɴ?","ʜᴀʏᴀʟʟᴇʀɪɴɪᴢᴅᴇᴋɪ ᴋɪs‌ɪʏɪ ᴛᴀʀɪғ ᴇᴅɪɴ.",
"ɢʀᴜʙᴜ sᴇᴠɪʏᴏʀ ᴍᴜsᴜɴ ?","ʙɪʀɪɴɪ ᴏ‌ᴘᴇʀᴋᴇɴ ᴋᴇɴᴅɪɴɪ ʜɪᴄ‌ ᴋᴏ‌ᴛᴜ‌ ʜɪssᴇᴛᴛɪɴ ᴍɪ?","ʙᴜ ʜᴀʏᴀᴛᴛᴀ sᴇɴɪ sᴇɴɪ ᴇɴ ᴄ‌ᴏᴋ ɴᴇ ɢıᴄıᴋ ᴇᴅᴇɴ ᴠᴇ ᴄ‌ɪʟᴇᴅᴇɴ ᴄ‌ıᴋᴀʀᴀɴ s‌ᴇʏ ɴᴇᴅɪʀ?","ʜɪᴄ‌ ᴋᴏᴘʏᴀ ᴄ‌ᴇᴋᴛɪɴ ᴍɪ?","ɪ‌ɴsᴀɴʟᴀʀıɴ sɪᴢᴇ ɴᴇ sᴏʀᴍᴀsıɴᴅᴀɴ ʙıᴋᴛıɴıᴢ?","ʜɪᴄ‌ sᴇᴠɢɪʟɪɴɪ ʙɪʀɪʏʟᴇ ᴀʟᴅᴀᴛᴛıɴ ᴍı?","ᴇɢ‌ᴇʀ ʙᴜʀᴀᴅᴀᴋɪ ʜᴇʀᴋᴇsɪ ʏᴀɴᴀɴ ʙɪʀ ʙɪɴᴀᴅᴀɴ ᴋᴜʀᴛᴀʀᴍᴀʏᴀ ᴄ‌ᴀʟıs‌ıʏᴏʀ ᴏʟsᴀʏᴅıɴ ᴠᴇ ʙɪʀɪɴɪ ɢᴇʀɪᴅᴇ ʙıʀᴀᴋᴍᴀᴋ ᴢᴏʀᴜɴᴅᴀ ᴋᴀʟıʀsᴀɴ, ᴋɪᴍɪ ɢᴇʀɪᴅᴇ ʙıʀᴀᴋıʀᴅıɴ?",
"ᴏʏᴜɴᴜ ᴏʏɴᴀʏᴀɴ ᴏʏᴜɴᴄᴜ ɢʀᴜʙᴜɴᴅᴀ ʏᴇʀ ᴀʟᴀɴʟᴀʀᴅᴀɴ ᴋɪᴍɪ ᴏ‌ᴘᴍᴇᴋ ɪsᴛᴇʀsɪɴ?","ɢʀᴜᴘᴛᴀ ᴋɪᴍɪɴ ʏᴇʀɪɴᴅᴇ ᴏʟᴍᴀᴋ ɪsᴛᴇʀᴅɪɴ ?","sᴇᴠᴅɪɢ‌ɪɴɪ ɪᴛɪʀᴀғ ᴇᴛᴍᴇᴋᴛᴇɴ ᴜᴛᴀɴᴅıɢ‌ıɴ ғɪʟᴍ ʜᴀɴɢɪsɪᴅɪʀ?","ʙᴜ ʜᴀʏᴀᴛᴛᴀ s‌ɪᴍᴅɪʏᴇ ᴋᴀᴅᴀʀ ʏᴀᴘᴛıɢ‌ıɴ ᴇɴ ʙᴜ‌ʏᴜ‌ᴋ ʜᴀᴛᴀ ɴᴇᴅɪʀ?","ʜɪᴄ‌ sıɴıғᴛᴀ ᴜʏᴜᴅᴜɴ ᴍᴜ?","ᴍᴇssɪ ᴍɪ ʀᴏɴᴀʟᴅᴏ ᴍᴜ?","ʜɪᴄ‌ ʙɪʀ ᴅᴇʀsᴛᴇɴ ʙᴀs‌ᴀʀısıᴢ ᴏʟᴅᴜɴ ᴍᴜ?","s‌ᴜ ᴀɴᴋɪ ʀᴜʜ ʜᴀʟɪɴᴇ ʙᴀᴋᴀʀᴀᴋ ɴᴇ ᴛᴜ‌ʀ ғɪʟᴍ ɪᴢʟᴇʀsɪɴ (ᴀᴋsɪʏᴏɴ/ᴅʀᴀᴍ/ʙɪʟɪᴍ ᴋᴜʀɢᴜ/ʀᴏᴍᴀɴᴛɪᴋ ᴋᴏᴍᴇᴅɪ/ʙɪʏᴏɢʀᴀғɪ/ғᴀɴᴛᴀsᴛɪᴋ)",
"ɪʟᴇʀᴅᴇ ᴄ‌ᴏᴄᴜɢ‌ᴜɴ ᴏʟᴜʀsᴀ ɴᴇ ɪsɪᴍ ᴋᴏʏᴍᴀᴋ ɪsᴛᴇʀsɪɴ?","ᴋıʀᴍıᴢı ʜᴀʟıᴅᴀ ʙᴇʀᴀʙᴇʀ ʏᴜ‌ʀᴜ‌ᴍᴇᴋ ɪsᴛᴇᴅɪɢ‌ɪɴ ᴜ‌ɴʟᴜ‌ ɪsɪᴍ ᴋɪᴍ .","ʙᴇʏɴɪɴɪ ʙɪʀ ʀᴏʙᴏᴛᴀ ʏᴇʀʟᴇs‌ᴛɪʀᴇʙɪʟɪʀ ᴠᴇ sᴏɴsᴜᴢᴀ ᴋᴀᴅᴀʀ ʙᴜ s‌ᴇᴋɪʟᴅᴇ ʏᴀs‌ᴀʏᴀʙɪʟsᴇᴅɪɴ,ʙᴜɴᴜ ʏᴀᴘᴀʀ ᴍıʏᴅıɴ?","ʜᴀʏᴀʟʟᴇʀɪɴɪᴢᴅᴇᴋɪ ᴋɪs‌ɪʏɪ ᴛᴀʀɪғ ᴇᴅɪɴ.","ᴀɪʟᴇɴɪᴢ ᴅıs‌ıɴᴅᴀ, ʏᴀs‌ᴀᴍıɴıᴢ ᴜ‌ᴢᴇʀɪɴᴅᴇ ᴇɴ ʙᴜ‌ʏᴜ‌ᴋ ᴇᴛᴋɪsɪ ᴏʟᴀɴ ᴋɪs‌ɪ ᴋɪᴍᴅɪʀ?","ᴇɴ ᴋᴏ‌ᴛᴜ‌ ᴀʟıs‌ᴋᴀɴʟıɢ‌ıɴıᴢ ɴᴇᴅɪʀ?","ɢʀᴜᴘ sᴇɴɪɴ ɪᴄ‌ɪɴ ɴᴇ ɪғᴀᴅᴇ ᴇᴅɪʏᴏʀ?","ʙɪʀ ɢᴜ‌ɴ ᴋᴀʀs‌ı ᴄɪɴs ᴏʟᴀʀᴀᴋ ᴜʏᴀɴıʀsᴀɴ, ɪʟᴋ ʏᴀᴘᴀᴄᴀɢ‌ıɴ s‌ᴇʏ ɴᴇᴅɪʀ?",
"ɢʀᴜᴘᴛᴀ ɢɪᴢʟɪ ᴀs‌ᴋıɴ ᴠᴀʀ ᴍı ?","ᴛᴇʟᴇғᴏɴᴅᴀ ᴀʀᴀᴅıɢ‌ıɴ sᴏɴ s‌ᴇʏ ɴᴇʏᴅɪ?","sᴜ‌ᴘᴇʀ ᴋᴀʜʀᴀᴍᴀɴʟᴀʀ ɢᴇʀᴄ‌ᴇᴋᴛᴇɴ ᴠᴀʀ ᴏʟsᴀʏᴅı ᴅᴜ‌ɴʏᴀ ɴᴀsıʟ ʙɪʀ ʏᴇʀ ᴏʟᴜʀᴅᴜ?","ᴋᴀʀᴀɴʟıᴋᴛᴀɴ/ʏᴜ‌ᴋsᴇᴋʟɪᴋᴛᴇɴ ᴋᴏʀᴋᴀʀ ᴍısıɴ?","ᴘᴀɴᴛᴏʟᴏɴᴜɴᴜ ʜɪᴄ‌ ᴋᴇsᴛɪɴ ᴍɪ?","ʜɪᴄ‌ sᴀʜᴛᴇ ᴋɪᴍʟɪᴋ ᴋᴜʟʟᴀɴᴅıɴ ᴍı?",
"Söylediğin en son yalan neydi?","Spor yapar mısın?","Hayatının geri kalanında sadece bir kıyafet giyebilseydin, bu kıyafetin hangi renk olurdu?","Sizce Türkiye’nin eğitim sisteminde yapılması gereken en önemli değişiklik nedir?","Karanlıktan/yükseklikten korkar mısın?",
"Kendi görünuşünü 1 ile 10 arasında puanla :)","Yaptıgın en yasadışı şey neydi?","Şimdi sana bir evlenme teklifi gelse ve sevmediğin biri olsa, ve bu sana son gelecek evlilik teklifi olsa kabul edermiydin?","Şu anki ruh haline bakarak ne tür film izlersin (aksiyon/dram/bilim kurgu/romantik komedi/biyografi/fantastik)","Kendini en ezik hissettiğin an hangisiydi ?","ilerde çocuğun olursa ne isim koymak istersin?",
"Unicorun mu olmasını isterdin ejderhan mı?","Kaç sevgilin oldu?","Hayatta unutmadığın biri var mı?","en sevdiğin şarkı?","Yapmaman gereken bir şeyi yaparken hiç yakalandın mı?","En sevdiğin sanatçı kim?","karşı cinste ilk dikkatini çeken ne?","bu yıl hayatında neyi değişmeyi uygun görüyorsun?",
"Birinin telefonunda gördüğün en tuhaf şey nedir?","Süper kahramanlar gerçekten var olsaydı Dünya nasıl bir yer olurdu?","Hayatın size öğrettiği en önemli ders nedir?","Kültürümüzün en çok sevdiğiniz yanı nedir?","Ailenizin uyguladığı en tuhaf gelenek nedir?",
"Aileniz dışında, yaşamınız üzerinde en büyük etkisi olan kişi kimdir?","Kadın/Erkek olmanın en kötü ve en iyi yanı nedir?","Beynini bir robota yerleştirebilir ve sonsuza kadar bu şekilde yaşayabilsedin,bunu yapar mıydın?","Evinizde ağırladığın en kötü misafir kimdi ve ne oldu?",
"İnsanların size ne sormasından bıktınız?","En tuhaf korkunuz nedir?","En sevdiğiniz TV programı hangisidir?","Girdiğiniz en saçma tartışma nedir?","En son söylediğin yalan nedir?", "Biriyle çıkarken yaptığın en utanç verici şey neydi?","Hiç arabanla (varsa) yanlışlıkla bir şeye birine çarptın mı?",
"Hoşuna gittiğini düşündüğün ama bir türlü açılamadığın biri oldu mu?","En tuhaf takma adın nedir?","Fiziksel olarak sana en acı veren deneyimin ne oldu?","Hangi köprüleri yakmak seni rahatlattı?","Toplu taşıma araçlarında yaptığın en çılgınca şey neydi?","Şişeden bir cin çıksa üç dileğin ne olurdu?","Dünyadaki herhangi birini Türkiye’nin başkanı yapabilseydin bu kim olurdu?",
"Şimdiye kadar bir başkasına söylediğin en acımasızca şey neydi?","Birini öperken kendini hiç kötü hissettin mi?","Hiçbir sonucu olmayacağını bilsen ne yapmak isterdin?","Bir aynanın önünde yaptığın en çılgınca şey nedir?","Şimdiye kadar başkasına söylediğin en anlamlı şey neydi?",
"Arkadaşlarınla yapmayı sevdiğin ama sevgilinin önünde asla yapmayacağın şey nedir?","Bu hayatta en çok kimi kıskanıyorsun?","En sevdiğin pijamaların neye benziyor?","Bir buluşmadan kaçmak için hiç hasta numarası yaptın mı?","Çıktığın en yaşlı kişi kim?",
"Günde kaç tane özçekim yaparsın?","Aşk için her şeyi yaparım ama “bunu” yapmam dediğin şey nedir?","Haftada kaç kez aynı pantolonu giyiyorsun?","Bugün şansın olsa lise aşkınla çıkar mısın?","Vücudunun hangi bölümlerinden gıdıklanıyorsun?",
"Çeşitli batıl inançların var mı? Varsa onlar neler?","Sevdiğini itiraf etmekten utandığın film hangisidir?","En utan verici kişisel bakım alışkanlığın nedir?","En son ne zaman ve ne için özür diledin?","Sözlü destanlar hakkında ne düşünüyorsun?",
"Utanç verici kokularınızın çoğu nereden geliyor?","Hiç sevgilini anlatmayı düşündün mü?","Hiç sevgilini biriyle aldattın mı?","Boxer mı yoksa külot mu?","Hiç havuza veya denize işedin mi?","Saçlarını uzatmayı düşünsen ne kadar uzatırdın?","Kimsenin bilmeyeceği garanti olsa kimi öldürmek isterdin?","Başkası için aldığın en ucuz hediye nedir?",
"Zamanının çoğunu en çok hangi uygulamada harcıyorsun?","Otobüste yaptığın en tuhaf şey nedir?","Hiç toplum içinde çıplak kaldın mı?","Günde ne kadar dedikodu yaparsın?","Çıkmak isteyeceğin en genç kişi kaç yaşında olurdu?","Hiç toplum içindeyken burnunu karıştırdın mı?",
"Hiç yaşın hakkında yalan söyledin mi?","Telefonundan bir uygulamayı silmek zorunda olsan bu hangisi olurdu?","Gece geç saatte yaptığın en utanç verici şey nedir?","Duş almadan en uzun süre ne kadar durdun ?","Hiç sahte kimlik kullandın mı?","Kırmızı halıda beraber yürümek istediğin ünlü isim kim?","Gizli aşkın kim?",
)

c = (
"Seçtiğiniz bir sosyal medya hesabınızdan çok çirkin bir fotoğrafınızı paylaşın.","Mesaj yazma bölümünüzü telefonunuzdan açın gözlerinizi kapatın ve rasgele bir kişiye körü körüne bir metin gönderin.","Telegramda son konuşmanı ss at.","🎀 ŞANSLI MESAJ🎊 Grupdan İstediğin Birinin Google/Youtube/İnstagram Arama Geçmişini İste","Galerinin En Alttan 7. Fotosunu gönder","Sonraki 3 tur boyunca şiveyle konuş. Farklı şivelere kayış olursa /zar Komutunu kullanarak 6 ya en cok yaklaşan oyuncu sana ceza verecek",
"Önümüzdeki 5 dakika boyunca söylediğin her şeyden sonra “mee” diyeceksin","Önümüzdeki 5 dakika içinde birinin hayvanı olun.","İnstagramını oyunculardan birine ver. 5 dk boyunca her yere bakmak serbest.","Oyundan bir kişiye serenat yap (kız ise erkeğe, erkek ise kıza)","Sonraki 3 tur boyunca şiveyle konuş.","3 dakika boyunca bebek taklidi yap!","Telefonunda ki en sevmediğin fotoğrafını at","En beğendiğin fotoğrafını at",
"Whatsapp’da 2 konuşmanı at","Özel mesajlarını ssi al ve gruba at","Whatsapp’da son konuşmanı at","Bir deftere 20 kez ben çatlağım yaz ve resmini at","Telegramda son konuşmanı ss at.","Biyografine +18 bir cümle yaz; 3 Saat duracak.!","Galerinin bir kısmını ss alıp at","Galerindeki 16. Fotoğrafı at.","Instagram yada telegramdan tanımadığın birine komik olmayan bir fıkra anlat.",
"Ninni Söyleyerek Ses At","Bugununle ilgili kısa bir hikaye uydur.","Grupta ki en çok hoşuna giden karşı cinse seni seviyorum diye mesaj at.","Galerindeki 16. Fotoğrafı at.","Galerindeki 30. Fotoğrafı at.","Whatsapp’da konuşduğun kişilerin ss ini at","Grubun üye listesine gir ve 7. kişiye anlık at. (Grup daha az kişiyse ya da aktif sayısı azsa üstten saymaya devam et)","En son konuştuğun kişiye \"Hayırlı Cumalar\" diye mesaj at.(platform farketmez)",
"Şuan ki halini fotoğraf çekip  atar mısın?","Grupta üyeler kısmına gir 11. kişiye \"Analar neler doğuruyor bee\" diye ses at ve cevabını grupla paylaş.","Profil fotoğrafına nefret ettiğin bir ünlünün resmini koy.","Kafanda yumurta kır ve fotosunu at","Gruptan sevdiğin bir kişinin fotoğrafını profil resmi yap","Balkona veya pencereye cık dısardakılerın duyacagı sekılde sarkı soyle videoya al gruba at.",
"İtiraf et: üye çalmak için kaç hesabın var?","Gruptaki 5 abazaya seni seviyorum de","İki dakika tavuk gibi davran.","Seçtiğiniz bir hayvanı taklit edin.","Seçtiğin bir nesneyi yalayın ve gruba fotosunu atın.","Gruba gerçekten utanç verici bir fotoğrafını göster.","Çirkin bir selfie çek ve sosyal medya uygulamalarından birinde yayınla 1.5 saat kalacak.","Bir kaşık un ye ve video ya al gruba at",
"Hiç tanımadığın birine Kurban Bayramınızı kutlarım deyin","Sevdiğin bir kişiye ( ben seni neden sevdim niçin sevdim niye sevdim bunların bi izahı yok gördün işte sevdim. Yaw sahi ben seni nidennn sevdim ) de. Cevap geldiğinde grupla paylaş biz de gülelim","Telegram'daki en kalabalık grubu aç ve \"`Benim adım turşu bidonu!`\" diyerek ses kaydedip en kalabalık gruba gönder.","Hemcinsin olan yakın bir arkadaşına ona aşık olduğunu söyle.","Sürahiden su iç ve fotoğraf at.","En çok konuştuğun karşı cinsten arkadaşına \" `Seni çok seviyorum galiba aşık oldum`\" yaz ve tepkisini bizimle paylaş",
"İsmini 1 saatliğine Abdül<ismin> yap. (örneğin adın Berk ise AbdülBerk yap)","İnstagram'da dm kutunu (mesajlar bölümü) ss al gruba at.","Tanımadığın birisine şu cümleyi atıp sohbet başlat: \"`Aşkımızın suya düşeceğini bilseydim , balık olurdum`\"","En komik fotoğrafını grupla paylaş.","Grupta üyeler kısmına gir 11. kişiye \"`Analar neler doğuruyor bee`\" diye ses at ve cevabını grupla paylaş.",
"Tanımadığın birine şu mesajı at sonra cevabını grupla paylaş ➡️\n  \"`Bu mesaj özel bir frekansla gönderilmiştir. Zekilerde hafıza kaybı, aptallarda kısa sureli körlük ibnelerde de bir anlık gülümseme yapar!`\"","@ yaz çıkan ilk kişiyi etiketle ve seni seviyorum yaz.","Tanımadığın birine \" `sanırım sana aşık oldum`\" diye mesaj at.","Telegram hakkında kısmına \"`Babasının Prensesi`\" yaz 1 saat boyunca dursun.","Birine Sesli Öpücük At Ve Etiketle",
"Üç çorba kaşığı acı salça (veya buna benzer bir şey) ye ve video ya al gruba at","5 dakika boyunca oyundaki birinin evcil hayvanı olmasını isteyebilirsin.","Yeri yala Ve fotoğraf/videosunu gruba at","/zar Komutunu kullanarak 6 ya en cok yaklaşan oyuncuya sosyal medya hesaplarından birini 5dk ver","3 dakika boyunca bir ünlüyü taklit et.", "Birisi taklit edilen sanatçıyı tahmin edene kadar bir sanatçıyı taklit et",
"Grubun ortaya koyduğu bir konu etrafında sekiz satır ve iki mısralık bir şiir yaz","Oyundaki kişilerin ortak kararıyla gruptan birini öp ses atarak (ortak karar verilemezse /zar komutundan 1 e en yakın oyuncuyu öp).","5 dakika boyunca oyundaki bir kişinin kölesi ol.", "Bir süpürgeyle veya paspas ile dans et ve videosunu at","Gerçek aşkının kim olduğunu ilan et","Ağzını hareket ettirmeden baştan sona alfabeyi oku okurken video at", "Aklına gelen ilk kelimeyi hemen söyle.",
"Oyundaki oyunculardan biri hakkında hikaye uydur", "15 saniye içerisinde sondan başa doğru alfabeyi oku okurken ses at", "Bir köpek gibi havla havlarken ses at","Bir şarkıyı baştan sona söyle söylerken ses at","Çıktığın en kötü ve en iyi kişiyi açıkla.","Bir dakika boyunca karşı cinsten biri gibi yürü.","Sevgiline atıp atabileceğin en acımasız mesajı gönder.","Oyunda yer alan her kişi hakkında bildiğin komik bir şey anlat.",
"Ünlü restoranlardan birini ara ve menülerini öğrenirken dalga geç.","Eski bir şarkıyı aç ve onu taklit ederek söylemeye çalış söylerken ses at","1 tur boyunca farklı bir dilde konuş.","Eski sevgiline mesaj at ve onu unutamadığını söyle.","2 tur boyunca “sen” kelimesini duyunca kuş gibi ses çıkart.","Telefondaki tarayıcı geçmişini herkese göster.","Odadan birisi için satın alacakmış gibi iç çamaşırı araştırması yap.",
)

koyluu = "**Rolün basit: hayatta kalmaya çalış. Böylece her gün lanet olası Kurt Adamı linç etmek için bir şansın olacak .**"
sarhoss = "**Seni lanet olası Alkolik! Alkolik olarak sen sadece bir köylüsün. ANCAK! Kurtlar seni öldürürse, sonraki gece yüksek promilli kanını delicesine içtikleri için etkisiz hale gelecekler .**"
gozcuu = "**Sen Gözcü’sün. Bu rolde her gece birini seçebilir ve rolünü görebilirsin. Rolünü akıllıca oyna: Eğer Gözcü olduğun belli olursa Kurtlar seni yemeye çalışır !**"
yancii = "**Yancı olarak her gece başka bir oyuncuyu ziyaret etme şansın olacak. Eğer onlar kurt değilse, sana da kurt olmadıkları söylenecek (bunu hayatta kalman ile anlayacaksın akıllı!). Kurtu ziyaret edersen, öldürüleceksin. Kurtların öldürmek için seçtiği oyuncuyu ziyaret edersen, sen de öldürüleceksin. Ancak - Eğer bir oyuncuyu ziyaret ediyorsan ve kurtlar seni öldürmeyi seçerse sen hayatta kalırsın (çünkü evde değildin) .**"
seyircii = "**Sana gerçek Gözcü’nün kim olduğu söylenecek (Gerçek Gözcü, Aptal değil) .**"
silahsorr = "**Biraz mutluyuz değil mi? Nişancı olarak, oyunun başında sana 2 tane gümüş mermi verilir. Her gün, başka bir oyuncunun kafasına sıkma şansın olacak. Bunu yaptığında, herkes senin nişancı olduğunu bilecek! Yinede dikkatli ol, sadece 2 mermin var !**"
kmelekk = "**Sen Koruyucu Meleksin! Her gece, bir oyuncuyu kollamak için seçebilirsin. Ancak dikkatli ol! Eğer bir kurtu kollamak için seçersen, %50 ihtimalle öldürülebilirsin .**"
aptall = "**Aptal kendisinin Gözcü olduğunu zanneder... Gece birisini görmek için seçtiğinde, sana rastgele bir rol gösterilir. Sonuç doğru da olabilir doğru olmayadabilir .**"
masonn = "**Mason’un işi basit. Birden fazla mason varsa eğer diğer Mason’ların kim olduğunu bilecek. Bunun dışında basit bir köylü .**"
dedektiff = "**Sen ihtiyar dedektifsin. Her gün, başka bir oyuncuyu araştırma şansın olacak. Ancak bunu dikkatlice kullan, %40 ihtimalle Kurt Adamlar seni bulabilir !**"
gozcucc = "**Şu an normal bir köylüsün ama Gözcü ölürse yeni Gözcü sen olacaksın .**"
tavcii = "**Senin işin Tarikat Üyesi avlamak. Eğer Tarikatçı seni tarikata çekmeye çalışırsa en yeni mensupları ölecek. Her gece avlamak için bir oyuncu seçeceksin; seçtiğin kişi eğer Tarikat Üyesi çıkarsa ölecek .**"
eross = "**Havada Aşk kokusu var. Eros olarak oyunun başında iki kişi seç. Bu iki kişiden biri ölürse diğeri de ızdıraptan ölecek.:( Tam bir klasik aşk masalı!/nNot: Aşıklar kimler olduklarını bilecekler ama rolleri birbirlerine söylenmeyecekler. Aşıklar sona kalan 2 kişi olursa takımlarından bağımsız olarak kazanacaklar. Aşıklar farklı takımdalarsa (köylü + kurt), örneğin kurt takımı kazansa köylü aşığı da kazanmış olur. Lafın kısası aşıklardan biri kazanan takımda ise, aşığı da kazanır .**"
avcii = "**Mutlu bir tetikçi, kindar bir oyuncu. Avcı olarak kendini tutman lazım. Diğerleri seni ziyarete gelirse kendilerini ölü bulabilirler. Paranoyan devreye girer ve takır takır vurmaya başlarsın. Kurtlar sana saldırırsa birini de kendinle beraber götürme şansın var. Öbür türlü, ölürken birini vurma şansın var.\nNot: Kurt saldırıları için şansın %30’dan başlıyor. Sadece bir Kurt varsa Avcı’nın Kurt’u öldürme şansı %30. Her bir ek Kurt için %20 oranında şansın artar. (2 Kurt = %50, 3 = %70 vs.) Öte yandan, birden fazla Kurt varsa birini öldürsen bile sen de öleceksin. \nTarikat seni dönüştürmeye çalışırsa %50 kaybetme şansları var. Kaybederlerse %50 şansla onlardan birini öldüreceksin !**"
beceriksizz = "**Beceriksiz’sin. Daha başladığın işleri başaramıyorsun ki. Buna rağmen istediğin adama oy verebileceğini mi sanıyorsun? (Verdiğin oyda tuturma ihtimalin %50) .**"
demircii = "**Demircisin. Yıllardır ne bir bıçak, ne de bir kılıç sana elflerin sipariş ettiği gümüş bıçakların tatminini vermemişti.\nBiraz gümüş tozun kalmış olmalı. Kim bilir? Belki kurt saldırısını bu gece engelleyebilirsin 🤔**"
karakk = "**Sen sürü aramak için başka bir köyden gelen yalnız bir kurt olan Kara Kurt'sun. Amacın geceleri Alfa Kurt'u bulmak ve ona meydan okumaktır. Kazanırsan,% 40 bulaşıcı ısırık ile yeni Alfa Kurt olacaksın. Ancak kaybedersen, sonuç senin için ağır olabilir .**"
prenss = "**Prens, Köy Takımı stratejisinde anahtar bir rol oynar. Prens linç edildiği zaman, rolü ortaya çıkar ve yaşamaya devam eder. Ama bu bir kez olur ve rolü açığa çıkar. Köylüler linç etmeye devam ederlerse Prens ölür .**"
bbaskanii = "**Muhtar sıradan bir köylüdür. Ta ki kendini açığa çıkarana kadar. Linç ederken oyun 2 oy sayılır. (Yani oyun herkesinkinden 2 kat güçlü olur.) Gücünü Köy Takımı için akıllıca kullan .**"
kahinn = "**Kahine, birinin hangi rolde OLMADIĞI söylenecek. Dikkatli olmalı. Çünkü gördüğü rol hala hayatta .**"
hukumdarr = "**Sen hükümdarsın! Krallığın bir parçası olarak bu köyde yetkiniz var... En az bir günlüğüne! Köye tacınızı ve soyağacınızı gösterdiğiniz takdirde bir günlüğüne linç kararını sizin vermenize izin verirler .**"
bariscill = "**Pasifist barışçıl bir insandır ve köydeki şiddete dayanamaz. Her oyunda bir kez, kendini gösterebilir ve böylece herkes sevgi ve özgürlüğün önemini hatırlayacak. Köy oy kullanamayacak .**"
ybilgee = "**Yaşlı Bilgesin 📚. Uzun yaşamın boyunca birçok iyi ve kötü insan ile karşılaştın. Bu bilgelikle, bir kişiyi günde bir kez kontrol edebilir ve başkalarını öldürüp öldüremeyeceğini öğrenebilirsin .**"
uyutucuu = "**Oyun başına bir kez, Uyutucu tüm oyuncuları o kadar derin uyutabilir. Kimse gece yeteneklerini kullanamaz .**"
kurdumsuu = "**Kurdumsu, sen aşağılık bir köylüsün. Zamanının çoğunu gerçek kurtların olduğu ormanda geçirdiğin için seni görenin kafası karışacak ve senin bir kurt adam olduğunu düşünecek! Oh hayır ...**"
sehitt = "**Sen Fedai'sin. Oyunun başında öleceğin kişiyi seçeceksin. O kişi ölürse, onun için ölürsün ve o kişi hayatta kalır. Ancak o kişi kazanırsa kazanabilirsin .**"
simyacii = "**Simyacısın. İksir yapma sanatına adanmış bir hayatın sonunda likantropinin tedavisini buldun. Ama bu zor bir görev. İksirin tamamlanması 3 gece sürer ve kurt adamlar güçlü bir koku duyusuna sahiptir. Daha da kötüsü, iksiri bir köylüye verirsen, bir kurt adama dönüşecek ve ilk iş olarak seni öldürecek .**"
efendii = "**Sen YEDEK Tarikat Avcısısın. Ustanı takip et ve işi iyice öğren, eğer o ölürse yerine sen geçeceksin .**"
guzell = "**Sen Güzelsin, en güzel ve en nazik köylüsün. Herhangi bir gece rolü, seni ziyaret etmeye veya öldürmeye çalışırsa, onun yerine güzel görünüşüne aşık olacak ve sevgili olacaksınız .**"
fgetirenn = "**Fırtına Getiren olarak, geceleri korkunç bir fırtına yaratma gücüne sahipsin. Fırtına çıkardığın gece, tüm aktif roller evlerine sığınacak ve hiçbir gece eylemi olmayacak. Gecenin herhangi bir saatinde fırtına çıkarabilirsin .**"
hainn = "**Sen bir hain, alçaksın. Bütün kurtlar ölene kadar hayatta kalırsan, bir Kurt Adam olacaksın ve geceleyin önceki masum takım arkadaşlarını öldürmeye hazır olacaksın !**"
ycocukk = "**Oyunun başında kendine rol-model birini seçeceksin. Eğer o ölürse, Kurt Adam olacaksın. Rol-modelin ölmeden tarikat olursan şansına küs. Yoluna imansız olarak devam edeceksin .**"
lanetli = "**Lanetli olarak Kurtlar seni öldürene kadar -şimdilik- normal bir köylüsün... Onlar seni öldürdüğünde sen de onlar gibi bir kurt olup gece avlanmak için özgür olacaksın ... XD**"
kurtadamm = "**Eğlence başlasın! Her gün oyuncu arkadaşlarını aldatmaya çalışacaksın ve her gece bir oyuncuyu öldürmek için seçeceksin! Not:Eğer lanetliye saldırırsan, onlar da senin gibi kurt olur! Şunu belirtmeliyim ki sarhoşa saldırırsan kendin de sarhoş olursun ve içki sersemliğiyle gelecek gece saldıramazsın!(Genellikle bu durum gelecek gece saldırı yapmana engel olur fakat Yavru Kurt öldürülürse ve Sarhoş senin ilk seçiminse, ikinci seçimini öldüremeyeceksin. Tabii ki gelecek gece saldırı yapabilirsin.) Haydin arkadaşlar !**"
alfakurtt = "**Sen Alfa Kurt’sun, lanetin kaynağı, kurtların lideri ve pisliğin tekisin. Sen hayattayken kurt takımının yediği birinin kurtadama dönüşme ihtimali %20 .**"
falcii = "**Eski yaşlı gözcüyü hatırlıyor musun? İyi, şimdi Kurt Takımı’nda olma zamanı. Falcı kuçukuçuların Gözcüsü’dür. Sadece Kurtları ve Gözcüleri görebilir. Kurtlarla beraber kazanır .**"
yavrukurtt = "**Ne tatlış bir minik kuçukuçu! Gıdı, gıdı. Dediğim gibi, sen Yavru Kurt’sun. Biri seni öldürürse, kuçukuçulara 2 kurban vereceğim. Ölmek için çok tatlısın. Daha fazla seni gıdıklayamayacağım .**"
lycann = "**Lycan da bir kurt ama gözcüye bir köylü gibi görünecek .**"
haydutt = "**Sen haydutsun. Kurtlarla ittifak kuruyorsun. Geceleri köyü gezebilir ve birinin penceresinden bakabilirsin. O kişinin uyanık olup olmadığını bileceksin. İzlediğin kişi kurt adamlar tarafından yenirse müttefiklerini öğrenebilirsin .**"
mistikk = "**Sen Mistiksin! Kurtlarla ittifak kuruyorsun. Her gece bir kişiyi lanetleyebilirsin. Bu kişi lanetlenecek ve şans eseri enfekte olursa kurt adam olacak(% 30 şans). Ama hayatına dikkat et! Lanet sadece sen yaşadığın sürece sürer .**"
duzenbazz = "**Sen Düzenbaz Kurt'sun! Siz koyun postundaki kurtsunuz, oyunda istediğiniz zaman tanrıların sizin için seçtikleri rastgele bir rol olarak ortaya çıkabilirsiniz. Ancak yalnızca mesajın görüneceğini unutmayın. Rolün etkisi olmayacak .**"
karmelekk = "**Kara Melek 👼🐺 eskiden köyün koruyucu meleğiydi, ancak kurt adamlar tarafından enfekte oldu ve dönüştü. Her gece köyün kurt adam olmayan herhangi bir üyesini öldürebilir veya bir kurt adamı koruyabilir. Seçin senin .**"
ibliss = "**İblis’in amacı basit: Linç edilmek. Eğer İblis linç edilirse o oyunu kazanır, diğer bütün saflar kaybeder .**"
tarikatcii = "**Tarikat Üyesi olarak senin görevin oyundaki diğer tüm oyuncuları (Kurtlar, Seri Katil, Kundakçı ve T.Avcısı hariç) Tarikat Üyesi yapmak. Eğer oyunun sonunda yaşayan tüm oyuncular tarikat Üyesi olursa tarikat kazanır .**"
rahipp = "**Şeyhlerin birincil amacı, insanları tarikata katılmaya ikna etmeye yardımcı olmaktır, tarikat her gece bir şeyh ile birini ziyaret eder ve tarikata dönüşme şanslarını %10 arttırır, ziyaret ettikleri kişi onları önce öldürmediği veya evde olmadığı sürece. Tarikat Şeyhi, tarikatların alfa kurdu gibidir, yani ayrı ayrı değil, diğer tarikatlarla birlikte oy kullanır. Potansiyel üyeleri ziyaret ederken yeni tarikat ile birlikte hareket ettiğinden, Tarikat; Tarikat Avcısı veya Kurt adamlar gibi tarikatı anında öldüren rolleri ziyaret ettiğinde ölme riskiyle karşı karşıyadır.\n\nTarikat Şeyhi hakkında diğer bazı yararlı gerçekler.\n• 10 veya daha fazla oyunculu oyunlarda ortaya çıkıyorlar.\n• Tarikat modda görünme şansları %35'dir.\n• Rol ağırlıkları 13 + oyundaki dönüştürülebilir rollerin sayısıdır.\n• Hırsız tarafından çalınma olasılığı %25**"
hirsizz = "**Hırsız, kanunsuz ve rolü olmayan bir kişidir. İstediği bir rolü çalmak için geceleri diğer oyunculardan birini seçer. Karşılığında rolünü kaybeden oyuncu hırsız olacak .**"
kustasii = "**Sen Kukla Ustası'sın. Başkalarını manipüle etmede bir numarasın. Her gece, hayatta kaldığın sürece, bir kişinin (veya bir grubun) senin istediğini yapması için özel güçlerini kullanabilirsin .**"
cgidenn = "**Ataların başkalarının kılığına girebiliyordu… Fakat sen onların tüm gücüne sahip değilsin. Oyunun başında bir oyuncu seç ve o ölürse onun rolüne geçeceksin.\nNot: Eğer oyuncu Tarikatçı olursa sen onun gerçek rolünü alacaksın. Eğer Vahşi Çocuk ise ve rol-modeli ölürse Kurt olursun. Yoksa onun rol-modelini alırsın.\nTarikat Çift-Giden’i dönüştüremez. (ama Çift-Giden rolünü değiştirirse yapabilir.) Aynı zamanda, Çift-Giden dönüşene kadar kazanamaz. Oyunun sonunda eğer Çift-Giden hala Çift-Giden olarak kaldıysa o zaman kaybeder.(Aşık hariç)**"
skatill = "**Akıl hastanesi zaten sıkıcı bir yerdi. Şaka şaka. Şu anda özgürsün ama her zamanki işine dönmen lazım: Soğukkanlılıkla öldürmek! Seri Katil kendi takımında yalnız bir oyuncudur. Sadece son kalan oyuncu olursa oyunu kazanır (Aşık olma durumu hariç). Seri Katil olarak herhangi birini öldürebilirsin. Kurtlar sana saldırırsa rastgele bir tanesini öldürürsün ve yaşamaya devam edersin .**"
kundakcii = "**Sen Kundakçısın 🔥. Yetişkinlerin çocukları korkutmak için söylediği ve senin yaptıklarını anlatan korku hikayeleri var. Şehirleri yerle bir edebilecek yanıcı bir çözüm için gizli bir tarifiniz var! Bu çözüm ile her gece iki evin üzerine benzin dökebilirsin. En az bir evi başarıyla benzinleyebilirsen, tüm benzinlenen evleri ateşe verebilir ve içindeki köylüleri yakabilirsin .**"
necromancerr = "Necromancer'in ölenlerin rolünü seçme şansı var. Geceleri Necromancer, oyunun geri kalan kısmı için ölü olan bir rol olmayı seçebilir. Oyunu Necromancer olarak kazanamaz. Necromancer ve Çift Giden aynı oyunda olmaz.\n( Necromancer = Büyücü )"

rols = "**🗒️ Lütfen Bir Takım Seçin ...**"
bilgis = "**🗒️ Lütfen Bir Rol Seçin ...**"
