from config import *

smesajs = ["Hoş Geldin 💕", "Nasılsın 😌", "Seni Özledim 💕", "Nerdesin sen 🙄", "Gel oyun oynayalım ✨", "Şarkı dinleyelim mi 🤭",]
bottst = ["Bana mı dedin bot diye ?", "Ben bot değilim bi kere 🙄", "Bi daha bot dersen 🤬", "Hala bot diyor ya 😡", "Adamı hasta edersin 🙄", "Olm dayak yersin ama 😬",]
gmze = ["ᴋᴇɴᴅɪ̇sɪ̇ ᴄᴇɴɴᴇᴛᴛᴇ ʜᴀʟᴀʏ ᴄ̧ᴇᴋɪ̇ʏᴏʀ 😂", "ᴀʟғᴀ ᴋᴀᴅɪɴ 💋", "ɢᴜ̈ᴢᴇʟʟɪ̇ᴋ ᴀʙɪ̇ᴅᴇsɪ̇ ❣️", "ᴇᴘᴇʏᴅɪ̇ʀ, ᴀᴛᴀʀʟɪ ʙɪ̇ ʜᴀᴛᴜɴ ɢᴏ̈ʀᴇᴍᴇᴅɪ̇ᴋ 🤭",]
bkt = ["He canım ✨", "He aşkım 💕", "Duygularım darmadağın !", "Efendim tatlım 💞", "Bana mı seslendin 🙄", "Yaw ne ne aaaa", "Seni dinliyorum gülüm 🥰", "Al sana harçlık 💰", "Başımın etini yedin 🙄", "Seni tokatlarım 😏", "Buyrun benim ?", "Offff 🙄", "Vay arkadaş bu çocuk abayı yakmış 😅", "Sus artik Sus !", "Dost elinden yaralıyam 😔", "Kırık kalbimi onarır mısın ?", "Seni seviyorum bitanem 💕", "Gel seni öpim 😘", "Dile benden ne dilersen", "Benim başım ağrıyor 🥺", "Yar beni sevmez !", "Şarkı söyleyelim mi ✨", "Efendim hocam ?",]
selam = ["ve aleyküm selam hoş geldin yahu", "Aleyküm Selam Naber 🎉", "Selam Hoş Geldin", "Ase, Hoş Geldin 💕",]
nasilsin = ["Senle iyi, Sen ?", "İyiyim senden naber", "İyiyim sen", "İyim fıstık, ya sen 💕", "Teşekkür ederim iyiyim sen nasılsın", "Tıpkı senin gibi mükemmelim 🥳",]
adam = ["Mermiler seksin, alemde teksin 😏", "Mermiler seksin, tokatımı yersin 😏",]
iyiyim = ["İyi olmana sevindim", "Hep daha iyi olman dileğiyle  ", "Keşke bende senin kadar iyi olsam 😏",]
hoş = ["Naber", "Hoş buldum nabıyon", "Nasılsın",]
merhaba = ["Merhaba, Hoş geldin", "Merhabalar Hoş geldiniz efem 🥳", "Merhaba, nerelerdesin ya sen", "yine özlettin kendini 😏",]
ban = ["İmdatttt, grup boşalıyor 😱", "Grupta üye kalmadı mübarek 🙄", "Ayıp ettin !", "Bak sen 🤔", "Adamın dibisin sen :)", "Grub boşalıyor yetişin .",]
nabiyon = ["Oturuyorum, sen", "Gördüğün gibi takılıyoruz", "Yapacak bişey yok", "Ne yapmamı istersin",]
uzgun = ["Kıyamam ki ben sana 😢", "Üzülme, buda geçer 😔", "Bizi üzenler utansın 😏", "Hoppala, kim üzdü seni",]
valla = ["tamam, tamam inandım 🥴", "de valla", "Deme öyle Allah çarpar", "Sus çarpılırsin .",]
sg = ["Küfür etme turşu !", "Lütfen düzgün konuş 😏", "Dayanamıyacam ben artık ama ...", "Ben buna dalarım ama ...",]
mal = ["Akıllı görünce kıskandı 😏", "Sana özeniyorum, galiba başarıyorum 🙈", "Beni birine benzettin galiba 🙄", "Hop, orda dur beni daha fazla sinirlendirmeyin lütfen ...",]
balim = ["Arı mısın gülüm 🙈", "Canın çektiyse yiyebilirsin beni 😋", "Efendim, hayatım .", "Şımarıyorum ama 🙈",]
canim = ["Gülüm 💕", "Bebeğim 💕", "Bitanem 💕", "Hayatım 💕", "Turşu suratlım 💕",]
gidiyorum = ["Nereye, Karpuz Kesmiştik .", "Hoşuma yeterince gittin, otur oturduğun yerde 🤫", "Görüşürüz, Hakkını helal et ...", "Kal desem kalır mı acaba 🤔",]
sinirlendim = ["Farkettim .", "Sakin ol, Şampiyon .", "Bakıyorum da Domates gibi kızardın .", "Ne yapayım .",]
tanis = ["Olur tanışalım .", "Kim olduğunu biliyorum :)", "Kendini tanıt !", "Düşünmem gerek 🤔",]
adne = ["Buket, ya senin ?", "Sen söylersen bende söylerim 😏", "Söylemem, banane .", "Ben de Buket memnun oldum ❣️",]
iyisen = ["Bende iyiyim teşekürler .", "Senin gibi iyi olamıyorum 😔", "Birazcık kötüyüm .", "Mükemmelim tıpkı senin gibi 🤭",]
gullu = ["Ne gülüyon?", "Açıkta bişey mi gördün .", "Bakıyorum da keyfin yerinde .", "Mutlu olmana sevindim 💕",]
buyuk = ["Senden Büyük Allah var 😎", "Yalan söyleme .", "Hayır, Küçük ✓",]
aiko = ["Buyrun, Asistanı olurum ?", "Aiko kadar başına taş düşsün emi .", "Öldü artık yok 🙄", "zıkkım ne var ne 😑",] 
gnyy = ["Günaydın, naber", "Günüm aydı, hoş geldin 🎉", "Günaydın, tatlım .", "Güneşim doğdu, hoş geldin 🥳",]
igece = ["Tatlı rüyalar 🎉", "İyi geceler, görüşürüz .", "Gecen güzel geçsin kalbi güzel insan .", "Bir günün daha sonuna geldik, iyi geceler .",]
kyas = ["Yaşın bi önemi var mı ?", "Tahmin et kaç yaşındayım .", "Senden büyük olduğum kessin .",]
nereli = ["Dünyalı, ya sen", "Ben bir yerli değilim 😔", "Galiba Dünyanın bir yerindenim .",]
pms = ["Susmasam ne olur 😳", "Lan sus 🙄", "Sen konuşma 🤭", "Hayır, Konuşacam 🙄", "SEN KONUŞMA SONERRRR 😂",]
krdn = ["Ya kıyamam 😔", "Gel sarılalım .", "Oh iyi oldu .",]
skdm = ["Bende, ne yapalım ?", "Benden sıkıldın mı ?", "Hadi uyuyalım .", "Oyun oynayalım mı ?",]
hms = ["hmmmm 🙄", "Yeter ama aaaa 🙄", "Kafana sıkarım senin 🙄",]
bts = ["Sağolun 😔", "Eyvallah Ciğerim .",]
trt = ["Oyun mu istiyorsun /turet yaz .", "/d mi /c mi !", "aaaa oyun oynamayı unuttuk 😬 derhal /sayi yaz .",]
evt = ["Bi sus ya", "Hayır", "Hayır ulan hayır !", "yioooooooo",]
hyrr = ["la havle vela kuvvete", "Ne demek hayır 🙄", "Evet ...", "Evet ulan evet !",]
gzs = ["Gözler ömre bedel 😂", "Yukarıda ne var 🤔", "Tahtalı köyü mü arıyon mübarek 😲",]
ofs = ["pffffff", "of deme oh de 🤪", "Bakıyorum da oflamaya başladın 🙄",]
cklta = ["Aaaaa çok severim 💕", "Bana Çikolata Alsana 🥺", "Çikolatam olur musun 😋",]
lna = ["Lan mı, memleket bize Ana diyor 🙄", "Ne var lan 🙄", "Bana mı dedin 😠", "Lannnnn sus 🙄",]
dddm = ["Duymadım 😜", "Ne dedin ?", "Anlamadım ?", "Neden öyle dedin ?",]
ylna = ["Yalan söyleyen kim 🙄", "Yalan konuşmayın çarparım 🙄", "Terbiyesiz 😠",]
sgll = ["Sende sağol 💕", "Başımız sağolsun .",]
crkn = ["Kimmiş çirkin olan 🙄", "Ben çok güzelim 🙈", "Sus artık 🙄",]
dmy = ["Banın hayırlı olsun 🙄", "Şşşş, yasak ...", "Seni döverim bak 🙄",]
tymm = ["Midemden tuhaf bir ses geliyor 😸", "Galiba acıktım 😋", "Olsa da yesek 🥺",]
kmm= ["Olm sinirleniyorum ama 😬", "Bana bak 🙄", "Seni yollarım 😁", "Acımam ama 😁", "Sen şimdi hapı yuttun 😳",]
kankas = ["Efendim canım 💕", "Kanka diyen ağzını 😁", "Bana mı dedin lan 😳", "Bi daha dersen, fena olur 🙄",]
opsss = ["Muahhhhhhh 😘", "Utandırma beni 🤭", "Yanaş bakim 😲",]
sgne = ["Nasıl sanane 🙄", "Asıl sanane 😏", "Seni alakadar etmez 😏",]
bgne = ["Yok öyle yama 😏", "Asıl banane 😏", "Şşşş bidaha duymim 🙄",]
bnen = ["Hayır ben !", "Yok öyle yama !", "Ben ulan ben 🙄",]
snen = ["Evet ben !", "Eeeee...", "Hayır sen !",]

ibaslama = "🎂 ᴇᴛɪ̇ᴋᴇᴛʟᴇᴍᴇʏᴇ ʙᴀşʟɪʏᴏʀᴜᴍ ʙᴇʙᴇɢ̆ɪ̇ᴍ !"
nogroup = "🔹 ʙᴜ ᴋᴏᴍᴜᴛᴜ ɢʀᴜᴘʟᴀʀᴅᴀ ᴋᴜʟʟᴀɴ !"
noadmin = "😏 ʏᴏ̈ɴᴇᴛɪ̇ᴄɪ̇ ᴅᴇɢ̆ɪ̇ʟsɪ̇ɴ ʙᴇʙᴇɢ̆ɪ̇ᴍ !"
botnoadmin = "😡 ʙᴇɴɪ̇ ʏᴏ̈ɴᴇᴛɪ̇ᴄɪ̇ ʏᴀᴘɪɴ ʟᴀɴ !"

emj = " ❤️ 🧡 💛 💚 💙 💜 🖤 🤍 🤎 🙂 🙃 😉 😌 😍 🥰 😘 😗 😙 😚 😋 😛 😝 😜 🤪 🤨 🧐 🤓 😎 🤩 🥳 😏 😒 " \
        "😞 😔 😟 😕 🙁 😣 😖 😫 😩 🥺 😢 😭 😤 😠 😡 🤯 😳 🥵 🥶 😱 😨 😰 😥 😓 🤗 🤔 🤭 🤫 🤥 😶 😐 😑 😬 🙄 " \
        "🌦 🍃 🎋".split(" ")

rutbe = (
"ᴇᴍɴɪʏᴇᴛ ᴍᴜ̈ᴅᴜ̈ʀᴜ̈", "ᴇᴍɴɪʏᴇᴛ ᴀᴍɪʀɪ", "ʙᴀşᴋᴏᴍɪsᴇʀ", "ᴋᴏᴍɪsᴇʀ", "ᴏʀɢᴇɴᴇʀᴀʟ", "ᴋᴜʀᴍᴀʏ", "ᴘɪʏᴀᴅᴇ", "sᴜ̈ᴠᴀʀɪ", "ᴛᴀɴᴋᴄ̧ɪ", "ᴛᴏᴘᴄ̧ᴜ", "ᴋᴏʀɢᴇɴᴇʀᴀʟ", "ᴛᴜ̈ᴍɢᴇɴᴇʀᴀʟ", "ᴛᴜɢ̆ɢᴇɴᴇʀᴀʟ",
)

gsos = (
"ʙᴀʟʟɪ ʟᴏᴋᴍᴀᴍ 🍯", "ᴋᴀʏᴍᴀɢ‌ɪᴍ 🎂", "sᴜ‌ᴛʟᴜ‌ ᴄ‌ᴏ‌ʀᴇɢ‌ɪ‌ᴍ 🍩", "ʙᴀʟ ᴋᴀʙᴀɢ‌ɪᴍ 🎃", "ᴄᴀɴ ᴅᴏsᴛᴜᴍ 💕", "ʙɪ‌ʀ ᴛᴀɴᴇᴍ ❤️‍🔥", "ʙᴏ‌ʙʀᴇɢ‌ɪ‌ᴍ 🫀", "ᴋᴀs‌ᴀʀʟɪ ᴛᴏsᴛᴜᴍ 🥪", "ᴀʏɪᴄɪɢ‌ɪᴍ 🧸", "ᴛᴀᴛʟɪ ᴀʏɪᴄɪᴋ 🐻",
)

guzelsoz = (
'ᴀŞᴋ ʙɪʀ ᴋᴀᴅɪɴɪɴ ʏᴀŞᴀᴍɪɴɪɴ ᴛÜᴍ ÖʏᴋÜꜱÜ, ᴇʀᴋᴇĞɪɴ ɪꜱᴇ ʏᴀʟɴɪᴢᴄᴀ ʙɪʀ ꜱᴇʀÜᴠᴇɴɪᴅɪʀ ...','ʜᴇʀŞᴇʏɪ ᴅᴇɴᴇʀɪᴍ; ᴀᴍᴀ ʏᴀᴘᴀʙɪʟᴅɪᴋʟᴇʀɪᴍɪ ʏᴀᴘᴀʀɪᴍ ...','ʏᴀɴʟɪŞ ʙɪʟᴅɪĞɪɴ ʏᴏʟᴅᴀ; ʜЕʀᴋЕꜱʟЕ ʏÜʀÜʏЕᴄЕĞɪɴЕ, ᴅᴏĞʀᴜ ʙɪʟᴅɪĞɪɴ ʏᴏʟᴅᴀ; ᴛЕᴋ ʙᴀŞɪɴᴀ ʏÜʀÜ ...','ᴏ ᴅᴀ ɢᴀᴢɪ ᴏʟᴍᴀᴋ ɪꜱᴛᴇᴅɪ, ꜰᴀᴋᴀᴛ ᴏɴᴀ ᴀɴʟᴀᴛᴍᴀᴋ ɢᴇʀᴇᴋᴛɪ ᴋɪ, Şᴇʜɪᴅ ᴏʟᴍᴀʏɪ ɢÖᴢᴇ ᴀʟᴀᴍᴀʏᴀɴ ɢᴀᴢɪ ᴏʟᴀᴍᴀᴢᴅɪ ...','ɴᴇ ᴋᴀᴅᴀʀ ʏÜᴋꜱᴇʟɪʀꜱᴇɴ, ᴜÇᴍᴀʏɪ ʙɪʟᴍᴇʏᴇɴʟᴇʀᴇ ᴏ ᴋᴀᴅᴀʀ ᴋÜÇÜᴋ ɢÖʀÜɴÜʀꜱÜɴ ...',
'ɴᴇ ᴋᴀᴅᴀʀ ʜᴀᴢɪɴ ʙɪʀ ÇᴀĞᴅᴀ ʏᴀŞɪʏᴏʀᴜᴢ, ʙɪʀ Öɴʏᴀʀɢɪʏɪ ᴏʀᴛᴀᴅᴀɴ ᴋᴀʟᴅɪʀᴍᴀᴋ ᴀᴛᴏᴍᴜ ᴘᴀʀÇᴀʟᴀᴍᴀᴋᴛᴀɴ ᴅᴀʜᴀ ɢÜÇ ...','ᴍᴜᴛʟᴜʟᴜᴋ ʜᴇʀ Şᴇʏᴅᴇɴ Öɴᴄᴇ ᴠÜᴄᴜᴛ ꜱᴀĞʟɪĞɪɴᴅᴀᴅɪʀ ...','ʙᴀᴢᴇɴ ʙɪʀ Şᴇʏᴇ ꜱᴏɴ ᴠᴇʀᴍᴇᴋ ɪÇɪɴ ɪꜱᴛᴇᴍᴇᴅɪĞɪɴ ʙɪʀ Şᴇʏ ʏᴀᴘᴍᴀɴ ɢᴇʀᴇᴋɪʀ ...','ᴋɪᴍ ᴋᴀᴢᴀɴᴍᴀᴢꜱᴀ ʙᴜ ᴅÜɴʏᴀᴅᴀ ʙɪʀ ᴇᴋᴍᴇᴋ ᴘᴀʀᴀꜱɪ ʏᴀ ᴅᴏꜱᴛᴜɴᴜɴ ʏÜᴢ ᴋᴀʀᴀꜱɪ ʏᴀ ᴅᴀ ᴅÜŞᴍᴀɴɪɴɪɴ ᴍᴀꜱᴋᴀʀᴀꜱɪ ...','ᴀᴠᴜᴄᴜ ᴋᴀᴅᴀʀ ʏÜʀᴇĞɪ ᴏʟᴍᴀʏᴀɴ ɪɴꜱᴀɴʟᴀʀɪ ᴋÜʀᴇᴋ ɢɪʙɪ ᴅɪʟɪ ᴠᴀʀ ...','ᴍᴜᴛʟᴜʟᴜᴋ ʜᴇʀ Şᴇʏᴅᴇɴ Öɴᴄᴇ ᴠÜᴄᴜᴛ ꜱᴀĞʟɪĞɪɴᴅᴀᴅɪʀ ...',
'ᴏᴋʏᴀɴᴜꜱᴛᴀ Öʟᴍᴇᴢ ᴅᴇ ɪɴꜱᴀɴ, ɢɪᴅᴇʀ ʙɪʀ ᴋᴀŞɪᴋ ꜱᴇᴠᴅᴀᴅᴀ ʙᴏĞᴜʟᴜʀ ...','ᴍᴜᴛʟᴜʟᴜᴋ ʜᴇʀ Şᴇʏᴅᴇɴ Öɴᴄᴇ ᴠÜᴄᴜᴛ ꜱᴀĞʟɪĞɪɴᴅᴀᴅɪʀ ...','ɴᴇʀᴇʏᴇ ɢɪᴛᴛɪĞɪɴɪ ʙɪʟᴍɪʏᴏʀꜱᴀɴ, ʜᴀɴɢɪ ʏᴏʟᴅᴀɴ ɢɪᴛᴛɪĞɪɴɪɴ ʜɪÇʙɪʀ Öɴᴇᴍɪ ʏᴏᴋᴛᴜʀ ...','ʙᴀᴢᴇɴ ɪʟᴋ ɢÖʀÜŞᴛᴇ ʙɪʟɪʀꜱɪɴ, ᴏ ɪɴꜱᴀɴ ꜱᴇɴɪɴ ᴋᴀᴅᴇʀɪɴᴅɪʀ. ʙᴀᴢᴇɴ ʙɪʀ ÖᴍÜʀ ᴀʀᴀʀꜱɪɴ, ʙᴜʟᴜɴᴍᴀᴢ ...','ʟᴀɴᴇᴛ ᴏʟꜱᴜɴ. ɴᴇ ᴍᴜᴀᴢᴢᴀᴍ Şᴇʏ ꜱᴇɴɪ ꜱᴇᴠᴍᴇᴋ ...','ʏᴀʀɪᴍ ɴᴇꜰᴇꜱʟɪᴋ ʙᴜ ʜᴀʏᴀᴛᴛᴀ. ꜱᴇᴠɢɪᴅᴇɴ ʙᴀŞᴋᴀ ʜɪÇʙɪʀ Şᴇʏ ᴘʟᴀɴʟᴀᴍᴀ ...',
'İʟɪᴍ ᴀŞᴀĞɪᴅᴀᴋɪʟᴇʀɪ ʏÜᴋꜱᴇʟᴛɪʀ, ᴄᴀʜɪʟʟɪᴋ ɪꜱᴇ ʏÜᴋꜱᴇᴋᴛᴇᴋɪʟᴇʀɪ ᴀʟÇᴀʟᴛɪʀ ...','ᴋɪᴍ ɪʟɪᴍ ᴀʀᴀᴍᴀ ʏᴏʟᴜɴᴅᴀ ᴏʟᴜʀꜱᴀ, ᴄᴇɴɴᴇᴛ ᴅᴇ ᴏɴᴜ ᴀʀᴀᴍᴀ ʏᴏʟᴜɴᴅᴀ ᴏʟᴜʀ ...','ʏᴀɴɪʟᴛᴍᴀꜱɪɴ ꜱᴇɴɪ ᴍᴀꜱᴜᴍ ʙᴀᴋɪŞʟᴀʀ, ʙᴀᴢɪʟᴀʀɪɴɪ Şᴇʏᴛᴀɴ ᴀʏᴀᴋᴛᴀ ᴀʟᴋɪŞʟᴀʀ ...','İɴꜱᴀɴʟᴀʀɪ ᴛᴀɴɪŞɪʀᴋᴇɴ ᴅᴇĞɪʟ, ᴛᴀʀᴛɪŞɪʀᴋᴇɴ ᴛᴀɴɪʀꜱɪɴ. ÇÜɴᴋÜ Öꜰᴋᴇ, ꜱᴀʟʟᴀɴᴀɴ ᴋɪŞɪʟɪĞɪ ᴏʀᴛᴀʏᴀ Çɪᴋᴀʀɪʀ ...','ɢᴇʀÇᴇᴋ ᴀŞᴋ ɪÇɪɴ ᴀꜱʟᴀ ʙɪʀ ᴢᴀᴍᴀɴ ʏᴀ ᴅᴀ ʏᴇʀ ʏᴏᴋᴛᴜʀ ...','ᴇĞᴇʀ ᴅᴏĞʀᴜʏᴜ ꜱÖʏʟᴇʀꜱᴇɴ ʜɪÇʙɪʀ Şᴇʏɪ ʜᴀᴛɪʀʟᴀᴍᴀᴋ ᴢᴏʀᴜɴᴅᴀ ᴅᴇĞɪʟꜱɪɴ ...',
'ʜᴇʀ ᴇʟɪɴɪ ꜱɪᴋᴀɴʟᴀ ᴅᴏꜱᴛ, ʜᴇʀ ᴄᴀɴɪɴɪ ꜱɪᴋᴀɴʟᴀ ᴅÜŞᴍᴀɴ ᴏʟᴍᴀ ...','ᴇᴅᴇᴘ ᴀᴋʟɪɴ ᴛᴇʀᴄÜᴍᴀɴɪᴅɪʀ. ʜᴇʀᴋᴇꜱ ᴇᴅᴇʙɪ ᴋᴀᴅᴀʀ ᴀᴋɪʟʟɪ, ᴀᴋʟɪ ᴋᴀᴅᴀʀ Şᴇʀᴇꜰʟɪ, Şᴇʀᴇꜰɪ ᴋᴀᴅᴀʀ ᴅᴇĞᴇʀʟɪᴅɪʀ ...','ʏᴀŞɪɴ ᴅᴇĞɪʟ ʏᴀŞᴀᴅɪᴋʟᴀʀɪɴ ÖĞʀᴇᴛɪʀ ꜱᴀɴᴀ ʜᴀʏᴀᴛɪ ...','Şᴜɴᴜ ᴀꜱʟᴀ ᴜɴᴜᴛᴍᴀ; ɢÜʟᴇʀᴋᴇɴ ᴋᴀʏʙᴇᴛᴛɪᴋʟᴇʀɪɴɪ, ᴀĞʟᴀʏᴀʀᴀᴋ ᴋᴀᴢᴀɴᴀᴍᴀᴢꜱɪɴ ...','ꜰᴀᴢʟᴀ ʙÜʏÜᴛᴍᴇ ᴋᴇɴᴅɪɴɪ, ᴇɴ ꜰᴀᴢʟᴀ ꜱᴇᴠᴇʙɪʟᴅɪĞɪᴍ ᴋᴀᴅᴀʀꜱɪɴ; ᴅᴀʜᴀꜱɪ ʏᴏᴋ ...','ᴀŞᴋ Çᴏᴋ ᴋɪꜱᴀ ᴀᴍᴀ ᴜɴᴜᴛᴍᴀꜱɪ Çᴏᴋ ᴢᴏʀ ...',
'İʏɪʏɪ ᴀʀᴀ, ᴅᴏĞʀᴜʏᴜ ᴀʀᴀ, ɢÜᴢᴇʟɪ ᴀʀᴀ ꜰᴀᴋᴀᴛ ᴋᴜꜱᴜʀᴜ ᴀʀᴀᴍᴀ ...','ʜᴀʏᴀᴛɪ ɢÖᴢʏᴀŞʟᴀʀɪɴʟᴀ ÖᴅÜʟʟᴇɴᴅɪʀᴇᴄᴇĞɪɴᴇ; ɢÜʟÜᴄÜᴋʟᴇʀɪɴʟᴇ ᴄᴇᴢᴀʟᴀɴᴅɪʀ ...','ᴜᴢᴀᴋᴋᴇɴ ʙɪʟᴇ ʙɪʀ ɴᴇꜰᴇꜱ ᴋᴀᴅᴀʀ ʏᴀᴋɪɴɪᴍᴅᴀꜱɪɴ ...','ʜᴇʀ ᴍÜɴᴀᴋᴀŞᴀɴɪɴ ᴛᴇᴍᴇʟɪɴᴅᴇ ʙɪʀɪꜱɪɴɪɴ ᴄᴀʜɪʟʟɪĞɪ ʏᴀᴛᴀʀ ...','ʙɪʟɢᴇʟɪᴋ ᴋᴀʟᴘᴛᴇɴ ɢᴇʟɪʀ. ᴀᴋɪʟʟᴀ ɪʟɢɪꜱɪ ʏᴏᴋᴛᴜʀ. ʙɪʟɢᴇʟɪᴋ, ᴠᴀʀʟɪĞɪɴɪɴ ᴇɴ ᴅᴇʀɪɴ ɴᴏᴋᴛᴀꜱɪɴᴅᴀɴ Çɪᴋᴀʀ. ᴋᴀꜰᴀʏᴀ ᴀɪᴛ ᴅᴇĞɪʟᴅɪʀ ...',
'ʏᴀŞᴀᴅɪĞɪɴ ʏᴇʀɪ ᴄᴇɴɴᴇᴛ ʏᴀᴘᴀᴍᴀᴅɪĞɪɴ ꜱÜʀᴇᴄᴇ ᴋᴀÇᴛɪĞɪɴ ʜᴇʀ ʏᴇʀ ᴄᴇʜᴇɴɴᴇᴍᴅɪʀ ...','ᴋɪʀɪʟᴍɪŞ ʙɪʀɪ Çᴏᴋ ɢÜᴢᴇʟ ꜱᴜꜱᴀʀ. ʜᴇʀ Şᴇʏɪɴᴇ ʜᴀꜱʀᴇᴛ ᴋᴀʟɪʀꜱɪɴ ...','İɴᴀɴÇ, ᴘᴀʀÇᴀʟᴀɴᴍɪŞ ʙɪʀ ᴅÜɴʏᴀɴɪɴ ɪŞɪĞᴀ ÇɪᴋᴀᴄᴀĞɪ ɢÜÇᴛÜʀ ...','ʙᴇʟᴋɪ ᴅᴇ ɪɴꜱᴀɴ ʜᴇʀ Şᴇʏɪ ɪÇɪɴᴇ ᴀᴛᴍᴀᴋᴛᴀɴ ʙᴏĞᴜʟᴜʏᴏʀ ᴢᴀᴍᴀɴʟᴀ ...','ᴀŞᴋ ʙɪʀ ᴋᴀᴅɪɴɪɴ ʏᴀŞᴀᴍɪɴɪɴ ᴛÜᴍ ÖʏᴋÜꜱÜ, ᴇʀᴋᴇĞɪɴ ɪꜱᴇ ʏᴀʟɴɪᴢᴄᴀ ʙɪʀ ꜱᴇʀÜᴠᴇɴɪᴅɪʀ ...','ᴀŞᴋ ʀÜᴢɢᴀʀ ɢɪʙɪᴅɪʀ, ɢÖʀᴇᴍᴇᴢꜱɪɴ ᴀᴍᴀ ʜɪꜱꜱᴇᴅᴇʙɪʟɪʀꜱɪɴ ...',
'ᴅᴇĞɪŞɪᴍ ᴇʙᴇᴅɪ, ÖʟÜᴍꜱÜᴢʟÜᴋ ᴋᴀʟɪᴄɪᴅɪʀ ...','ᴋÖʀʟᴇʀɪɴ Üʟᴋᴇꜱɪɴᴅᴇ, ᴛᴇᴋ ɢÖᴢʟÜ ɪɴꜱᴀɴ ᴋʀᴀʟ ᴏʟᴜʀ ...''ᴏʏꜱᴀ ʏÜʀᴇĞɪ ᴛᴇᴍɪᴢ ᴏʟᴍᴀʏᴀɴɪɴ, ᴀɴʟᴀʏɪŞɪ ᴅᴀ ᴋɪᴛᴛɪʀ ...','ʜɪÇ ʙᴜ ᴋᴀᴅᴀʀ ꜱᴜꜱᴍᴀᴋ ɪꜱᴛᴇᴍᴇᴍɪŞᴛɪᴍ ...','ŞÜᴋʀᴇᴛᴍᴇʏɪ ÖĞʀᴇɴᴍᴇʏᴇɴ ɴᴀɴᴋÖʀ ᴇʟʙᴇᴛᴛᴇ ŞɪᴋÂʏᴇᴛ ᴇᴅᴇʀ ...','Öʏʟᴇ ʙɪʀ ɢᴇʟ ᴅᴇᴍᴇʟɪꜱɪɴ ᴋɪ, ᴍᴇꜱᴀꜰᴇʟᴇʀ ᴀɴʟᴀᴍɪɴɪ ʏɪᴛɪʀᴍᴇʟɪ ...',
'ꜱᴀʙɪʀ ᴠᴀᴢɢᴇÇᴍᴇᴋ ᴅᴇĞɪʟ, ᴜᴍᴜᴅᴜ ʏᴀʀɪɴᴀ ᴇʀᴛᴇʟᴇᴍᴇᴋᴛɪʀ ...','ꜱᴇᴠᴅɪᴋʟᴇʀɪɴɪᴢᴇ ᴢᴀᴍᴀɴ ᴀʏɪʀɪɴ ʏᴏᴋꜱᴀ ᴢᴀᴍᴀɴ ꜱɪᴢɪ ꜱᴇᴠᴅɪᴋʟᴇʀɪɴɪᴢᴅᴇɴ ᴀʏɪʀɪʀ ...','ʙᴀŞᴋᴀꜱɪɴɪɴ ÖɴÜɴÜ ᴀʏᴅɪɴʟᴀᴛɪʀᴋᴇɴ ᴋᴇɴᴅɪ ʏᴏʟᴜᴍᴜᴢᴀ ᴅᴀ ɪŞɪᴋ ᴛᴜᴛᴀʀɪᴢ ...','ʜᴇʀᴋᴇꜱ ᴀʏɴɪ Şᴇʏɪ ᴅÜŞÜɴÜʏᴏʀꜱᴀ, ʜɪÇ ᴋɪᴍꜱᴇ ꜰᴀᴢʟᴀ ʙɪʀ Şᴇʏ ᴅÜŞÜɴᴍÜʏᴏʀ ᴅᴇᴍᴇᴋᴛɪʀ ...','İÇɪɴᴇ ᴀᴛᴛɪᴋʟᴀʀɪɴ ᴋᴇᴅᴇʀɪɴᴅɪʀ. İÇɪɴᴅᴇɴ ᴀᴛᴀᴍᴀᴅɪᴋʟᴀʀɪɴ ᴋᴀᴅᴇʀɪɴ ...',
'ᴍᴜᴛʟᴜ ᴍᴜ ᴏʟᴍᴀᴋ ɪꜱᴛɪʏᴏʀꜱᴜɴ , ᴋɪᴍꜱᴇᴅᴇɴ ʙɪʀ Şᴇʏ ʙᴇᴋʟᴇᴍᴇ ...','ɢÜᴢᴇʟɪ ɢÜᴢᴇʟ ʏᴀᴘᴀɴ ᴇᴅᴇᴘᴛɪʀ, ᴇᴅᴇᴘ ɪꜱᴇ ɢÜᴢᴇʟɪ ꜱᴇᴠᴍᴇʏᴇ ꜱᴇʙᴇᴘᴛɪʀ ...','ʏᴏʀᴍᴀ ᴋᴇɴᴅɪɴɪ... ʙɪʀᴀᴋ ʜᴀʏᴀᴛɪɴᴀ ᴇŞʟɪᴋ ᴇᴛᴍᴇᴋ ɪꜱᴛᴇʏᴇɴʟᴇʀ ꜱᴇɴɪɴʟᴇ ɢᴇʟꜱɪɴ ...','ʙɪʀÇᴏᴋ ɪɴꜱᴀɴ ᴍᴜᴛʟᴜʟᴜĞᴜ, ʙᴜʀɴᴜɴᴜɴ ÜꜱᴛÜɴᴅᴇ ᴜɴᴜᴛᴛᴜĞᴜ ɢÖᴢʟÜᴋ ɢɪʙɪ ᴇᴛʀᴀꜰᴛᴀ ᴀʀᴀʀ ...','ᴅÜʀÜꜱᴛ ᴏʟᴍᴀᴋᴛᴀɴ ᴋᴏʀᴋᴍᴀ, ᴋᴀʏʙᴇᴅᴇᴄᴇĞɪɴ ᴇɴ ꜰᴀᴢʟᴀ ʏᴀɴʟɪŞ ɪɴꜱᴀɴʟᴀʀ ᴏʟᴜʀ ...',
)

sor = (
'Bu Grupta En Çok Sevdiğin Kişi Kimdir ...','En Çok Gitmek İstediğin Ülke Neresidir ...','Medeni Halin Nedir ...','Özlediğin Bir Kimse Var Mı ...','Fotojenik Misin Kanka ...','Dans Etmeyi Sever Misin ...','Eski Sevgilinin Adı Ne ...','En Sevdigin Film Hangisi ...','En Sevdiğin Sanatçı Kim ...','Ünlü veya Fenomen Olmak İster Misin ...','Gözlerinin Rengi Nedir ...','Boyun Kaç Santim :)',
'Bugün için Bir Planın Var Mı ...','Birini Kahraman Yapan Nedir ...','Bir Dilek Hakkın Olsa Ne Dilerdim ...','Çocukken En Büyük Hayalin Neydi ...','Aşka İnanır Mısın ...','Bir Hedefin Var Mı ...','Karanlıktan Korkar Misin ...','Müzik Dinlemeyi Sever Misin ...','Sizce Anlaşılmak Kolay Mı ...','En Sevdiğin Ders Nedir ...','Nabiyosun Aslanım ...',
'Bu Grupta Sevdiğin Birini Etiketle ...','Bu Gruptaki En Yakışıklı Kişiyi Etiketleyin ...','Bu Gruptaki En Güzel Kız Kim ...','Sizce Gruptaki En Akıllı Kişi Kim ...','Kadere İnanır Mısın ...','Hayatından Memnun Musun ...','Hey, Sen Çok Şanslısın ...','En sevdiğin Ninja Kaplumbağa hangisiydi ...','Güliver olsaydın devler ülkesine mi yoksa cüceler ülkesine mi düşmek isterdin ...',
'En sevdiğin Pokemon hangisi ...','Çocukken izlemeyi en çok sevdiğin çizgi filmler hangileriydi ...','Dünyaya bir dahaki gelişinde hayvan olarak gelseydin hangi hayvan olmak isterdin ...','Bir şiir olsaydın hangi şiir olurdun ...','En sevdiğin Ninja Kaplumbağa hangisiydi ...','Issız bir adaya düşseydin yanına kesinlikle ‘’almayacağın’’ üç şey ne olurdu ...','Küçükken hiç pembe dizi izledin mi, İzlediysen hangisi ...',
'Sihirli bir değneğin olsaydı öncelikle neyi değiştirirdin ...','Arkadaşının sırrını 1 milyon dolar karşılığında ifşa eder miydin ...','Bir dizinin içine ışınlanmak isteseydin bu hangi dizi olurdu ...','Filmlerdeki kötü karakterlerden biri olsaydın hangisi olurdun ...','Küçükken oynamayı en sevdiğin atari oyunu hangisiydi ...','Şu an okuduğun iyi bir kitap var mı , Öneriyor musun ...','Hangi dizileri izliyorsun ...','En son hangi filmi izledin ...',
'Telefonunuzda olmadan yaşayamayacağınız herhangi bir uygulama var mı ...','Hayatın geri kalanında sadece bir film türünü izleyebiliceksen, ne olurdu ...','Herkesin sevdiği sizin nefret ettiğiniz bir kitap var mı, ya da tam tersi ...','Seni ağlatan en son film ne oldu, veya yüksek sesle güldüren ...','İnstagramda kesin takip et dediğin birisi var mı ...','En sevdiğin kitabın ismi ne ...','En son hangi diziyi tek oturuşta bitirdin ...',
'Çocukluğunda en sevdiğin çizgi film hangisiydi ...','Çocukluğunda en sevdiğin çizgi film karakteri hangisiydi ...','İzlemeyi en çok sevdiğin film türü ne ...','Telefonunun ekran süresi ortalama kaç saat ...','Spor yapmayı sever misin ...','Voleybol maçları izler misin ...','Sevdiğin spor dalı ne ...','Çocukken aşık olduğun kurgusal bir karakter var mıydı ...','Sonsuza kadar sadece bir kitap okuyacak olsan bu hangi kitap olurdu ...',
'En sevdiğin distopik eser hangisi ...','Hangi tür kitaplar okumayı seviyorsun ...','Kahve içmek istediğin kitap karakteri var mı ...','Takip ettiğin bir influencer var mı ...','En çok hangi influencerın önerdiği ürünleri kullanıyorsun ...','Okurken ağlamana  neden olacak bir kitap oldu mu ...','En sevdiğin yazar kim ...','En çok hangi dijital platformu kullanıyorsun ...',
'Hayatta gerçekleştirmek istediğin bir hayalin var mı?', 'Kaç tane kız aradaşın oldu ?','Nefret ettiğiniz ancak yine de kullandığın bir uygulama var mı?','En tuhaf korkun nedir?','Hangi takımı tutuyorsun ?','Romayı senmi yaktın?','Fiziksel olarak sana en acı veren deneyimin ne oldu?','Hangi yılda doğdun?','Boyun kaç ?','En sevdiğin hobi nedir?','Nasılsın ?','Gruptaki gizli aşık olduğun kim?',
'Nerelisin?','Naber nasıl gidiyor?','Grupta nefret ettiğin kişi kim?','Kaç tane sevgilin oldu?','Gruptaki partnerin kim?','Kendini 3 kelime ile anlatırmısın','Selam ne yapıyorsun?','En son okuduğun kitabın adı neydi','Grubu yakacakmışsın doğru mu?','En sevdiğin müzik nedir?','Googlede en son neye baktın?','Okumayı en çok sevdiğin kitap türü nedir ...','Çocukluğundan unutmadığın bir çizgi film var mı ...',
'Aşk mı? para mı?','En son yaptığın en saçma olay neydi?','Keşke şu olsada yesek dediğin şey neydi?','Karşı cinste aradığın krater nedir?','Karşı cinsin ilk neresine bakıyorsun?','Grupta sevdiğin 3 kişiyi etiketler misin?','Grupta en sevmediğin 3 kişiyi etiketler misin?','Grupta işte aradığım eş adayı dediğin kişiyi etiketler misin?','En Sevdiğin Renk Nedir ...',
'Aşkın yaşı yoktur diyorlar doğru mu?','Bir adaya düşsen yanına alacağın üç şey ne olurdu?','Grupta sevgilin var mı?','İnstagrama günde kaç story atıyorsun?','Hangi şehirde yaşıyorsun','Şehrini üç kelime ile anlatır mısın?','Memleketini üç kelime ile anlatır mısın?','Geçmişe dönüp yaşadığın bir olayı silebilmen mümkün olsaydı hangi olay olurdu?',
)

d = (
"Telefonunda en son aradığın şey neydi?","Birisi kız arkadaşın / erkek arkadaşından ayrılmak için sana 1 milyon tl önerseydi, yapar mıydın?","Bu grupda en az kimi seviyorsun ve neden?","Hiç sınıfta yüksek sesle geğirdin mi?","Hiç sınıfta yüksek sesle geğirdin mi?","Yerden bir şeyi alıp hiç yedin mi?","Bir gün karşı cins olarak uyanırsan, ilk yapacağın şey nedir?","Hiç havuzda işedin mi?","Asansörde hiç gaz kaçırdın mı?",
"Tuvalette otururken aklınıza gelen şeyler nelerdir?","Büyüyen hayali bir arkadaşınız var mıydı?","En kötü alışkanlığınız nedir?","Burnunu karıştırır mısın?","Banyoda şarkı söyler misin?","Hiç üzerine işedin mi?","Toplumda en utanç verici anınız neydi?","Aynada kendinle hiç konuştun mu?",
"Web geçmişinizi, birileri görürse utanacağınız şey ne olurdu?","Uykunda konuşur musun?","Gizli aşkın kim?","Benim hakkımda neyi sevmiyorsun?","Şu an ne renk iç çamaşır giyiyorsun?","Son attığın mesaj neydi?","İnsanları yanan bir binadan kurtarıyor olsaydınız ve bir kişiyi bu grupdan geride bırakmak zorunda kalırsanız, kim olurdu?",
"İç çamaşırlarını ne sıklıkla yıkıyorsun?","Hiç kulak kiri tattın mı?","Hiç osurup başka birini suçladın mı?","Hiç terinin tadına baktın mı?","Bu odadaki kim bugüne kadarki en kötü insan olurdu? Neden?",
"Yeniden doğmuş olsaydın, hangi yüz yılda doğmak isterdin?","Söylediğiniz veya yaptığınız bir şeyi silmek için zamanda geriye gidebilseydiniz, bu hangi yıl olurdu?","Erkek arkadaşın veya kız arkadaşın seni hiç utandırdı mı?","Birdenbire görünmez olsaydın ne yapardın?",
"Banyoda kaldığınız en uzun süre nedir ve neden bu kadar uzun süre kaldınız?","Şimdiye kadar gördüğüm en garip rüyayı anlat.","Duşta işiyor musun?","Hala yaptığın en çocukça şey nedir?","Hangi çocuk filmini tekrar tekrar izleyebilirsin?",
"Ayak kokunuz kötü mü?","Saçma takma adların var mı?","Telefonunuzda hangi uygulamada en çok zaman harcıyorsunuz?","Tek bir oturuşta yediğin en çok yemek ne?","Tek başınayken dans ediyor musun?","Karanlıktan korkar mısın?",
"Bütün gün evdeysen ne yapardın?","Günde kaç öz çekim yapıyorsunuz?","En son ne zaman dişlerini fırçaladın?","En sevdiğin pijamalar neye benziyor?","Hiç yerden bir şey yedin mi?","Yapmaman gereken bir şeyi yaparken hiç yakalandın mı?","Vücudunun hangi bölümünü seviyorsun, hangi kısmından nefret ediyorsun?","Hiç bitlendin mi?","Pantolonunu hiç kestin mi?","Tabağını yalıyor musun?","Kimsenin senin hakkında bilmediği bir şey nedir?",
"Hiç tabağını yaladın mı?","Dirseğini yalayabilir misin?","Eğer buradaki herkesi yanan bir binadan kurtarmaya çalışıyor olsaydın ve birini geride bırakmak zorunda kalırsan, kimi geride bırakırdın?","Telefonda aradığın son şey neydi?","Bir uygulamayı telefonunuzdan silmek zorunda kalsanız hangisini silerdiniz?","Bir ilişkideki en büyük korkun nedir?",
"Odanın her bir kişi hakkında bir tane olumlu, bir tane olumsuz şey söyleyin.","Sevmediğin kötü huyun var mı?","Hayatında yaptığın en çılgın şey nedir?","Üç gün boyunca bir adada mahsur kalmış olsaydınız, bu grupdan kimleri seçerdiniz?","Bu odadaki en sinir bozucu kişi kim?","Bu grupdan biriyle evlenmek zorunda kalsan kim olurdu?","En uzun ilişkiniz ne kadar sürdü?",
"Bir ünlü Instagram’da seni takip etseydi bu ünlünün kim olmasını isterdin?","Instagram’da 5 kişiyi silmek zorunda olsan kimleri silerdin?","Kaç çocuk sahibi olmak istersin?","Hayallerinizdeki kişiyi tarif edin.","Messi mi Ronaldo mu?","Pes mi Fifa mı?",
"İlk işin neydi?","Üniversite hakkındaki en büyük korkun nedir?","En iyi arkadaşının seninle aynı üniversiteye gitmesini ister misin?","Mevcut erkek arkadaşının ya da kız arkadaşının seninle aynı üniversiteye gitmesini ister misin?","Hayalindeki iş ne?",
"Hiç bir dersten başarısız oldun mu?","Hiç kopya çektin mi?","Hiç sınıfta uyudun mu?","Sınıfta asla yanında oturmak istemeyeceğin kim?","Derse hiç geç kaldın mı?","Bir öğretmenin önünde yaptığın en utanç verici şey nedir?","Hiç masanın altına sakız attın mı?",
"Hiç okulda kavga ettin mi?","Bir sınavdan aldığın en kötü puan neydi?","Sınıfta hiç uyuya kaldın mı?","Hiç gözaltına alındın mı?","Eğer görünmez olsaydın hangi derse gizlice girerdin?","En kötü grup hangisidir?","Bu grupdaki sır tutma  konusunda en çok zorlanan kişi kimdir?",
"Söylediğin en son yalan neydi?","Spor yapar mısın?","Hayatının geri kalanında sadece bir kıyafet giyebilseydin, bu kıyafetin hangi renk olurdu?","Sizce Türkiye’nin eğitim sisteminde yapılması gereken en önemli değişiklik nedir?","Karanlıktan/yükseklikten korkar mısın?",
"Kendi görünuşünü 1 ile 10 arasında puanla :)","Yaptıgın en yasadışı şey neydi?","Şimdi sana bir evlenme teklifi gelse ve sevmediğin biri olsa, ve bu sana son gelecek evlilik teklifi olsa kabul edermiydin?","Şu anki ruh haline bakarak ne tür film izlersin (aksiyon/dram/bilim kurgu/romantik komedi/biyografi/fantastik)","Kendini en ezik hissettiğin an hangisiydi ?","ilerde çocuğun olursa ne isim koymak istersin?",
"Unicorun mu olmasını isterdin ejderhan mı?","Kaç sevgilin oldu?","Hayatta unutmadığın biri var mı?","en sevdiğin şarkı?","Yapmaman gereken bir şeyi yaparken hiç yakalandın mı?","En sevdiğin sanatçı kim?","karşı cinste ilk dikkatini çeken ne?","bu yıl hayatında neyi değişmeyi uygun görüyorsun?",
"Birinin telefonunda gördüğün en tuhaf şey nedir?","Süper kahramanlar gerçekten var olsaydı Dünya nasıl bir yer olurdu?","Hayatın size öğrettiği en önemli ders nedir?","Kültürümüzün en çok sevdiğiniz yanı nedir?","Ailenizin uyguladığı en tuhaf gelenek nedir?",
"Aileniz dışında, yaşamınız üzerinde en büyük etkisi olan kişi kimdir?","Kadın/Erkek olmanın en kötü ve en iyi yanı nedir?","Beynini bir robota yerleştirebilir ve sonsuza kadar bu şekilde yaşayabilsedin,bunu yapar mıydın?","Evinizde ağırladığın en kötü misafir kimdi ve ne oldu?",
"İnsanların size ne sormasından bıktınız?","En tuhaf korkunuz nedir?","En sevdiğiniz TV programı hangisidir?","Girdiğiniz en saçma tartışma nedir?","En son söylediğin yalan nedir?", "Biriyle çıkarken yaptığın en utanç verici şey neydi?","Hiç arabanla (varsa) yanlışlıkla bir şeye birine çarptın mı?",
"Hoşuna gittiğini düşündüğün ama bir türlü açılamadığın biri oldu mu?","En tuhaf takma adın nedir?","Fiziksel olarak sana en acı veren deneyimin ne oldu?","Hangi köprüleri yakmak seni rahatlattı?","Toplu taşıma araçlarında yaptığın en çılgınca şey neydi?","Şişeden bir cin çıksa üç dileğin ne olurdu?","Dünyadaki herhangi birini Türkiye’nin başkanı yapabilseydin bu kim olurdu?",
"Şimdiye kadar bir başkasına söylediğin en acımasızca şey neydi?","Birini öperken kendini hiç kötü hissettin mi?","Hiçbir sonucu olmayacağını bilsen ne yapmak isterdin?","Bir aynanın önünde yaptığın en çılgınca şey nedir?","Şimdiye kadar başkasına söylediğin en anlamlı şey neydi?",
"Arkadaşlarınla yapmayı sevdiğin ama sevgilinin önünde asla yapmayacağın şey nedir?","Bu hayatta en çok kimi kıskanıyorsun?","En sevdiğin pijamaların neye benziyor?","Bir buluşmadan kaçmak için hiç hasta numarası yaptın mı?","Çıktığın en yaşlı kişi kim?",
"Günde kaç tane özçekim yaparsın?","Aşk için her şeyi yaparım ama “bunu” yapmam dediğin şey nedir?","Haftada kaç kez aynı pantolonu giyiyorsun?","Bugün şansın olsa lise aşkınla çıkar mısın?","Vücudunun hangi bölümlerinden gıdıklanıyorsun?",
"Çeşitli batıl inançların var mı? Varsa onlar neler?","Sevdiğini itiraf etmekten utandığın film hangisidir?","En utan verici kişisel bakım alışkanlığın nedir?","En son ne zaman ve ne için özür diledin?","Sözlü destanlar hakkında ne düşünüyorsun?",
"Utanç verici kokularınızın çoğu nereden geliyor?","Hiç sevgilini anlatmayı düşündün mü?","Hiç sevgilini biriyle aldattın mı?","Boxer mı yoksa külot mu?","Hiç havuza veya denize işedin mi?","Saçlarını uzatmayı düşünsen ne kadar uzatırdın?","Kimsenin bilmeyeceği garanti olsa kimi öldürmek isterdin?","Başkası için aldığın en ucuz hediye nedir?",
"Zamanının çoğunu en çok hangi uygulamada harcıyorsun?","Otobüste yaptığın en tuhaf şey nedir?","Hiç toplum içinde çıplak kaldın mı?","Günde ne kadar dedikodu yaparsın?","Çıkmak isteyeceğin en genç kişi kaç yaşında olurdu?","Hiç toplum içindeyken burnunu karıştırdın mı?",
"Hiç yaşın hakkında yalan söyledin mi?","Telefonundan bir uygulamayı silmek zorunda olsan bu hangisi olurdu?","Gece geç saatte yaptığın en utanç verici şey nedir?","Duş almadan en uzun süre ne kadar durdun ?","Hiç sahte kimlik kullandın mı?","Kırmızı halıda beraber yürümek istediğin ünlü isim kim?","Gizli aşkın kim?",
)

c = (
"Seçtiğiniz bir sosyal medya hesabınızdan çok çirkin bir fotoğrafınızı paylaşın.","Mesaj yazma bölümünüzü telefonunuzdan açın gözlerinizi kapatın ve rasgele bir kişiye körü körüne bir metin gönderin.","Telegramda son konuşmanı ss at.","🎀 ŞANSLI MESAJ🎊 Grupdan İstediğin Birinin Google/Youtube/İnstagram Arama Geçmişini İste","Galerinin En Alttan 7. Fotosunu gönder","Sonraki 3 tur boyunca şiveyle konuş. Farklı şivelere kayış olursa /zar Komutunu kullanarak 6 ya en cok yaklaşan oyuncu sana ceza verecek",
"Önümüzdeki 5 dakika boyunca söylediğin her şeyden sonra “mee” diyeceksin","Önümüzdeki 5 dakika içinde birinin hayvanı olun.","İnstagramını oyunculardan birine ver. 5 dk boyunca her yere bakmak serbest.","Oyundan bir kişiye serenat yap (kız ise erkeğe, erkek ise kıza)","Sonraki 3 tur boyunca şiveyle konuş.","3 dakika boyunca bebek taklidi yap!","Telefonunda ki en sevmediğin fotoğrafını at","En beğendiğin fotoğrafını at",
"Whatsapp’da 2 konuşmanı at","Özel mesajlarını ssi al ve gruba at","Whatsapp’da son konuşmanı at","Bir deftere 20 kez ben çatlağım yaz ve resmini at","Telegramda son konuşmanı ss at.","Biyografine +18 bir cümle yaz; 3 Saat duracak.!","Galerinin bir kısmını ss alıp at","Galerindeki 16. Fotoğrafı at.","Instagram yada telegramdan tanımadığın birine komik olmayan bir fıkra anlat.",
"Ninni Söyleyerek Ses At","Bugununle ilgili kısa bir hikaye uydur.","Grupta ki en çok hoşuna giden karşı cinse seni seviyorum diye mesaj at.","Galerindeki 16. Fotoğrafı at.","Galerindeki 30. Fotoğrafı at.","Whatsapp’da konuşduğun kişilerin ss ini at","Grubun üye listesine gir ve 7. kişiye anlık at. (Grup daha az kişiyse ya da aktif sayısı azsa üstten saymaya devam et)","En son konuştuğun kişiye \"Hayırlı Cumalar\" diye mesaj at.(platform farketmez)",
"Şuan ki halini fotoğraf çekip  atar mısın?","Grupta üyeler kısmına gir 11. kişiye \"Analar neler doğuruyor bee\" diye ses at ve cevabını grupla paylaş.","Profil fotoğrafına nefret ettiğin bir ünlünün resmini koy.","Kafanda yumurta kır ve fotosunu at","Gruptan sevdiğin bir kişinin fotoğrafını profil resmi yap","Balkona veya pencereye cık dısardakılerın duyacagı sekılde sarkı soyle videoya al gruba at.",
"İtiraf et: üye çalmak için kaç hesabın var?","Gruptaki 5 abazaya seni seviyorum de","İki dakika tavuk gibi davran.","Seçtiğiniz bir hayvanı taklit edin.","Seçtiğin bir nesneyi yalayın ve gruba fotosunu atın.","Gruba gerçekten utanç verici bir fotoğrafını göster.","Çirkin bir selfie çek ve sosyal medya uygulamalarından birinde yayınla 1.5 saat kalacak.","Bir kaşık un ye ve video ya al gruba at",
"Hiç tanımadığın birine Kurban Bayramınızı kutlarım deyin","Sevdiğin bir kişiye ( ben seni neden sevdim niçin sevdim niye sevdim bunların bi izahı yok gördün işte sevdim. Yaw sahi ben seni nidennn sevdim ) de. Cevap geldiğinde grupla paylaş biz de gülelim","Telegram'daki en kalabalık grubu aç ve \"`Benim adım turşu bidonu!`\" diyerek ses kaydedip en kalabalık gruba gönder.","Hemcinsin olan yakın bir arkadaşına ona aşık olduğunu söyle.","Sürahiden su iç ve fotoğraf at.","En çok konuştuğun karşı cinsten arkadaşına \" `Seni çok seviyorum galiba aşık oldum`\" yaz ve tepkisini bizimle paylaş",
"İsmini 1 saatliğine Abdül<ismin> yap. (örneğin adın Berk ise AbdülBerk yap)","İnstagram'da dm kutunu (mesajlar bölümü) ss al gruba at.","Tanımadığın birisine şu cümleyi atıp sohbet başlat: \"`Aşkımızın suya düşeceğini bilseydim , balık olurdum`\"","En komik fotoğrafını grupla paylaş.","Grupta üyeler kısmına gir 11. kişiye \"`Analar neler doğuruyor bee`\" diye ses at ve cevabını grupla paylaş.",
"Tanımadığın birine şu mesajı at sonra cevabını grupla paylaş ➡️\n  \"`Bu mesaj özel bir frekansla gönderilmiştir. Zekilerde hafıza kaybı, aptallarda kısa sureli körlük ibnelerde de bir anlık gülümseme yapar!`\"","@ yaz çıkan ilk kişiyi etiketle ve seni seviyorum yaz.","Tanımadığın birine \" `sanırım sana aşık oldum`\" diye mesaj at.","Telegram hakkında kısmına \"`Babasının Prensesi`\" yaz 1 saat boyunca dursun.","Birine Sesli Öpücük At Ve Etiketle",
"Üç çorba kaşığı acı salça (veya buna benzer bir şey) ye ve video ya al gruba at","5 dakika boyunca oyundaki birinin evcil hayvanı olmasını isteyebilirsin.","Yeri yala Ve fotoğraf/videosunu gruba at","/zar Komutunu kullanarak 6 ya en cok yaklaşan oyuncuya sosyal medya hesaplarından birini 5dk ver","3 dakika boyunca bir ünlüyü taklit et.", "Birisi taklit edilen sanatçıyı tahmin edene kadar bir sanatçıyı taklit et",
"Grubun ortaya koyduğu bir konu etrafında sekiz satır ve iki mısralık bir şiir yaz","Oyundaki kişilerin ortak kararıyla gruptan birini öp ses atarak (ortak karar verilemezse /zar komutundan 1 e en yakın oyuncuyu öp).","5 dakika boyunca oyundaki bir kişinin kölesi ol.", "Bir süpürgeyle veya paspas ile dans et ve videosunu at","Gerçek aşkının kim olduğunu ilan et","Ağzını hareket ettirmeden baştan sona alfabeyi oku okurken video at", "Aklına gelen ilk kelimeyi hemen söyle.",
"Oyundaki oyunculardan biri hakkında hikaye uydur", "15 saniye içerisinde sondan başa doğru alfabeyi oku okurken ses at", "Bir köpek gibi havla havlarken ses at","Bir şarkıyı baştan sona söyle söylerken ses at","Çıktığın en kötü ve en iyi kişiyi açıkla.","Bir dakika boyunca karşı cinsten biri gibi yürü.","Sevgiline atıp atabileceğin en acımasız mesajı gönder.","Oyunda yer alan her kişi hakkında bildiğin komik bir şey anlat.",
"Ünlü restoranlardan birini ara ve menülerini öğrenirken dalga geç.","Eski bir şarkıyı aç ve onu taklit ederek söylemeye çalış söylerken ses at","1 tur boyunca farklı bir dilde konuş.","Eski sevgiline mesaj at ve onu unutamadığını söyle.","2 tur boyunca “sen” kelimesini duyunca kuş gibi ses çıkart.","Telefondaki tarayıcı geçmişini herkese göster.","Odadan birisi için satın alacakmış gibi iç çamaşırı araştırması yap.",
)
